import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const CF="https://api.cloudflare.com/client/v4";
const ACCOUNT="bd94cb0580e86e7f40b4271a03052426";
const ZONE="44753df079f42f8995124c358b135597";
const HOST="app.cloudsales.app";
const SERVICE="cloudsales-pwa-v31";
const VERSION="2026.08.30.1";
const COMMAND="cloudsales_pwa_auth_v31";
const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});
async function command(id:string){return(await db.from("internal_command_queue").select("*").eq("id",id).maybeSingle()).data}
async function finish(id:string,status:string,result:unknown,error:string|null=null){await db.from("internal_command_queue").update({status,result,error,finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id)}
async function cf(token:string,path:string,method="GET",body?:unknown){const r=await fetch(CF+path,{method,headers:{Authorization:`Bearer ${token}`,Accept:"application/json","content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const raw=await r.text();let data:any={};try{data=JSON.parse(raw)}catch{data={raw}}return{ok:r.ok&&data?.success!==false,status:r.status,data}}
async function domains(token:string){const r=await cf(token,`/accounts/${ACCOUNT}/workers/domains`);return Array.isArray(r.data?.result)?r.data.result:[]}
async function attach(token:string){const list=await domains(token);const old=list.find((x:any)=>x.hostname===HOST&&x.zone_id===ZONE)||null;if(old?.service===SERVICE)return{ok:true,old};if(old){const d=await cf(token,`/accounts/${ACCOUNT}/workers/domains/${old.id}`,"DELETE");if(!d.ok)return{ok:false,old,status:d.status}}const a=await cf(token,`/accounts/${ACCOUNT}/workers/domains`,"PUT",{hostname:HOST,service:SERVICE,zone_id:ZONE,zone_name:"cloudsales.app"});return{ok:a.ok,old,status:a.status,errors:a.data?.errors||[]}}
async function restore(token:string,old:any){const list=await domains(token);const current=list.find((x:any)=>x.hostname===HOST&&x.zone_id===ZONE);if(current)await cf(token,`/accounts/${ACCOUNT}/workers/domains/${current.id}`,"DELETE");if(old?.service)await cf(token,`/accounts/${ACCOUNT}/workers/domains`,"PUT",{hostname:HOST,service:old.service,zone_id:ZONE,zone_name:"cloudsales.app"})}
async function text(url:string){const r=await fetch(`${url}${url.includes("?")?"&":"?"}r=${Date.now()}`,{headers:{"cache-control":"no-cache",pragma:"no-cache"}});if(!r.ok)throw new Error(`fetch_${r.status}_${url}`);return await r.text()}
async function bytes(url:string){const r=await fetch(`${url}${url.includes("?")?"&":"?"}r=${Date.now()}`,{headers:{"cache-control":"no-cache"}});if(!r.ok)throw new Error(`fetch_${r.status}_${url}`);return new Uint8Array(await r.arrayBuffer())}
function b64(data:Uint8Array){let out="";for(let i=0;i<data.length;i+=32768)out+=String.fromCharCode(...data.subarray(i,Math.min(i+32768,data.length)));return btoa(out)}
async function digest(data:Uint8Array){return[...new Uint8Array(await crypto.subtle.digest("SHA-256",data))].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function hashInline(value:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));let out="";for(const b of d)out+=String.fromCharCode(b);return btoa(out)}
function brand(source:string){let page=source;page=page.replace(/<link rel="manifest"[^>]*>/i,`<link rel="manifest" href="/manifest.webmanifest?v=${VERSION}">`).replace(/<link rel="icon"[^>]*>/gi,"").replace(/<link rel="apple-touch-icon"[^>]*>/gi,"");page=page.replace("</head>",`<link rel="icon" type="image/png" sizes="512x512" href="/cloudsales-favicon-official-v2.png?v=${VERSION}"><link rel="shortcut icon" type="image/png" href="/cloudsales-favicon-official-v2.png?v=${VERSION}"><link rel="apple-touch-icon" sizes="512x512" href="/cloudsales-app-icon-official-v2.png?v=${VERSION}"></head>`).replace(/install\.js\?v=[^\"']+/g,`install.js?v=${VERSION}`).replace(/<div class="logo"><img src="\/icon\.svg" alt="">CloudSales<\/div>/gi,`<div class="logo official-logo"><img src="/cloudsales-logo-official-v2.png?v=${VERSION}" alt="CloudSales"></div>`).replace(/<div class="brandrow"><img src="\/icon\.svg" alt="">CloudSales<\/div>/gi,`<div class="brandrow official-brandrow"><img src="/cloudsales-logo-official-v2.png?v=${VERSION}" alt="CloudSales"></div>`).replace(/src="\/icon\.svg"/gi,`src="/cloudsales-app-icon-official-v2.png?v=${VERSION}"`).replace("</style>",`.official-logo img{width:min(250px,80vw)!important;height:auto!important;max-width:none!important}.official-brandrow img{width:185px!important;height:auto!important;max-width:100%!important}</style>`);for(const path of ['/auth-runtime-v2.js','/app-runtime-v14.js','/meta-runtime-v1.js','/cloudy-runtime-v3.js','/works-runtime-v1.js','/ad-spend-runtime-v1.js'])if(!page.includes(path))page=page.replace("</body>",`<script src="${path}?v=${VERSION}"></script></body>`);return page}
async function csp(page:string){const scripts=[...page.matchAll(/<script(?![^>]+src=)[^>]*>([\s\S]*?)<\/script>/gi)].map(x=>x[1]);const hashes=await Promise.all(scripts.map(hashInline));return`default-src 'self'; script-src 'self' ${hashes.map(x=>`'sha256-${x}'`).join(" ")}; script-src-attr 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://storage.googleapis.com; connect-src 'self' https://fkahaqprzgcimgyathqx.supabase.co; worker-src 'self' blob:; font-src 'self' data:; media-src 'self' blob: data:; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';`}
function worker(page:string,manifest:string,sw:string,scripts:Record<string,string>,icon512:string,icon192:string,logo:string,policy:string){return`const PAGE=${JSON.stringify(page)},MANIFEST=${JSON.stringify(manifest)},SW=${JSON.stringify(sw)},SCRIPTS=${JSON.stringify(scripts)},I512=${JSON.stringify(icon512)},I192=${JSON.stringify(icon192)},LOGO=${JSON.stringify(logo)},CSP=${JSON.stringify(policy)},V=${JSON.stringify(VERSION)};const H={'x-cloudsales-release':V,'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(),geolocation=(),payment=(self),microphone=(self)','cross-origin-resource-policy':'same-origin','cross-origin-opener-policy':'same-origin-allow-popups','origin-agent-cluster':'?1','x-permitted-cross-domain-policies':'none','x-robots-tag':'noindex, noarchive, nosnippet'};function r(b,t='text/html; charset=utf-8',c='no-store',pc=true){return new Response(b,{headers:{...H,'content-type':t,'cache-control':c,...(pc?{'content-security-policy':CSP}:{})}})}function img(x){const u=Uint8Array.from(atob(x),c=>c.charCodeAt(0));return new Response(u,{headers:{...H,'content-type':'image/png','cache-control':'public,max-age=31536000,immutable'}})}export default{async fetch(req){const u=new URL(req.url),p=u.pathname;if(p==='/__version')return r(V,'text/plain','no-store',false);if(p==='/manifest.webmanifest')return r(MANIFEST,'application/manifest+json','no-store',false);if(p==='/sw.js')return r(SW,'application/javascript; charset=utf-8','no-cache',false);if(SCRIPTS[p])return r(SCRIPTS[p],'application/javascript; charset=utf-8','no-cache',false);if(p==='/cloudsales-logo-official-v2.png')return img(LOGO);if(p==='/cloudsales-app-icon-official-v2-192.png'||p==='/icon-192.png')return img(I192);if(['/cloudsales-app-icon-official-v2.png','/cloudsales-favicon-official-v2.png','/favicon.png','/favicon.ico','/apple-touch-icon.png','/icon-512.png'].includes(p))return img(I512);if(p==='/icon.svg'||p==='/favicon.svg')return Response.redirect(u.origin+'/cloudsales-favicon-official-v2.png?v='+V,301);return r(PAGE)}};`}
async function upload(token:string,code:string){const form=new FormData();form.append("metadata",new Blob([JSON.stringify({main_module:"main.mjs",compatibility_date:"2026-08-30"})],{type:"application/json"}));form.append("main.mjs",new Blob([code],{type:"application/javascript+module"}),"main.mjs");const r=await fetch(`${CF}/accounts/${ACCOUNT}/workers/scripts/${SERVICE}`,{method:"PUT",headers:{Authorization:`Bearer ${token}`},body:form});const raw=await r.text();let data:any={};try{data=JSON.parse(raw)}catch{data={raw}}return{ok:r.ok&&data?.success!==false,status:r.status,errors:data?.errors||[]}}
async function check(path:string){const r=await fetch(`https://${HOST}${path}${path.includes("?")?"&":"?"}qa=${Date.now()}`,{headers:{"cache-control":"no-cache",pragma:"no-cache"}});return{status:r.status,body:await r.text(),release:r.headers.get("x-cloudsales-release")||"",type:r.headers.get("content-type")||""}}
async function checkBytes(path:string){const r=await fetch(`https://${HOST}${path}?qa=${Date.now()}`,{headers:{"cache-control":"no-cache"}});const data=new Uint8Array(await r.arrayBuffer());return{status:r.status,hash:await digest(data),size:data.length,type:r.headers.get("content-type")||""}}

Deno.serve(async req=>{
  if(req.method!=="POST")return json({error:"method_not_allowed"},405);
  const body=await req.json().catch(()=>({}));const id=String(body.command_id||"");const queued=await command(id);
  if(!queued||queued.command_type!==COMMAND||queued.status!=="queued"||new Date(queued.expires_at).getTime()<=Date.now())return json({error:"invalid_command"},403);
  await db.from("internal_command_queue").update({status:"running",started_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);
  const token=Deno.env.get("CLOUDFLARE_API_TOKEN_CLOUDSALES")||"";if(!token){await finish(id,"failed",null,"cloudflare_token_missing");return json({error:"cloudflare_token_missing"},503)}
  const result:any={version:VERSION,service:SERVICE};let old:any=null;
  try{
    const sourceCommit=/^[0-9a-f]{40}$/.test(String(queued.input?.source_commit||""))?String(queued.input.source_commit):"main";result.source_commit=sourceCommit;
    const raw=`https://raw.githubusercontent.com/crmcloudsales/CLOUDSALES/${sourceCommit}/web`;
    const page=brand(await text(`${raw}/pwa.html`));const policy=await csp(page);const manifest=await text(`${raw}/manifest.webmanifest`);const sw=await text(`${raw}/sw.js`);
    const paths=['/install.js','/auth-runtime-v2.js','/app-runtime-v14.js','/meta-runtime-v1.js','/cloudy-runtime-v3.js','/works-runtime-v1.js','/ad-spend-runtime-v1.js','/ai-chat-runtime-v2.js','/ai-chat-backfill-v1.js','/ai-chat-channels-v1.js','/calendar-runtime-v1.js','/ai-chat-calendar-bridge-v1.js'];
    const scripts:Record<string,string>={};for(const path of paths)scripts[path]=await text(`${raw}${path}`);
    const [i512,i192,logo]=await Promise.all([bytes(`${raw}/assets/cloudsales-app-icon-official-v2.png`),bytes(`${raw}/assets/cloudsales-app-icon-official-v2-192.png`),bytes(`${raw}/assets/cloudsales-logo-official-v2.png`)]);const expected={icon512:await digest(i512),icon192:await digest(i192),logo:await digest(logo)};
    result.upload=await upload(token,worker(page,manifest,sw,scripts,b64(i512),b64(i192),b64(logo),policy));if(!result.upload.ok)throw new Error(`upload_failed_${result.upload.status}`);
    const attached=await attach(token);old=attached.old;if(!attached.ok)throw new Error("attach_failed");await new Promise(r=>setTimeout(r,7000));
    const [root,m,installer,auth,ops,meta,cloudy,works,adspend,swLive,live512,live192,liveLogo]=await Promise.all([check('/'),check('/manifest.webmanifest'),check('/install.js'),check('/auth-runtime-v2.js'),check('/app-runtime-v14.js'),check('/meta-runtime-v1.js'),check('/cloudy-runtime-v3.js'),check('/works-runtime-v1.js'),check('/ad-spend-runtime-v1.js'),check('/sw.js'),checkBytes('/cloudsales-app-icon-official-v2.png'),checkBytes('/cloudsales-app-icon-official-v2-192.png'),checkBytes('/cloudsales-logo-official-v2.png')]);
    const tests={release:root.status===200&&root.release===VERSION,exact_logo_visible:root.body.includes(`/cloudsales-logo-official-v2.png?v=${VERSION}`),exact_favicon:root.body.includes(`/cloudsales-favicon-official-v2.png?v=${VERSION}`),no_legacy_icon:!root.body.includes('/icon.svg'),manifest_identity:m.body.includes('"id": "/cloudsales-app-v2"'),installer_native_prompt:installer.body.includes('beforeinstallprompt'),auth_explicit_email:root.body.includes(`/auth-runtime-v2.js?v=${VERSION}`)&&auth.body.includes('claimPending')&&auth.body.includes('authorize_email')&&auth.body.includes('signup_confirmation')&&auth.body.includes('signup_confirmation_resend')&&auth.body.includes('signupEmailNotice')&&auth.body.includes('un único correo de confirmación'),mobile_ops:ops.body.includes('Operational Center')&&ops.body.includes('tenant-ops-api'),meta_ads:meta.body.includes("META_PROVIDER='meta_ads'")&&meta.body.includes("META_FN='cloudflare-pwa-release-v10'"),cloudy_voice:cloudy.body.includes('MediaRecorder')&&cloudy.body.includes('cloudy-voice?mode=transcribe')&&cloudy.body.includes('cloudy-voice?mode=tts')&&!cloudy.body.includes('SpeechRecognition'),works:works.body.includes('Works · Trabajos')&&works.body.includes('works.snapshot'),ad_spend:adspend.body.includes('Ad Spend & Billing')&&adspend.body.includes('CloudSales no recibe ni almacena'),sw_release:swLive.body.includes(`cloudsales-pwa-${VERSION}`)&&swLive.body.includes('/auth-runtime-v2.js'),icon512:live512.hash===expected.icon512&&/image\/png/i.test(live512.type),icon192:live192.hash===expected.icon192&&/image\/png/i.test(live192.type),logo:liveLogo.hash===expected.logo&&/image\/png/i.test(liveLogo.type)};
    result.tests=tests;result.hashes=expected;if(Object.values(tests).some(v=>v!==true))throw new Error("pwa_auth_v31_smoke_failed");
    await db.from("audit_log").insert({actor_type:"system",action:"cloudsales.pwa.auth_v31.promoted",entity_type:"release",entity_id:VERSION,success:true,context:{service:SERVICE,source_commit:sourceCommit,tests,hashes:expected}});
    await finish(id,"succeeded",result,null);return json(result);
  }catch(error){const message=String((error as Error).message||error).slice(0,500);result.error=message;if(old?.service)await restore(token,old);await finish(id,"failed",result,message);return json(result,500)}
});
