import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const CF="https://api.cloudflare.com/client/v4",ACCOUNT="bd94cb0580e86e7f40b4271a03052426",ZONE="44753df079f42f8995124c358b135597",HOST="app.cloudsales.app",SERVICE="cloudsales-pwa-v31",VERSION="2026.09.03.8",COMMAND="cloudsales_pwa_icon_safearea_v31",U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});
const LOCALES=["es","en","fr","it","pt-BR","de","ar-AE","ru","he","zh-CN","ja"];
const PAGE_RUNTIMES=["/auth-runtime-v2.js","/app-runtime-v14.js","/meta-runtime-v1.js","/cloudy-runtime-v3.js","/works-runtime-v1.js","/ad-spend-runtime-v1.js","/ai-chat-runtime-v2.js","/ai-chat-backfill-v1.js","/ai-chat-channels-v1.js","/calendar-runtime-v1.js","/ai-chat-calendar-bridge-v1.js","/contact-profile-runtime-v1.js","/dashboard-runtime-v3.js","/sales-analytics-runtime-v1.js","/native-shell-runtime-v1.js","/pwa-polish-runtime-v1.js","/workspace-polish-runtime-v1.js","/pwa-i18n-runtime-v1.js","/pwa-i18n-complete-v2.js","/cloudy-executive-runtime-v1.js"],SERVED_SCRIPTS=["/install.js",...PAGE_RUNTIMES];
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
async function cmd(id:string){return(await db.from("internal_command_queue").select("*").eq("id",id).maybeSingle()).data}
async function done(id:string,status:string,result:unknown,error:string|null=null){await db.from("internal_command_queue").update({status,result,error,finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id)}
async function cf(token:string,path:string,method="GET",body?:unknown){const r=await fetch(CF+path,{method,headers:{Authorization:`Bearer ${token}`,Accept:"application/json","content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)}),t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{}return{ok:r.ok&&d?.success!==false,status:r.status,data:d}}
async function domains(token:string){const r=await cf(token,`/accounts/${ACCOUNT}/workers/domains`);return Array.isArray(r.data?.result)?r.data.result:[]}
async function attach(token:string){const list=await domains(token),old=list.find((x:any)=>x.hostname===HOST&&x.zone_id===ZONE)||null;if(old?.service===SERVICE)return{ok:true,old};if(old){const del=await cf(token,`/accounts/${ACCOUNT}/workers/domains/${old.id}`,"DELETE");if(!del.ok)return{ok:false,old}}const a=await cf(token,`/accounts/${ACCOUNT}/workers/domains`,"PUT",{hostname:HOST,service:SERVICE,zone_id:ZONE,zone_name:"cloudsales.app"});return{ok:a.ok,old}}
async function text(url:string){const r=await fetch(`${url}${url.includes('?')?'&':'?'}r=${Date.now()}`,{headers:{"cache-control":"no-cache",pragma:"no-cache"}});if(!r.ok)throw new Error(`fetch_${r.status}_${url}`);return r.text()}
async function bytes(url:string){const r=await fetch(`${url}${url.includes('?')?'&':'?'}r=${Date.now()}`,{headers:{"cache-control":"no-cache"}});if(!r.ok)throw new Error(`fetch_${r.status}_${url}`);return new Uint8Array(await r.arrayBuffer())}
function b64(a:Uint8Array){let s="";for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,Math.min(i+32768,a.length)));return btoa(s)}
async function digest(a:Uint8Array){return[...new Uint8Array(await crypto.subtle.digest("SHA-256",a))].map(x=>x.toString(16).padStart(2,"0")).join("")}
function brand(src:string){let p=src.replace(/<link rel="manifest"[^>]*>/i,`<link rel="manifest" href="/manifest.webmanifest?v=${VERSION}">`);for(const path of PAGE_RUNTIMES)if(!p.includes(path))p=p.replace("</body>",`<script src="${path}?v=${VERSION}"></script></body>`);return p}
function worker(page:string,manifest:string,sw:string,scripts:Record<string,string>,catalogs:Record<string,string>,i512:string,i192:string,logo:string){return`const PAGE=${JSON.stringify(page)},MANIFEST=${JSON.stringify(manifest)},SW=${JSON.stringify(sw)},SCRIPTS=${JSON.stringify(scripts)},CATALOGS=${JSON.stringify(catalogs)},I512=${JSON.stringify(i512)},I192=${JSON.stringify(i192)},LOGO=${JSON.stringify(logo)},V=${JSON.stringify(VERSION)};const H={'x-cloudsales-release':V,'x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'};function r(b,t='text/html; charset=utf-8',c='no-store',s=200){return new Response(b,{status:s,headers:{...H,'content-type':t,'cache-control':c}})}function img(x){return new Response(Uint8Array.from(atob(x),c=>c.charCodeAt(0)),{headers:{...H,'content-type':'image/png','cache-control':'public,max-age=31536000,immutable'}})}export default{async fetch(req){const u=new URL(req.url),p=u.pathname.replace(/\\\/+$/,'')||'/';if(p==='/__version')return r(V,'text/plain');if(p==='/manifest.webmanifest')return r(MANIFEST,'application/manifest+json','public,max-age=300');if(p==='/sw.js')return r(SW,'application/javascript','no-cache');if(SCRIPTS[p])return r(SCRIPTS[p],'application/javascript','public,max-age=300');if(p.startsWith('/i18n/catalog-v1/')&&p.endsWith('.json')){const lc=decodeURIComponent(p.slice('/i18n/catalog-v1/'.length,-5)),x=CATALOGS[lc];return x?r(x,'application/json; charset=utf-8','public,max-age=3600,stale-while-revalidate=86400'):r('{"error":"not_found"}','application/json','no-store',404)}if(p==='/cloudsales-app-icon-official-v4-192.png'||p==='/icon-192.png')return img(I192);if(['/cloudsales-app-icon-official-v4.png','/cloudsales-favicon-official-v4.png','/favicon.png','/favicon.ico','/apple-touch-icon.png','/icon-512.png'].includes(p))return img(I512);if(p==='/cloudsales-logo-official-v2.png')return img(LOGO);return r(PAGE)}};`}
async function upload(token:string,code:string){const f=new FormData();f.append("metadata",new Blob([JSON.stringify({main_module:"main.mjs",compatibility_date:"2026-09-03"})],{type:"application/json"}));f.append("main.mjs",new Blob([code],{type:"application/javascript+module"}),"main.mjs");const r=await fetch(`${CF}/accounts/${ACCOUNT}/workers/scripts/${SERVICE}`,{method:"PUT",headers:{Authorization:`Bearer ${token}`},body:f});return{ok:r.ok,status:r.status}}
async function bcheck(path:string){const r=await fetch(`https://${HOST}${path}${path.includes('?')?'&':'?'}qa=${Date.now()}`,{headers:{'cache-control':'no-cache'}}),a=new Uint8Array(await r.arrayBuffer());return{status:r.status,hash:await digest(a),size:a.length,text:new TextDecoder().decode(a).slice(0,4000),type:r.headers.get('content-type')||'',release:r.headers.get('x-cloudsales-release')||''}}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const body=await req.json().catch(()=>({})),id=String(body.command_id||""),q=await cmd(id);if(!q||q.command_type!==COMMAND||q.status!=="queued"||new Date(q.expires_at).getTime()<=Date.now())return json({error:"invalid_command"},403);await db.from("internal_command_queue").update({status:"running",started_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);const token=Deno.env.get("CLOUDFLARE_API_TOKEN_CLOUDSALES")||"";const result:any={version:VERSION};try{const requested=String(q.input?.source_commit||""),commit=/^[0-9a-f]{40}$/i.test(requested)?requested:"main",RAW=`https://raw.githubusercontent.com/crmcloudsales/CLOUDSALES/${commit}/web`,page=brand(await text(`${RAW}/pwa.html`)),manifest=await text(`${RAW}/manifest.webmanifest`),sw=await text(`${RAW}/sw.js`),scripts:Record<string,string>={},catalogs:Record<string,string>={};for(const p of SERVED_SCRIPTS)scripts[p]=await text(`${RAW}${p}`);for(const lc of LOCALES){const raw=await text(`${RAW}/i18n/catalog-v1/${encodeURIComponent(lc)}.json`),parsed=JSON.parse(raw);if(parsed?.locale!==lc||!parsed?.pwa||Object.keys(parsed.pwa).length<100)throw new Error(`catalog_invalid_${lc}`);catalogs[lc]=raw}const[i512,i192,logo]=await Promise.all([bytes(`${RAW}/assets/cloudsales-app-icon-official-v4.png`),bytes(`${RAW}/assets/cloudsales-app-icon-official-v4-192.png`),bytes(`${RAW}/assets/cloudsales-logo-official-v2.png`)]),expected={i512:await digest(i512),i192:await digest(i192)};result.source_commit=commit;result.upload=await upload(token,worker(page,manifest,sw,scripts,catalogs,b64(i512),b64(i192),b64(logo)));if(!result.upload.ok)throw new Error('upload_failed');const a=await attach(token);if(!a.ok)throw new Error('attach_failed');await new Promise(r=>setTimeout(r,9000));const[l512,l192,ver,overlay,...cats]=await Promise.all([bcheck('/cloudsales-app-icon-official-v4.png'),bcheck('/cloudsales-app-icon-official-v4-192.png'),bcheck('/__version'),bcheck('/pwa-i18n-complete-v2.js'),...LOCALES.map(lc=>bcheck(`/i18n/catalog-v1/${encodeURIComponent(lc)}.json`))]);result.tests={icon512:l512.hash===expected.i512,icon192:l192.hash===expected.i192,release:ver.status===200&&ver.text.includes(VERSION)&&ver.release===VERSION,overlay:overlay.status===200&&overlay.text.includes('cs-pwa-i18n-complete-v2'),catalogs:cats.every((x,i)=>x.status===200&&/application\/json/i.test(x.type)&&x.text.includes(`\"locale\": \"${LOCALES[i]}\"`))};if(Object.values(result.tests).some(v=>v!==true))throw new Error('pwa_i18n_smoke_failed');await done(id,'succeeded',result);return json(result)}catch(e){const err=String((e as Error).message||e).slice(0,500);result.error=err;await done(id,'failed',result,err);return json(result,500)}});
