import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2";
const CF="https://api.cloudflare.com/client/v4",ACCOUNT="bd94cb0580e86e7f40b4271a03052426",ZONE="44753df079f42f8995124c358b135597";
const HOST="app.cloudsales.app",SERVICE="cloudsales-pwa-v33",VERSION="2026.09.05.telnyx-v33",COMMAND="cloudsales_pwa_release_v33";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}});
const LOCALES=["es","en","fr","it","pt-BR","de","ar-AE","ru","he","zh-CN","ja"];
const REQUIRED=["/install.js","/auth-runtime-v2.js","/app-runtime-v14.js","/meta-runtime-v1.js","/cloudy-runtime-v3.js","/cloudy-productivity-runtime-v1.js","/connect-center-runtime-v1.js","/works-runtime-v1.js","/ad-spend-runtime-v1.js","/ai-chat-runtime-v2.js","/ai-chat-backfill-v1.js","/ai-chat-channels-v1.js","/calendar-runtime-v1.js","/ai-chat-calendar-bridge-v1.js","/contact-profile-runtime-v1.js","/dashboard-runtime-v3.js","/sales-analytics-runtime-v1.js","/native-shell-runtime-v1.js","/canonical-pwa-runtime-v1.js","/pwa-polish-runtime-v1.js","/workspace-polish-runtime-v1.js","/pwa-i18n-runtime-v1.js","/cloudsales-static-i18n-v2.js","/cloudy-executive-runtime-v1.js","/billing-runtime-v1.js","/member-runtime-v1.js","/cloudy-voice-client-policy-v1.js","/pwa-ui-runtime-v1.js","/pwa-connect-fix-runtime-v1.js"];
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
async function cmd(id:string){return(await db.from("internal_command_queue").select("*").eq("id",id).maybeSingle()).data}
async function done(id:string,status:string,result:any,error:string|null=null){await db.from("internal_command_queue").update({status,result,error,finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id)}
async function cf(token:string,path:string,method="GET",body?:unknown){const r=await fetch(CF+path,{method,headers:{Authorization:`Bearer ${token}`,Accept:"application/json","content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)}),t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={raw:t}}return{ok:r.ok&&d?.success!==false,status:r.status,data:d}}
async function domains(token:string){const r=await cf(token,`/accounts/${ACCOUNT}/workers/domains`);return Array.isArray(r.data?.result)?r.data.result:[]}
async function attach(token:string){const list=await domains(token),old=list.find((x:any)=>x.hostname===HOST&&x.zone_id===ZONE)||null;if(old?.service===SERVICE)return{ok:true,old,changed:false};if(old){const d=await cf(token,`/accounts/${ACCOUNT}/workers/domains/${old.id}`,"DELETE");if(!d.ok)return{ok:false,old,changed:false,error:`delete_${d.status}`}}const a=await cf(token,`/accounts/${ACCOUNT}/workers/domains`,"PUT",{hostname:HOST,service:SERVICE,zone_id:ZONE,zone_name:"cloudsales.app"});return{ok:a.ok,old,changed:a.ok,error:a.ok?null:`attach_${a.status}`}}
async function restore(token:string,old:any){const list=await domains(token),now=list.find((x:any)=>x.hostname===HOST&&x.zone_id===ZONE);if(now)await cf(token,`/accounts/${ACCOUNT}/workers/domains/${now.id}`,"DELETE");if(old?.service)await cf(token,`/accounts/${ACCOUNT}/workers/domains`,"PUT",{hostname:HOST,service:old.service,zone_id:ZONE,zone_name:"cloudsales.app"})}
async function text(url:string){const r=await fetch(`${url}${url.includes('?')?'&':'?'}r=${Date.now()}`,{headers:{"cache-control":"no-cache",pragma:"no-cache"}});if(!r.ok)throw Error(`fetch_${r.status}_${url}`);return r.text()}
async function bytes(url:string){const r=await fetch(`${url}${url.includes('?')?'&':'?'}r=${Date.now()}`,{headers:{"cache-control":"no-cache"}});if(!r.ok)throw Error(`fetch_${r.status}_${url}`);return new Uint8Array(await r.arrayBuffer())}
function b64(a:Uint8Array){let s="";for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,Math.min(i+32768,a.length)));return btoa(s)}
async function hash(a:Uint8Array){return[...new Uint8Array(await crypto.subtle.digest("SHA-256",Uint8Array.from(a).buffer))].map(x=>x.toString(16).padStart(2,"0")).join("")}
function scripts(page:string,sw:string){const set=new Set(REQUIRED);for(const src of [page,sw])for(const m of src.matchAll(/["'](\/[^"']+\.js)(?:\?[^"']*)?["']/g))set.add(m[1]);return[...set].filter(p=>/^\/[A-Za-z0-9._\/-]+\.js$/.test(p))}
function brand(page:string){return page.replace(/<link rel="manifest"[^>]*>/i,`<link rel="manifest" href="/manifest.webmanifest?v=${VERSION}">`)}
function worker(page:string,manifest:string,sw:string,js:Record<string,string>,catalogs:Record<string,string>,i512:string,i192:string,logo:string){return`const PAGE=${JSON.stringify(page)},MANIFEST=${JSON.stringify(manifest)},SW=${JSON.stringify(sw)},JS=${JSON.stringify(js)},CAT=${JSON.stringify(catalogs)},I512=${JSON.stringify(i512)},I192=${JSON.stringify(i192)},LOGO=${JSON.stringify(logo)},V=${JSON.stringify(VERSION)};const H={'x-cloudsales-release':V,'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(),geolocation=(),payment=(self),microphone=(self)','x-robots-tag':'noindex, noarchive'};function r(b,t='text/html; charset=utf-8',c='no-store',s=200){return new Response(b,{status:s,headers:{...H,'content-type':t,'cache-control':c}})}function img(x){return new Response(Uint8Array.from(atob(x),c=>c.charCodeAt(0)),{headers:{...H,'content-type':'image/png','cache-control':'public,max-age=31536000,immutable'}})}export default{async fetch(req){const u=new URL(req.url),p=u.pathname.replace(/\\\/+$/,'')||'/';if(p==='/__version')return r(V,'text/plain');if(p==='/manifest.webmanifest')return r(MANIFEST,'application/manifest+json','no-store');if(p==='/sw.js')return r(SW,'application/javascript;charset=utf-8','no-cache');if(JS[p])return r(JS[p],'application/javascript;charset=utf-8','no-cache');if(p.startsWith('/i18n/catalog-v1/')&&p.endsWith('.json')){const lc=decodeURIComponent(p.slice('/i18n/catalog-v1/'.length,-5)),x=CAT[lc];return x?r(x,'application/json;charset=utf-8','public,max-age=3600,stale-while-revalidate=86400'):r('{"error":"not_found"}','application/json','no-store',404)}if(p==='/icon-192.png'||p==='/cloudsales-isotipo-official-192.png')return img(I192);if(['/icon-512.png','/icon.svg','/favicon.svg','/favicon.png','/favicon.ico','/apple-touch-icon.png','/cloudsales-isotipo-official-512.png'].includes(p))return img(I512);if(p==='/cloudsales-logo-official-v2.png')return img(LOGO);return r(PAGE)}};`}
async function upload(token:string,code:string){const f=new FormData();f.append("metadata",new Blob([JSON.stringify({main_module:"main.mjs",compatibility_date:"2026-09-05"})],{type:"application/json"}));f.append("main.mjs",new Blob([code],{type:"application/javascript+module"}),"main.mjs");let last:any;for(let n=0;n<4;n++){const r=await fetch(`${CF}/accounts/${ACCOUNT}/workers/scripts/${SERVICE}`,{method:"PUT",headers:{Authorization:`Bearer ${token}`},body:f}),t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={raw:t}}last={ok:r.ok&&d?.success!==false,status:r.status,errors:d?.errors||[]};if(last.ok)return last;if(r.status!==429)return last;await new Promise(x=>setTimeout(x,4000*(n+1)))}return last}
async function preflight(token:string,notBefore:number){const vr=await cf(token,`/accounts/${ACCOUNT}/workers/scripts/${SERVICE}/versions`),items=vr.data?.result?.items||vr.data?.result||[],v=Array.isArray(items)?items[0]:null;if(!vr.ok||!v?.id)throw Error("worker_version_missing");const cr=await cf(token,`/accounts/${ACCOUNT}/workers/scripts/${SERVICE}/versions/${v.id}/content`),r=cr.data?.result||{},created=Date.parse(r?.metadata?.created_on||v?.metadata?.created_on||""),handlers=r?.resources?.script?.handlers||[],compat=r?.resources?.script_runtime?.compatibility_date||"";const result={version_id:v.id,created_on:r?.metadata?.created_on||v?.metadata?.created_on||null,etag:r?.resources?.script?.etag||null,fetch_handler:Array.isArray(handlers)&&handlers.includes("fetch"),compatibility_date:compat};if(!cr.ok||!Number.isFinite(created)||created<notBefore||!result.fetch_handler||compat!=="2026-09-05")throw Error("worker_version_preflight_failed");return result}
async function check(path:string){let last:any;for(let i=0;i<5;i++){try{const r=await fetch(`https://${HOST}${path}${path.includes('?')?'&':'?'}canary=${Date.now()}`,{headers:{"cache-control":"no-cache",pragma:"no-cache"}});return{ok:r.ok,status:r.status,text:await r.text(),release:r.headers.get("x-cloudsales-release")||""}}catch(e){last=e;await new Promise(r=>setTimeout(r,1200*(i+1)))}}throw last}
async function smoke(){const[ver,connect,root]=await Promise.all([check("/__version"),check("/connect-center-runtime-v1.js"),check("/")]);return{version:ver.ok&&ver.text.includes(VERSION)&&ver.release===VERSION,connect:connect.ok&&connect.text.includes("WhatsApp")&&connect.text.includes("SMS / MMS")&&connect.text.includes("Voice")&&connect.text.includes("Google Workspace")&&connect.text.includes("connection-secret-setup"),root:root.ok&&root.text.includes("CloudSales — Cloudy runs your business")}}
Deno.serve(async req=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const body=await req.json().catch(()=>({})),id=String(body.command_id||""),q=await cmd(id);if(!q||q.command_type!==COMMAND||q.status!=="queued"||new Date(q.expires_at).getTime()<=Date.now())return json({error:"invalid_command"},403);const started=Date.now();await db.from("internal_command_queue").update({status:"running",started_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);const token=Deno.env.get("CLOUDFLARE_API_TOKEN_CLOUDSALES")||"",result:any={version:VERSION,service:SERVICE};let mapping:any=null;try{if(!token)throw Error("cloudflare_token_missing");const requested=String(q.input?.source_commit||""),commit=/^[0-9a-f]{40}$/i.test(requested)?requested:"main",RAW=`https://raw.githubusercontent.com/crmcloudsales/CLOUDSALES/${commit}/web`;const page=brand(await text(`${RAW}/pwa.html`)),manifest=await text(`${RAW}/manifest.webmanifest`),sw=await text(`${RAW}/sw.js`),js:Record<string,string>={},catalogs:Record<string,string>={};const paths=scripts(page,sw);for(const p of paths)js[p]=await text(`${RAW}${p}`);for(const lc of LOCALES){try{const raw=await text(`${RAW}/i18n/catalog-v1/${encodeURIComponent(lc)}.json`),v=JSON.parse(raw);if(v?.locale===lc&&v?.pwa)catalogs[lc]=raw}catch{}}const[i512,i192,logo]=await Promise.all([bytes(`${RAW}/assets/cloudsales-isotipo-official-512.png`),bytes(`${RAW}/assets/cloudsales-isotipo-official-192.png`),bytes(`${RAW}/assets/cloudsales-logo-official-v2.png`)]);result.source_commit=commit;result.script_count=paths.length;if(q.input?.promote_existing===true){result.upload={ok:true,skipped:true}}else{result.upload=await upload(token,worker(page,manifest,sw,js,catalogs,b64(i512),b64(i192),b64(logo)));if(!result.upload.ok)throw Error("upload_failed")}result.preflight=await preflight(token,q.input?.promote_existing===true?Date.parse("2026-09-05T18:17:50Z"):started-5000);mapping=await attach(token);result.mapping=mapping;if(!mapping.ok)throw Error(mapping.error||"prod_attach_failed");await new Promise(r=>setTimeout(r,3500));result.smoke=await smoke();if(Object.values(result.smoke).some(v=>v!==true)){if(mapping.changed)await restore(token,mapping.old);throw Error("prod_canary_smoke_failed_rollback")}await done(id,"succeeded",result);return json(result)}catch(e){const er=String((e as Error).message||e);if(mapping?.changed&&!result.smoke)await restore(token,mapping.old);result.error=er;await done(id,"failed",result,er);return json(result,500)}});