import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const OAUTH_RELAY=`${URL}/functions/v1/oauth-callback-relay`;
const te=new TextEncoder();
const headers={
  "content-type":"text/html; charset=utf-8",
  "cache-control":"no-store, max-age=0",
  "pragma":"no-cache",
  "x-content-type-options":"nosniff",
  "x-frame-options":"DENY",
  "referrer-policy":"no-referrer",
  "cross-origin-opener-policy":"same-origin",
  "content-security-policy":"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'"
};

type SetupStatus={stripe:boolean;cloudflare:boolean;highlevel:boolean;google_ads:boolean;google_developer_token:boolean;meta_ads:boolean};
const EMPTY_STATUS:SetupStatus={stripe:false,cloudflare:false,highlevel:false,google_ads:false,google_developer_token:false,meta_ads:false};
const ALLOWED_PURPOSES=new Set(["cloudsales_platform_integrations","cloudsales_initial_setup"]);

async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",te.encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function esc(v:string){return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]||c))}
function badge(ok:boolean){return `<span class="badge ${ok?'ok':'todo'}">${ok?'Configured':'Not configured'}</span>`}
function page(token:string,status:SetupStatus,msg="",ok=false){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CloudSales Secure Setup</title><style>
body{margin:0;background:#080811;color:#f5f5fb;font:16px system-ui;padding:24px}.wrap{max-width:760px;margin:auto}.card{background:#11111d;border:1px solid #29293a;border-radius:24px;padding:24px}h1{margin:0 0 8px;font-size:28px}.sub{color:#aaaabd;margin:0 0 24px;line-height:1.55}.g{display:grid;gap:14px}.section{border-top:1px solid #29293a;padding-top:18px;margin-top:8px}.title{display:flex;justify-content:space-between;gap:12px;align-items:center}.title h3{margin:0 0 12px}.badge{font-size:11px;border-radius:999px;padding:5px 8px;border:1px solid #4a4a5d}.badge.ok{color:#8ef0b7;border-color:#2d6744}.badge.todo{color:#e7c17d;border-color:#67512d}label{display:block;font-size:13px;color:#c8c8d4;margin:10px 0 6px}input{width:100%;box-sizing:border-box;background:#090912;color:#fff;border:1px solid #33334a;border-radius:12px;padding:13px;font-size:15px}button{margin-top:20px;width:100%;padding:14px;border:0;border-radius:999px;background:#ff2b9b;color:#fff;font-weight:800;font-size:16px}.msg{padding:12px;border-radius:12px;margin-bottom:16px;background:${ok?'#10351f':'#4a1724'}}small{color:#858596;line-height:1.5}.brand{color:#ff2b9b;font-weight:800}.relay{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;background:#090912;border:1px solid #2f2f40;border-radius:10px;padding:10px;overflow-wrap:anywhere;color:#d6d4df}.warning{border:1px solid #5b4129;background:#241a10;border-radius:12px;padding:11px;color:#e9c38c;font-size:12px;line-height:1.5;margin-top:12px}
</style></head><body><div class="wrap"><div class="card"><div class="brand">CloudSales</div><h1>Secure integration setup</h1><p class="sub">Platform credentials go directly from this browser to CloudSales Vault. Secret values are never shown back after saving and should never be pasted into chat. Leave a complete integration section blank if it is not ready yet.</p>${msg?`<div class="msg">${esc(msg)}</div>`:''}<form method="post"><input type="hidden" name="setup_token" value="${esc(token)}"><div class="g">
<div class="section"><div class="title"><h3>Stripe — CloudSales billing</h3>${badge(status.stripe)}</div><label>Live secret key</label><input name="stripe_secret" type="password" autocomplete="new-password" placeholder="sk_live_…"><label>Live publishable key</label><input name="stripe_publishable" autocomplete="off" placeholder="pk_live_…"></div>
<div class="section"><div class="title"><h3>Cloudflare</h3>${badge(status.cloudflare)}</div><label>Cloudflare API Token</label><input name="cloudflare_token" type="password" autocomplete="new-password" placeholder="API token for CloudSales zone"></div>
<div class="section"><div class="title"><h3>HighLevel</h3>${badge(status.highlevel)}</div><label>Client ID</label><input name="highlevel_client_id" autocomplete="off"><label>Client Secret</label><input name="highlevel_client_secret" type="password" autocomplete="new-password"><label>Installation URL</label><input name="highlevel_install_url" type="url" placeholder="https://…"><label>Redirect URI</label><input name="highlevel_redirect_uri" type="url" value="https://app.cloudsales.app/?oauth=highlevel"></div>
<div class="section"><div class="title"><h3>Google Ads — CloudSales platform OAuth</h3>${badge(status.google_ads&&status.google_developer_token)}</div><small>These are CloudSales platform credentials, not a client's Google login. Configure this exact redirect URI in Google Cloud:</small><div class="relay">${esc(OAUTH_RELAY)}</div><label>OAuth Client ID</label><input name="google_ads_client_id" autocomplete="off" placeholder="…apps.googleusercontent.com"><label>OAuth Client Secret</label><input name="google_ads_client_secret" type="password" autocomplete="new-password"><label>Google Ads Developer Token</label><input name="google_ads_developer_token" type="password" autocomplete="new-password"><div class="warning">CloudSales requests only the Google Ads OAuth scope. Client advertising spend and payment methods remain with Google.</div></div>
<div class="section"><div class="title"><h3>Meta Ads — CloudSales platform OAuth</h3>${badge(status.meta_ads)}</div><small>These are the CloudSales Meta App credentials, separate from every client's Dataset/CAPI token. Configure this exact redirect URI in the Meta App:</small><div class="relay">${esc(OAUTH_RELAY)}</div><label>Meta App ID</label><input name="meta_ads_app_id" inputmode="numeric" autocomplete="off"><label>Meta App Secret</label><input name="meta_ads_app_secret" type="password" autocomplete="new-password"><div class="warning">CloudSales requests <b>ads_read</b> and <b>ads_management</b>. Dataset/CAPI credentials remain isolated under the separate Meta signals connection.</div></div>
</div><button type="submit">Save securely to Vault</button><p><small>This setup link expires automatically. Secret fields are never repopulated. CloudSales does not collect advertising card numbers, CVCs, or expiration dates.</small></p></form></div></div></body></html>`}

async function validToken(svc:any,token:string){if(!token)return false;const h=await sha(token);const {data}=await svc.from("admin_setup_tokens").select("purpose,expires_at,revoked_at").eq("token_hash",h).maybeSingle();return Boolean(data&&ALLOWED_PURPOSES.has(String(data.purpose))&&!data.revoked_at&&new Date(data.expires_at).getTime()>Date.now())}
async function status(svc:any):Promise<SetupStatus>{const[{data:settings},{data:providers}]=await Promise.all([svc.from("internal_settings").select("setting_key,secret_id,value").in("setting_key",["stripe_secret_key_cloudsales_shared_temp","stripe_publishable_key_cloudsales_shared_temp","cloudflare_api_token_cloudsales","google_ads_developer_token"]),svc.from("provider_app_credentials").select("provider_key,client_id,client_secret_secret_id,enabled").in("provider_key",["highlevel","google_ads","meta_ads"])]);const sm=new Map((settings||[]).map((x:any)=>[String(x.setting_key),x]));const pm=new Map((providers||[]).map((x:any)=>[String(x.provider_key),x]));const ready=(key:string)=>{const x:any=pm.get(key);return Boolean(x?.enabled&&x?.client_id&&x?.client_secret_secret_id)};return{stripe:Boolean((sm.get("stripe_secret_key_cloudsales_shared_temp") as any)?.secret_id||(sm.get("stripe_publishable_key_cloudsales_shared_temp") as any)?.value?.key),cloudflare:Boolean((sm.get("cloudflare_api_token_cloudsales") as any)?.secret_id),highlevel:ready("highlevel"),google_ads:ready("google_ads"),google_developer_token:Boolean((sm.get("google_ads_developer_token") as any)?.secret_id),meta_ads:ready("meta_ads")}}
async function storeSecret(svc:any,key:string,value:string,name:string,description="CloudSales secure configuration"){const {data:old}=await svc.from("internal_settings").select("secret_id").eq("setting_key",key).maybeSingle();let sid=old?.secret_id;if(sid){const {error}=await svc.rpc("service_update_secret",{p_secret_id:sid,p_secret:value,p_name:name,p_description:description});if(error)throw error}else{const {data,error}=await svc.rpc("service_store_secret",{p_secret:value,p_name:name,p_description:description});if(error||!data)throw error||new Error("secret_storage_failed");sid=data}await svc.from("internal_settings").upsert({setting_key:key,secret_id:sid,value:{configured:true,updated_at:new Date().toISOString()}},{onConflict:"setting_key"});return sid}
async function upsertProvider(svc:any,providerKey:string,clientId:string,secretId:string,redirectUri:string,extra:any={}){const {data:old}=await svc.from("provider_app_credentials").select("metadata").eq("provider_key",providerKey).maybeSingle();const {error}=await svc.from("provider_app_credentials").upsert({provider_key:providerKey,client_id:clientId,client_secret_secret_id:secretId,redirect_uri:redirectUri,enabled:true,metadata:{...(old?.metadata||{}),...extra,configured_via:"admin_secure_setup",configured_at:new Date().toISOString()}},{onConflict:"provider_key"});if(error)throw error}

Deno.serve(async req=>{const svc=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});if(req.method==="GET"){const token=new URL(req.url).searchParams.get("token")||"";if(!(await validToken(svc,token)))return new Response(page("",EMPTY_STATUS,"This setup link is invalid or expired."),{status:403,headers});return new Response(page(token,await status(svc)),{headers})}if(req.method!=="POST")return new Response("Method not allowed",{status:405,headers});const form=await req.formData();const token=String(form.get("setup_token")||"");if(!(await validToken(svc,token)))return new Response(page("",EMPTY_STATUS,"This setup link is invalid or expired."),{status:403,headers});try{
const stripeSecret=String(form.get("stripe_secret")||"").trim(),stripePk=String(form.get("stripe_publishable")||"").trim(),cf=String(form.get("cloudflare_token")||"").trim(),hlId=String(form.get("highlevel_client_id")||"").trim(),hlSecret=String(form.get("highlevel_client_secret")||"").trim(),hlInstall=String(form.get("highlevel_install_url")||"").trim(),hlRedirect=String(form.get("highlevel_redirect_uri")||"").trim(),googleId=String(form.get("google_ads_client_id")||"").trim(),googleSecret=String(form.get("google_ads_client_secret")||"").trim(),googleDeveloper=String(form.get("google_ads_developer_token")||"").trim(),metaId=String(form.get("meta_ads_app_id")||"").trim(),metaSecret=String(form.get("meta_ads_app_secret")||"").trim();const saved:string[]=[];
if(stripeSecret){if(!stripeSecret.startsWith("sk_live_"))throw new Error("Stripe secret must be a live sk_live_ key.");await storeSecret(svc,"stripe_secret_key_cloudsales_shared_temp",stripeSecret,"cloudsales/stripe/live/first_100","CloudSales Stripe live secret");saved.push("Stripe secret")}
if(stripePk){if(!stripePk.startsWith("pk_live_"))throw new Error("Stripe publishable key must start with pk_live_.");await svc.from("internal_settings").upsert({setting_key:"stripe_publishable_key_cloudsales_shared_temp",secret_id:null,value:{key:stripePk,configured:true,updated_at:new Date().toISOString()}},{onConflict:"setting_key"});saved.push("Stripe publishable key")}
if(cf){if(cf.length<20||/\s/.test(cf))throw new Error("Cloudflare token format is invalid.");await storeSecret(svc,"cloudflare_api_token_cloudsales",cf,"cloudsales/cloudflare/api-token","CloudSales Cloudflare API token");saved.push("Cloudflare token")}
if(hlId||hlSecret||hlInstall){if(!(hlId&&hlSecret&&hlInstall))throw new Error("HighLevel requires Client ID, Client Secret, and Installation URL together.");const secretId=await storeSecret(svc,"highlevel_client_secret_cloudsales",hlSecret,"cloudsales/highlevel/client-secret","HighLevel OAuth client secret");await upsertProvider(svc,"highlevel",hlId,secretId,hlRedirect||"https://app.cloudsales.app/?oauth=highlevel",{install_url:hlInstall});await svc.from("provider_app_credentials").update({install_url:hlInstall}).eq("provider_key","highlevel");saved.push("HighLevel OAuth app")}
if(googleId||googleSecret||googleDeveloper){if(!(googleId&&googleSecret&&googleDeveloper))throw new Error("Google Ads requires OAuth Client ID, OAuth Client Secret, and Developer Token together.");if(googleId.length<12||/\s/.test(googleId))throw new Error("Google Ads OAuth Client ID format is invalid.");if(googleSecret.length<12||/\s/.test(googleSecret))throw new Error("Google Ads OAuth Client Secret format is invalid.");if(googleDeveloper.length<8||/\s/.test(googleDeveloper))throw new Error("Google Ads Developer Token format is invalid.");const secretId=await storeSecret(svc,"google_ads_client_secret_cloudsales",googleSecret,"cloudsales/google_ads/client-secret","Google Ads OAuth client secret");await storeSecret(svc,"google_ads_developer_token",googleDeveloper,"cloudsales/google_ads/developer-token","Google Ads developer token");await upsertProvider(svc,"google_ads",googleId,secretId,OAUTH_RELAY,{scopes:["https://www.googleapis.com/auth/adwords"],access_type:"offline"});saved.push("Google Ads OAuth app + developer token")}
if(metaId||metaSecret){if(!(metaId&&metaSecret))throw new Error("Meta Ads requires App ID and App Secret together.");if(!/^\d{5,30}$/.test(metaId))throw new Error("Meta App ID format is invalid.");if(metaSecret.length<20||/\s/.test(metaSecret))throw new Error("Meta App Secret format is invalid.");const secretId=await storeSecret(svc,"meta_ads_app_secret_cloudsales",metaSecret,"cloudsales/meta_ads/app-secret","Meta Ads App Secret");await upsertProvider(svc,"meta_ads",metaId,secretId,OAUTH_RELAY,{scopes:["ads_read","ads_management"],graph_api_version:"v24.0"});saved.push("Meta Ads OAuth app")}
const h=await sha(token);const {data:t}=await svc.from("admin_setup_tokens").select("use_count").eq("token_hash",h).maybeSingle();await svc.from("admin_setup_tokens").update({last_used_at:new Date().toISOString(),use_count:Number(t?.use_count||0)+1}).eq("token_hash",h);return new Response(page(token,await status(svc),saved.length?`Saved securely: ${saved.join(", ")}. Secret values will not be displayed.`:"Nothing was changed.",true),{headers})}catch(e){return new Response(page(token,await status(svc),String((e as Error).message||"Setup failed."),false),{status:400,headers})}});
