import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")!;
const A=Deno.env.get("SUPABASE_ANON_KEY")!;
const S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const PROVIDER="meta_ads";
const CAMPAIGN_PROVIDER="meta";
const DEFAULT_VERSION="v24.0";
const ORIGINS=new Set(["https://cloudsales.app","https://www.cloudsales.app","https://app.cloudsales.app","http://localhost:3000","http://localhost:5173"]);
const READ_ACTIONS=new Set(["ads.meta.platform_status","ads.meta.accounts","ads.meta.sync"]);
const OPERATOR_ACTIONS=new Set(["ads.meta.pause"]);
const ADMIN_ACTIONS=new Set(["ads.meta.account.select","ads.meta.resume","ads.meta.budget","ads.meta.create_campaign"]);
const ZERO_DECIMAL=new Set(["BIF","CLP","DJF","GNF","JPY","KMF","KRW","MGA","PYG","RWF","UGX","VND","VUV","XAF","XOF","XPF"]);
function cors(o:string|null){const v=o&&ORIGINS.has(o)?o:"https://app.cloudsales.app";return{"Access-Control-Allow-Origin":v,"Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info,x-cloudsales-worker-token","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
function json(b:unknown,s=200,o:string|null=null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"content-type":"application/json;charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}})}
const text=(v:any,n=600)=>String(v??"").trim().slice(0,n);
const now=()=>new Date().toISOString();
const numeric=(v:any)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const factor=(c:string)=>ZERO_DECIMAL.has(String(c||"USD").toUpperCase())?1:100;
const major=(v:any,c:string)=>{const n=numeric(v);return n===null?null:n/factor(c)};
const minor=(v:any,c:string)=>{const n=numeric(v);if(n===null||n<=0)throw new Error("meta_budget_must_be_positive");return Math.round(n*factor(c))};
const localStatus=(v:any)=>{const s=String(v||"").toUpperCase();if(s==="ACTIVE")return"active";if(s==="PAUSED")return"paused";if(["DELETED","ARCHIVED"].includes(s))return"archived";if(["COMPLETED","ENDED"].includes(s))return"completed";return"draft"};
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function same(a:string,b:string){if(!a||!b)return false;const[x,y]=await Promise.all([hash(a),hash(b)]);if(x.length!==y.length)return false;let r=0;for(let i=0;i<x.length;i++)r|=x.charCodeAt(i)^y.charCodeAt(i);return r===0}
function sensitivePaymentData(v:any,depth=0):boolean{if(depth>4||v==null)return false;if(Array.isArray(v))return v.some(x=>sensitivePaymentData(x,depth+1));if(typeof v!=="object")return false;for(const[k,x]of Object.entries(v)){if(/(^|_)(card|card_number|pan|cvc|cvv|expiry|expiration|security_code)(_|$)/i.test(k))return true;if(sensitivePaymentData(x,depth+1))return true}return false}
function graphError(data:any,status:number){const e=data?.error||{};return`meta_request_failed:${status}:${e.code||""}:${e.error_subcode||""}:${text(e.message||"Meta request failed",500)}`}

Deno.serve(async req=>{
  const origin=req.headers.get("origin");
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});
  if(req.method!=="POST")return json({error:"method_not_allowed"},405,origin);
  if(origin&&!ORIGINS.has(origin))return json({error:"origin_not_allowed"},403,origin);
  let body:any;try{body=await req.json()}catch{return json({error:"invalid_json"},400,origin)}
  const svc=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});
  let org="",action="",input:any={},actor:string|null=null,role="",jobId:string|null=null,internal=false,approvedBy:string|null=null;
  const workerToken=req.headers.get("x-cloudsales-worker-token")||"";
  if(workerToken){
    const{data:set}=await svc.from("internal_settings").select("secret_id").eq("setting_key","automation_worker_token").maybeSingle();if(!set?.secret_id)return json({error:"worker_not_configured"},503,origin);
    const{data:expected}=await svc.rpc("service_read_secret",{p_secret_id:set.secret_id});if(!expected||!(await same(workerToken,String(expected))))return json({error:"forbidden"},403,origin);
    jobId=String(body.job_id||"");if(!jobId)return json({error:"job_id_required"},400,origin);
    const{data:job}=await svc.from("automation_jobs").select("id,organization_id,job_type,status,requested_by,requires_approval,approved_by,input").eq("id",jobId).maybeSingle();if(!job)return json({error:"job_not_found"},404,origin);
    if(job.status!=="queued")return json({ok:true,status:job.status,idempotent:true},200,origin);
    if(job.requires_approval&&!job.approved_by)return json({error:"approval_required"},409,origin);
    org=String(job.organization_id);action=String(job.job_type);input=job.input||{};actor=job.requested_by||job.approved_by||null;approvedBy=job.approved_by||null;internal=true;
    if(!READ_ACTIONS.has(action)&&!approvedBy)return json({error:"owner_admin_approval_required"},409,origin);
    if(approvedBy){const{data:approver}=await svc.from("organization_members").select("role,status").eq("organization_id",org).eq("user_id",approvedBy).maybeSingle();if(!approver||approver.status!=="active"||!["owner","admin"].includes(String(approver.role)))return json({error:"invalid_approver"},403,origin)}
    const{data:locked}=await svc.from("automation_jobs").update({status:"running",started_at:now()}).eq("id",jobId).eq("status","queued").select("id").maybeSingle();if(!locked)return json({ok:true,status:"already_claimed",idempotent:true},200,origin);
  }else{
    const auth=req.headers.get("authorization");if(!auth)return json({error:"missing_authorization"},401,origin);
    const uc=createClient(U,A,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const{data:ud}=await uc.auth.getUser();const user=ud.user;if(!user)return json({error:"invalid_session"},401,origin);
    org=String(body.organization_id||"");action=String(body.action||"");input=body.input&&typeof body.input==="object"?body.input:{};if(!org||!action)return json({error:"missing_required_fields"},400,origin);
    const{data:m}=await svc.from("organization_members").select("role,status").eq("organization_id",org).eq("user_id",user.id).maybeSingle();role=String(m?.role||"");if(!m||m.status!=="active"||!["owner","admin","operator","viewer"].includes(role))return json({error:"forbidden"},403,origin);actor=user.id;
    if(role==="viewer"&&!READ_ACTIONS.has(action))return json({error:"insufficient_role"},403,origin);
    if(role==="operator"&&!(READ_ACTIONS.has(action)||OPERATOR_ACTIONS.has(action)))return json({error:"insufficient_role"},403,origin);
    if(ADMIN_ACTIONS.has(action)&&!["owner","admin"].includes(role))return json({error:"owner_or_admin_required"},403,origin);
  }
  if(!(READ_ACTIONS.has(action)||OPERATOR_ACTIONS.has(action)||ADMIN_ACTIONS.has(action)))return json({error:"unsupported_action"},400,origin);
  if(sensitivePaymentData(input))return json({error:"payment_card_data_not_allowed",billing_mode:"provider_managed"},400,origin);
  async function finish(status:"succeeded"|"failed",output:any,error:string|null=null){if(internal&&jobId){await svc.from("automation_jobs").update({status,output:output||null,error,finished_at:now()}).eq("id",jobId);await svc.from("cloudy_tool_runs").update({status:status==="succeeded"?"succeeded":"failed",output:output||null,error,finished_at:now()}).eq("automation_job_id",jobId).eq("organization_id",org)}await svc.from("audit_log").insert({organization_id:org,actor_user_id:actor,actor_type:internal?"worker":"user",action,entity_type:"meta_ads",entity_id:jobId||org,success:status==="succeeded",context:{provider_key:PROVIDER,internal,approved_by:approvedBy,error}})}
  async function platform(){const[{data:p},{data:c},{data:conn}]=await Promise.all([svc.from("provider_catalog").select("provider_key,display_name,availability,metadata").eq("provider_key",PROVIDER).maybeSingle(),svc.from("provider_app_credentials").select("client_id,client_secret_secret_id,redirect_uri,enabled,metadata").eq("provider_key",PROVIDER).maybeSingle(),svc.from("connections").select("id,status,external_account_name,expires_at,metadata,scopes").eq("organization_id",org).eq("provider_key",PROVIDER).eq("status","connected").order("created_at",{ascending:false}).limit(1).maybeSingle()]);const app=Boolean(c?.enabled&&c.client_id&&c.client_secret_secret_id&&c.redirect_uri);return{provider:p||null,oauth_app_configured:app,ready_for_oauth:app,connection:conn||null,missing:app?[]:["meta_ads_oauth_app"],required_permissions:["ads_read","ads_management"],billing:{mode:"provider_managed",portal_url:"https://business.facebook.com/billing_hub",card_data_stored_by_cloudsales:false}}}
  if(action==="ads.meta.platform_status"){const output=await platform();if(internal)await finish("succeeded",output);return json({ok:true,action,output},200,origin)}
  try{
    const p=await platform();if(!p.oauth_app_configured)throw new Error("meta_ads_platform_not_configured");
    const{data:conn}=await svc.from("connections").select("id,status,external_account_id,external_account_name,scopes,expires_at,metadata,last_sync_at").eq("organization_id",org).eq("provider_key",PROVIDER).eq("status","connected").order("created_at",{ascending:false}).limit(1).maybeSingle();if(!conn)throw new Error("meta_ads_connection_required");
    if(input.connection_id&&String(input.connection_id)!==String(conn.id))throw new Error("meta_ads_connection_mismatch");
    if(conn.expires_at&&new Date(conn.expires_at).getTime()<=Date.now())throw new Error("meta_ads_token_expired_reconnect_required");
    const{data:sec}=await svc.from("connection_secrets").select("access_token_secret_id").eq("connection_id",conn.id).maybeSingle();if(!sec?.access_token_secret_id)throw new Error("meta_ads_access_token_missing");
    const{data:tok}=await svc.rpc("service_read_secret",{p_secret_id:sec.access_token_secret_id});if(!tok)throw new Error("meta_ads_access_token_unavailable");const token=String(tok),version=String(conn.metadata?.graph_api_version||DEFAULT_VERSION);
    async function graph(path:string,method="GET",params:Record<string,any>={}){const url=new URL(`https://graph.facebook.com/${version}/${String(path).replace(/^\/+/,"")}`),values=new URLSearchParams();for(const[k,v]of Object.entries(params)){if(v===undefined||v===null||v==="")continue;values.set(k,typeof v==="string"?v:JSON.stringify(v))}if(method==="GET")url.search=values.toString();const r=await fetch(url.toString(),{method,headers:{Authorization:`Bearer ${token}`,Accept:"application/json",...(method==="GET"?{}:{"content-type":"application/x-www-form-urlencoded;charset=UTF-8"})},body:method==="GET"?undefined:values.toString()});const d=await r.json().catch(()=>({}));if(!r.ok||d?.error)throw new Error(graphError(d,r.status));return d}
    async function accountsState(){const d=await graph("me/adaccounts","GET",{fields:"id,name,account_status,currency,timezone_name,business,amount_spent",limit:100});const accounts=(d?.data||[]).map((x:any)=>({id:String(x.id||""),name:text(x.name,200),account_status:x.account_status??null,currency:String(x.currency||"USD"),timezone_name:text(x.timezone_name,120),business:x.business?{id:String(x.business.id||""),name:text(x.business.name,200)}:null,amount_spent:x.amount_spent??null})).filter((x:any)=>x.id.startsWith("act_"));const selected=String(conn.metadata?.selected_ad_account_id||"");return{connected:true,accounts,selected_ad_account_id:accounts.some((x:any)=>x.id===selected)?selected:null,connection_id:conn.id,expires_at:conn.expires_at,graph_api_version:version}}
    async function requireAccount(requested:any=null){const state=await accountsState();const wanted=String(requested||state.selected_ad_account_id||"");if(!wanted){if(state.accounts.length===1)return{...state,account:state.accounts[0]};throw new Error("meta_ad_account_selection_required")}const account=state.accounts.find((x:any)=>x.id===wanted);if(!account)throw new Error("meta_ad_account_not_authorized");return{...state,account}}
    async function budgetState(state:any,c:any){const currency=String(state.account.currency||"USD");if(c.daily_budget!=null||c.lifetime_budget!=null)return{scope:"campaign",object_id:String(c.id),daily_budget:major(c.daily_budget,currency),lifetime_budget:major(c.lifetime_budget,currency),adsets:[]};const d=await graph(`${c.id}/adsets`,"GET",{fields:"id,name,status,effective_status,daily_budget,lifetime_budget",limit:100});const adsets=(d?.data||[]).map((x:any)=>({id:String(x.id),name:text(x.name,200),status:x.status,effective_status:x.effective_status,daily_budget:major(x.daily_budget,currency),lifetime_budget:major(x.lifetime_budget,currency)}));const budgeted=adsets.filter((x:any)=>x.daily_budget!=null||x.lifetime_budget!=null);if(budgeted.length===1)return{scope:"adset",object_id:budgeted[0].id,daily_budget:budgeted[0].daily_budget,lifetime_budget:budgeted[0].lifetime_budget,adsets};if(budgeted.length>1)return{scope:"multiple_adsets",object_id:null,daily_budget:null,lifetime_budget:null,adsets};return{scope:"none",object_id:null,daily_budget:null,lifetime_budget:null,adsets}}
    async function syncRow(state:any,c:any,budget:any,insight:any=null){const currency=String(state.account.currency||"USD"),actions=Array.isArray(insight?.actions)?insight.actions:[],leads=actions.reduce((sum:number,a:any)=>/lead/i.test(String(a.action_type||""))?sum+(Number(a.value)||0):sum,0);const{data:existing}=await svc.from("marketing_campaigns").select("id,metadata").eq("organization_id",org).eq("provider_key",CAMPAIGN_PROVIDER).eq("external_campaign_id",String(c.id)).maybeSingle();const row:any={organization_id:org,provider_key:CAMPAIGN_PROVIDER,external_campaign_id:String(c.id),name:text(c.name,180)||`Meta ${c.id}`,objective:text(c.objective,180),status:localStatus(c.status||c.effective_status),daily_budget:budget.daily_budget,lifetime_budget:budget.lifetime_budget,currency,spend:numeric(insight?.spend)??0,leads:Math.max(0,Math.round(leads)),last_sync_at:now(),updated_at:now(),metadata:{...(existing?.metadata||{}),meta_effective_status:c.effective_status||null,meta_buying_type:c.buying_type||null,meta_budget_scope:budget.scope,meta_budget_object_id:budget.object_id,meta_adsets:budget.adsets||[],meta_account_id:state.account.id,meta_account_name:state.account.name,meta_ads_connection_id:conn.id,provider_confirmed_at:now()}};if(existing?.id){const{data,error}=await svc.from("marketing_campaigns").update(row).eq("id",existing.id).select("*").single();if(error)throw new Error("meta_campaign_local_sync_failed");return data}row.qualified_leads=0;row.revenue=0;row.created_by=actor;const{data,error}=await svc.from("marketing_campaigns").insert(row).select("*").single();if(error)throw new Error("meta_campaign_local_insert_failed");return data}
    async function localCampaign(id:string){const{data}=await svc.from("marketing_campaigns").select("*").eq("id",id).eq("organization_id",org).eq("provider_key",CAMPAIGN_PROVIDER).maybeSingle();if(!data||!data.external_campaign_id)throw new Error("meta_campaign_not_found");return data}
    let output:any;
    if(action==="ads.meta.accounts")output=await accountsState();
    else if(action==="ads.meta.account.select"){const state=await requireAccount(input.account_id);const metadata={...(conn.metadata||{}),selected_ad_account_id:state.account.id,selected_ad_account_name:state.account.name,selected_ad_account_currency:state.account.currency,selected_ad_account_timezone:state.account.timezone_name,ad_account_selected_at:now()};await svc.from("connections").update({metadata,last_sync_at:now()}).eq("id",conn.id);output={selected:state.account}}
    else if(action==="ads.meta.sync"){const state=await requireAccount(input.account_id);const cd=await graph(`${state.account.id}/campaigns`,"GET",{fields:"id,name,status,effective_status,objective,buying_type,daily_budget,lifetime_budget",limit:100});const rows=[];for(const c of cd?.data||[]){const budget=await budgetState(state,c);let insight:any=null;try{const ins=await graph(`${c.id}/insights`,"GET",{fields:"spend,actions",date_preset:"last_30d",limit:1});insight=ins?.data?.[0]||null}catch{}rows.push(await syncRow(state,c,budget,insight))}await svc.from("connections").update({last_sync_at:now(),metadata:{...(conn.metadata||{}),selected_ad_account_id:state.account.id,selected_ad_account_name:state.account.name,selected_ad_account_currency:state.account.currency,selected_ad_account_timezone:state.account.timezone_name,campaigns_last_sync_at:now()}}).eq("id",conn.id);output={account:state.account,campaigns:rows,count:rows.length,synced_at:now()}}
    else if(action==="ads.meta.pause"||action==="ads.meta.resume"){const local=await localCampaign(String(input.id||input.campaign_id||"")),state=await requireAccount(local.metadata?.meta_account_id||input.account_id),status=action==="ads.meta.pause"?"PAUSED":"ACTIVE";await graph(String(local.external_campaign_id),"POST",{status});const confirmed=await graph(String(local.external_campaign_id),"GET",{fields:"id,name,status,effective_status,objective,buying_type,daily_budget,lifetime_budget"});if(String(confirmed.status||"").toUpperCase()!==status)throw new Error("meta_campaign_status_confirmation_failed");const budget=await budgetState(state,confirmed);output={campaign:await syncRow(state,confirmed,budget,null),provider_status:status,confirmed:true,confirmed_at:now()}}
    else if(action==="ads.meta.budget"){const local=await localCampaign(String(input.id||input.campaign_id||"")),state=await requireAccount(local.metadata?.meta_account_id||input.account_id),currency=String(state.account.currency||local.currency||"USD"),amount=minor(input.daily_budget,currency);let objectId=String(input.budget_object_id||local.metadata?.meta_budget_object_id||"");const scope=String(local.metadata?.meta_budget_scope||"");if(scope==="multiple_adsets"&&!input.budget_object_id)throw new Error("meta_budget_multiple_adsets_requires_scope");if(!objectId&&scope==="campaign")objectId=String(local.external_campaign_id);if(!objectId)throw new Error("meta_budget_object_missing");await graph(objectId,"POST",{daily_budget:String(amount)});const confirmed=await graph(objectId,"GET",{fields:"id,daily_budget,lifetime_budget"});if(Number(confirmed.daily_budget||0)!==amount)throw new Error("meta_daily_budget_confirmation_failed");await svc.from("marketing_campaigns").update({daily_budget:major(confirmed.daily_budget,currency),updated_at:now(),metadata:{...(local.metadata||{}),meta_budget_object_id:objectId,provider_confirmed_at:now()}}).eq("id",local.id);output={campaign_id:local.id,provider:{object_id:objectId,daily_budget:major(confirmed.daily_budget,currency),currency},confirmed:true,confirmed_at:now()}}
    else if(action==="ads.meta.create_campaign"){const state=await requireAccount(input.account_id),name=text(input.name,180);if(!name)throw new Error("meta_campaign_name_required");const objective=text(input.objective||"OUTCOME_LEADS",80),special=Array.isArray(input.special_ad_categories)?input.special_ad_categories.map((x:any)=>text(x,50)).filter(Boolean):[];const created=await graph(`${state.account.id}/campaigns`,"POST",{name,objective,status:"PAUSED",special_ad_categories:special});const id=String(created?.id||"");if(!id)throw new Error("meta_campaign_create_failed");const confirmed=await graph(id,"GET",{fields:"id,name,status,effective_status,objective,buying_type,daily_budget,lifetime_budget"});if(String(confirmed.status||"").toUpperCase()!=="PAUSED")throw new Error("meta_campaign_pause_confirmation_failed");const budget=await budgetState(state,confirmed);output={campaign:await syncRow(state,confirmed,budget,null),provider_campaign:{id,name:confirmed.name||name,status:"PAUSED"},confirmed:true}}
    await finish("succeeded",output,null);return json({ok:true,action,output},200,origin);
  }catch(e){const error=text((e as Error).message,800);await finish("failed",null,error);return json({error},error.includes("connection_required")||error.includes("selection_required")?409:502,origin)}
});
