# trigger 2026-09-02
from pathlib import Path
p=Path('supabase/functions/auth-session/index.ts')
s=p.read_text()
s=s.replace('const VERSION="2026.08.31.1"','const VERSION="2026.09.02.2"',1)
marker='\nDeno.serve(async req=>{'
if marker not in s: raise SystemExit('serve marker missing')
fn=r'''
async function sendSignupAccess(svc:any,email:string,actionLink:string,fullName:string){
 const key=await settingSecret(svc,"resend_api_key_cloudco");
 if(!key)return{ok:false,status:503,error:"email_provider_not_configured"};
 const who=fullName?`Hola ${fullName},`:'Hola,';
 const html=`<!doctype html><html><body style="margin:0;background:#08080f;color:#f8f7fb;font-family:Arial,sans-serif;padding:24px"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="100%" style="max-width:560px;background:#111119;border:1px solid #30303e;border-radius:24px"><tr><td style="padding:30px"><img src="https://app.cloudsales.app/assets/cloudsales-logo-official-v2.png" alt="CloudSales" width="220" style="display:block;max-width:220px;height:auto;margin:0 0 24px"><h1 style="font-size:30px;line-height:1.08;margin:0 0 12px;color:#fff">Bienvenido a CloudSales</h1><p style="color:#c9c6d2;line-height:1.6;margin:0 0 10px">${who}</p><p style="color:#aaa7b5;line-height:1.6">Tu acceso está listo. Confirma tu correo y entra a CloudSales con el botón de abajo.</p><p style="margin:28px 0"><a href="${actionLink}" style="display:inline-block;background:linear-gradient(90deg,#ff2b9b,#bf32ff);color:#fff;text-decoration:none;font-weight:900;padding:15px 24px;border-radius:999px">Acceder a CloudSales</a></p><p style="font-size:12px;color:#777483;line-height:1.5">Este enlace es personal. Si tú no solicitaste esta cuenta, puedes ignorar este correo.</p><p style="font-size:11px;color:#5f5c69;margin-top:28px">CloudSales · Your business, operated by AI.</p></td></tr></table></td></tr></table></body></html>`;
 const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({from:"CloudSales <info@cloudsales.app>",to:[email],reply_to:"info@cloudsales.app",subject:"Bienvenido a CloudSales — confirma tu acceso",html})});
 const t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={raw:t}};
 return{ok:r.ok,status:r.status,data:d,error:r.ok?null:"signup_email_failed"};
}
'''
s=s.replace(marker,'\n'+fn+marker,1)
old='''if(action==="sign_up"){const password=String(body.password||""),fullName=safe(body.full_name,160);const{data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:APP_URL,data:fullName?{full_name:fullName}:{}}});if(error){await svc.from("email_send_authorizations").update({context:{...ctx,provider_call_completed:false,provider_error:"signup_failed"}}).eq("id",authorization.id);const m=String(error.message||"").toLowerCase();if(m.includes("rate")||error.status===429)return json({error:"signup_temporarily_limited"},429,origin);return json({error:"signup_unavailable"},400,origin)}await svc.from("email_send_authorizations").update({user_id:data.user?.id||null,consumed_at:new Date().toISOString(),context:{...ctx,provider_call_completed:true}}).eq("id",authorization.id);if(data.session)return json(sessionPayload(data),200,origin);const ids=Array.isArray(data.user?.identities)?data.user.identities:null;return json({confirmation_required:true,message_code:ids&&ids.length===0?"account_exists_or_confirmation_pending":"confirmation_sent",policy:POLICY},200,origin)}
 const{error}=await client.auth.resend({type:"signup",email,options:{emailRedirectTo:APP_URL}});if(error){await svc.from("email_send_authorizations").update({context:{...ctx,provider_call_completed:false,provider_error:"resend_failed"}}).eq("id",authorization.id);const m=String(error.message||"").toLowerCase();if(m.includes("rate")||error.status===429)return json({error:"confirmation_wait"},429,origin);return json({error:"resend_unavailable"},400,origin)}await svc.from("email_send_authorizations").update({consumed_at:new Date().toISOString(),context:{...ctx,provider_call_completed:true}}).eq("id",authorization.id);return json({ok:true,confirmation_required:true,message_code:"confirmation_resent",policy:POLICY},200,origin)'''
new='''if(action==="sign_up"){const password=String(body.password||""),fullName=safe(body.full_name,160);const{data,error}=await svc.auth.admin.generateLink({type:"signup",email,password,options:{redirectTo:APP_URL,data:fullName?{full_name:fullName}:{}}});if(error||!data?.properties?.action_link){await svc.from("email_send_authorizations").update({context:{...ctx,provider_call_completed:false,provider_error:"signup_link_failed"}}).eq("id",authorization.id);const m=String(error?.message||"").toLowerCase();if(m.includes("rate")||error?.status===429)return json({error:"signup_temporarily_limited"},429,origin);if(m.includes("already")||m.includes("registered")||m.includes("exists"))return json({error:"account_exists_use_signin"},409,origin);return json({error:"signup_unavailable"},400,origin)}const sent=await sendSignupAccess(svc,email,String(data.properties.action_link),fullName);if(!sent.ok){await svc.from("email_send_authorizations").update({user_id:data.user?.id||null,context:{...ctx,provider_call_completed:false,provider_error:sent.error,provider_status:sent.status}}).eq("id",authorization.id);return json({error:"signup_unavailable"},503,origin)}await svc.from("email_send_authorizations").update({user_id:data.user?.id||null,consumed_at:new Date().toISOString(),context:{...ctx,provider_call_completed:true,provider_status:sent.status,delivery:"resend",from:"info@cloudsales.app",branded:true}}).eq("id",authorization.id);return json({confirmation_required:true,message_code:"confirmation_sent",policy:POLICY,branded_email:true},200,origin)}
 const{data,error}=await svc.auth.admin.generateLink({type:"magiclink",email,options:{redirectTo:APP_URL}});if(error||!data?.properties?.action_link){await svc.from("email_send_authorizations").update({context:{...ctx,provider_call_completed:false,provider_error:"resend_link_failed"}}).eq("id",authorization.id);const m=String(error?.message||"").toLowerCase();if(m.includes("rate")||error?.status===429)return json({error:"confirmation_wait"},429,origin);return json({error:"resend_unavailable"},400,origin)}const sent=await sendSignupAccess(svc,email,String(data.properties.action_link),"");if(!sent.ok){await svc.from("email_send_authorizations").update({context:{...ctx,provider_call_completed:false,provider_error:sent.error,provider_status:sent.status}}).eq("id",authorization.id);return json({error:"resend_unavailable"},503,origin)}await svc.from("email_send_authorizations").update({user_id:data.user?.id||null,consumed_at:new Date().toISOString(),context:{...ctx,provider_call_completed:true,provider_status:sent.status,delivery:"resend",from:"info@cloudsales.app",branded:true}}).eq("id",authorization.id);return json({ok:true,confirmation_required:true,message_code:"confirmation_resent",policy:POLICY,branded_email:true},200,origin)'''
if old not in s: raise SystemExit('signup block missing')
s=s.replace(old,new,1)
for m in ['sendSignupAccess','Acceder a CloudSales','generateLink({type:"signup"','generateLink({type:"magiclink"','2026.09.02.2']:
    assert m in s,m
p.write_text(s)
print('branded signup email patch applied')
