import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import vm from 'node:vm';

const ROOT=process.cwd();
const locale=process.env.LOCALE||process.argv[2]||'';
const allowed=['es','en','fr','it','pt-BR','de','ar-AE','ru','he','zh-CN','ja'];
if(!allowed.includes(locale))throw new Error('invalid_locale_'+locale);
const labels={es:'Spanish (neutral Latin American Spanish)',en:'English (international business English)',fr:'French',it:'Italian','pt-BR':'Brazilian Portuguese',de:'German','ar-AE':'Modern Standard Arabic suitable for the UAE',ru:'Russian',he:'Hebrew','zh-CN':'Simplified Chinese',ja:'Japanese'};
const ENDPOINT='https://fkahaqprzgcimgyathqx.supabase.co/functions/v1/nvidia-nim';
const VERSION='2026.09.03.1';

const commercialHtml=['web/commercial.html','web/cloudco.html','web/academy.html','web/services.html','web/affiliate.html','web/terms.html','web/privacy.html','web/commercial/domains-v2.html','web/usage-pricing.html'];
const commercialJs=['web/commercial-sales-story-v1.js','web/commercial-crm-bmp-v3.js','web/commercial-brand-runtime-v2.js','web/cloudsales-brand-language-guard-v1.js','web/commercial/conversion-v1.js','web/webchat.js'];
const pwaHtml=['web/pwa.html'];
const pwaJs=['web/auth-runtime-v2.js','web/app-runtime-v14.js','web/meta-runtime-v1.js','web/cloudy-runtime-v3.js','web/works-runtime-v1.js','web/ad-spend-runtime-v1.js','web/ai-chat-runtime-v2.js','web/ai-chat-backfill-v1.js','web/ai-chat-channels-v1.js','web/calendar-runtime-v1.js','web/ai-chat-calendar-bridge-v1.js','web/contact-profile-runtime-v1.js','web/dashboard-runtime-v3.js','web/sales-analytics-runtime-v1.js','web/native-shell-runtime-v1.js','web/pwa-polish-runtime-v1.js','web/workspace-polish-runtime-v1.js','web/cloudy-executive-runtime-v1.js','web/install.js'];

function read(file){return fs.readFileSync(path.join(ROOT,file),'utf8')}
function decode(s){return s.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g,' ').trim()}
function normalized(s){return String(s||'').replace(/\s+/g,' ').trim()}
function candidate(s){s=normalized(s);if(s.length<2||s.length>5000)return false;if(!/[A-Za-zÁÉÍÓÚÜÑáéíóúüñÀ-žЀ-ӿ֐-׿؀-ۿ぀-ヿ㐀-鿿]/.test(s))return false;if(/^(?:https?:|mailto:|tel:|data:|blob:|application\/|text\/|image\/|audio\/|video\/|Bearer\s|SELECT\s|INSERT\s|UPDATE\s|DELETE\s)/i.test(s))return false;if(/^[/#.][A-Za-z0-9_./:#?=&-]+$/.test(s))return false;if(/^[A-Za-z0-9_.-]+\.(?:js|mjs|css|json|html|png|jpg|jpeg|webp|svg|pdf|woff2?)$/i.test(s))return false;if(/[{}]\s*=>|\b(?:function|const|let|var|return|document\.|window\.|querySelector|addEventListener|classList|localStorage|sessionStorage)\b/.test(s))return false;if((s.match(/[;{}]/g)||[]).length>4)return false;return true}
function add(set,s){s=decode(String(s||''));if(candidate(s))set.add(s)}
function htmlStrings(file,set){let h=read(file).replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<template\b[\s\S]*?<\/template>/gi,' ');for(const m of h.matchAll(/>([^<>]+)</g))add(set,m[1]);for(const m of h.matchAll(/\b(?:placeholder|aria-label|title|alt)=["']([^"']+)["']/gi))add(set,m[1]);for(const m of h.matchAll(/<meta\b[^>]*(?:name|property)=["'](?:description|og:title|og:description|twitter:title|twitter:description)["'][^>]*content=["']([^"']+)["'][^>]*>/gi))add(set,m[1]);for(const m of h.matchAll(/<meta\b[^>]*content=["']([^"']+)["'][^>]*(?:name|property)=["'](?:description|og:title|og:description|twitter:title|twitter:description)["'][^>]*>/gi))add(set,m[1])}
function jsStrings(file,set){if(!fs.existsSync(path.join(ROOT,file)))return;const s=read(file);let i=0;while(i<s.length){const q=s[i];if(q!=='"'&&q!=="'"&&q!=='`'){i++;continue}let j=i+1,out='',esc=false,badTemplate=false;for(;j<s.length;j++){const c=s[j];if(esc){out+='\\'+c;esc=false;continue}if(c==='\\'){esc=true;continue}if(q==='`'&&c==='$'&&s[j+1]==='{'){badTemplate=true;break}if(c===q)break;out+=c}if(!badTemplate&&j<s.length){try{let val;if(q==='"')val=JSON.parse('"'+out.replace(/"/g,'\\"')+'"');else if(q==="'")val=Function('return '+q+out.replace(/'/g,"\\'")+q)();else val=out;add(set,val)}catch{add(set,out)}}i=Math.max(i+1,j+1)}}
function literalAfter(src,marker){const m=src.indexOf(marker);if(m<0)return null;const start=src.indexOf('{',m+marker.length);if(start<0)return null;let d=0,q=null,e=false;for(let i=start;i<src.length;i++){const ch=src[i];if(q){if(e){e=false;continue}if(ch==='\\'){e=true;continue}if(ch===q)q=null;continue}if(ch==='"'||ch==="'"||ch==='`'){q=ch;continue}if(ch==='{')d++;else if(ch==='}'&&--d===0)return src.slice(start,i+1)}return null}
function addObjectKeys(file,marker,set,subkey=null){const src=read(file),lit=literalAfter(src,marker);if(!lit)return;try{const obj=vm.runInNewContext('('+lit+')');const x=subkey?obj?.[subkey]:obj;if(x&&typeof x==='object')for(const k of Object.keys(x))add(set,k)}catch(e){console.warn('object_parse_failed',file,marker,String(e.message||e))}}
function sources(){const commercial=new Set(),pwa=new Set();for(const f of commercialHtml)htmlStrings(f,commercial);for(const f of commercialJs)jsStrings(f,commercial);addObjectKeys('web/cloudsales-i18n-v1.js','const EN_FULL=',commercial);addObjectKeys('web/cloudsales-i18n-v1.js','const T=',commercial,'en');addObjectKeys('web/cloudsales-i18n-v1.js','const CS_FINAL_TRANSLATIONS=',commercial,'en');for(const f of pwaHtml)htmlStrings(f,pwa);for(const f of pwaJs)jsStrings(f,pwa);addObjectKeys('web/pwa-i18n-runtime-v1.js','const EN=',pwa);for(const x of ['Escribe un correo válido.','Preparando checkout…','No pudimos abrir el checkout: ','Idioma de la aplicación','Se aplicará en este dispositivo y se comparte con el sitio comercial.'])add(commercial,x);return{commercial:[...commercial].sort(),pwa:[...pwa].sort()}}
function neutral(s){return /^(?:CloudSales|Cloudy|AgentCloud|CloudCo|LISTIA|CRM|PWA|API|SEO|OAuth|Stripe|WhatsApp|Meta|Google|TikTok|LinkedIn|YouTube|HighLevel|Salesforce|HubSpot|Zoho CRM|Microsoft Dynamics 365|Pipedrive|monday CRM|Freshsales|Close|Copper|Twenty|PayPal|Binance|Basic|Pro|Premium|USD|WAF|AI CHAT|Conversion API|Web Events|CRM Events|Data Signals|Conversion Signals)$/i.test(s)||/^[A-Z0-9 .+/_-]{1,16}$/.test(s)}
function scoreWords(s,words){const low=' '+s.toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ')+' ';let n=0;for(const w of words)if(low.includes(' '+w+' '))n++;return n}
function likelySpanish(s){return /[¿¡áéíóúñü]/i.test(s)||scoreWords(s,['el','la','los','las','de','del','para','que','con','sin','una','un','tu','tus','por','como','negocio','ventas','correo','dominio','sitio','cuenta','privacidad','términos'])>=2}
function likelyEnglish(s){return scoreWords(s,['the','and','your','you','with','for','this','that','from','into','of','is','are','can','will','terms','privacy','account','business','domain','website','sales'])>=2}
function identityForTarget(s){if(neutral(s))return true;if(locale==='es'&&likelySpanish(s))return true;if(locale==='en'&&likelyEnglish(s))return true;return false}
function idFor(s){return crypto.createHash('sha256').update(s).digest('hex').slice(0,20)}
function numbers(s){return [...s.matchAll(/(?:[$€£¥]\s*)?\d+(?:[.,]\d+)?\s*%?/g)].map(m=>m[0].replace(/\s+/g,'')).sort()}
function validatePreservation(source,target){const a=numbers(source),b=numbers(target);if(JSON.stringify(a)!==JSON.stringify(b))throw new Error('numeric_preservation_failed: '+source.slice(0,80)+' => '+target.slice(0,80));for(const brand of ['CloudSales','Cloudy','AgentCloud','CloudCo','LISTIA','Stripe','PayPal','Binance'])if(source.includes(brand)&&!target.includes(brand))throw new Error('brand_preservation_failed_'+brand)}
let oidc={token:'',at:0};async function oidcToken(){if(oidc.token&&Date.now()-oidc.at<240000)return oidc.token;const base=process.env.ACTIONS_ID_TOKEN_REQUEST_URL,req=process.env.ACTIONS_ID_TOKEN_REQUEST_TOKEN;if(!base||!req)throw new Error('github_oidc_unavailable');const u=new URL(base);u.searchParams.set('audience','cloudsales-i18n-build');const r=await fetch(u,{headers:{Authorization:'Bearer '+req}});if(!r.ok)throw new Error('oidc_'+r.status);const j=await r.json();oidc={token:j.value,at:Date.now()};return oidc.token}
function parseJson(s){s=String(s||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)s=s.slice(a,b+1);return JSON.parse(s)}
async function translateBatch(items,surface,depth=0){if(!items.length)return{};const token=await oidcToken();const system=`You are the senior localization engine for CloudSales, a professional B2B SaaS product. Translate each user-facing source string into ${labels[locale]}. Source strings may be Spanish, English, or occasionally mixed. Return ONLY valid JSON exactly as {"translations":{"ID":"translation"}}. Preserve every ID exactly. Preserve CloudSales, Cloudy, AgentCloud, CloudCo, LISTIA, Stripe, CRM, PWA, API, SEO, OAuth, Meta, Google, TikTok, LinkedIn, WhatsApp, Salesforce, HubSpot, HighLevel, Pipedrive, Zoho, Microsoft Dynamics 365, monday CRM, Freshsales, Close, Copper, Twenty, PayPal, Binance, USD, plan names Basic/Pro/Premium, URLs, emails, variables, placeholders, numbers, prices, currencies, percentages, symbols and HTML tags. Do not change commercial claims, prices, legal meaning, obligations, disclaimers or scope. Use natural professional terminology for ${labels[locale]}; do not summarize or omit. For legal/privacy copy, be precise and conservative. If a source string is already in the target language or is a brand/technical label, keep it unchanged. Surface: ${surface}.`;
  const user=JSON.stringify({target_locale:locale,items:items.map(x=>({id:x.id,text:x.text}))});
  const body={model:'nvidia/nemotron-3.5-lightning-30b-a3b',messages:[{role:'system',content:system},{role:'user',content:user}],max_tokens:7000,temperature:0.05,response_format:{type:'json_object'},chat_template_kwargs:{enable_thinking:false}};
  for(let attempt=1;attempt<=3;attempt++)try{const r=await fetch(ENDPOINT,{method:'POST',headers:{Authorization:'Bearer '+token,'x-cloudsales-build':'i18n','content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error('gateway_'+r.status+'_'+JSON.stringify(j).slice(0,180));const obj=parseJson(j?.choices?.[0]?.message?.content||'');const tr=obj?.translations;if(!tr||typeof tr!=='object')throw new Error('invalid_json_shape');for(const x of items){if(typeof tr[x.id]!=='string'||!tr[x.id].trim())throw new Error('missing_'+x.id);validatePreservation(x.text,tr[x.id])}return tr}catch(e){if(attempt===3){if(items.length>1&&depth<5){const mid=Math.ceil(items.length/2);return Object.assign({},await translateBatch(items.slice(0,mid),surface,depth+1),await translateBatch(items.slice(mid),surface,depth+1))}throw e}await new Promise(r=>setTimeout(r,700*attempt))}return{}}
function batches(items){const out=[];let cur=[],chars=0;for(const x of items){const n=x.text.length;if(cur.length&&(cur.length>=28||chars+n>11500)){out.push(cur);cur=[];chars=0}cur.push(x);chars+=n}if(cur.length)out.push(cur);return out}
async function translateSurface(list,surface){const result={},pending=[];for(const text of list){if(identityForTarget(text)){result[text]=text;continue}pending.push({id:idFor(text),text})}const bs=batches(pending);console.log(locale,surface,'sources',list.length,'identity',list.length-pending.length,'batches',bs.length);let done=0;for(const batch of bs){const tr=await translateBatch(batch,surface);for(const x of batch)result[x.text]=tr[x.id];done+=batch.length;console.log(locale,surface,'translated',done,'/',pending.length)}for(const s of list)if(typeof result[s]!=='string'||!result[s].trim())throw new Error('catalog_missing_'+surface+'_'+s.slice(0,60));return Object.fromEntries(Object.entries(result).sort(([a],[b])=>a.localeCompare(b)))}

const src=sources();const commercial=await translateSurface(src.commercial,'commercial website, legal pages, domains and checkout');const pwa=await translateSurface(src.pwa,'CloudSales PWA application');const out={version:VERSION,locale,source_sha:process.env.GITHUB_SHA||'',generated_at:new Date().toISOString(),counts:{commercial:Object.keys(commercial).length,pwa:Object.keys(pwa).length},commercial,pwa};fs.mkdirSync('build/i18n',{recursive:true});fs.writeFileSync(`build/i18n/${locale}.json`,JSON.stringify(out,null,2)+'\n');console.log('WROTE',locale,out.counts);
