from pathlib import Path

p=Path('web/cloudsales-i18n-v1.js')
s=p.read_text(encoding='utf-8')
marker='/* CS_DOMAINS_SEARCH_RUNTIME_V3 */'
pos=s.find(marker)
if pos<0:
    raise SystemExit('domains runtime marker not found')

runtime=r'''/* CS_DOMAINS_SEARCH_RUNTIME_V4_11_LOCALES */
(()=>{
'use strict';
const originalInput=document.getElementById('domain'),originalBtn=document.getElementById('search');
if(!originalInput||!originalBtn)return;
/* Clone the two interactive controls once so historical inline listeners cannot
   issue duplicate registrar requests. The canonical runtime below is the sole
   owner of lookup interactions. */
const input=originalInput.cloneNode(true),btn=originalBtn.cloneNode(true);
originalInput.replaceWith(input);originalBtn.replaceWith(btn);
const $=id=>document.getElementById(id),result=$('result'),purchase=$('purchase');
document.querySelectorAll('#domainSuggestions,#domainSuggestions20260902').forEach(x=>x.remove());

const DS={
'es':{choose:'ELIGE UNA EXTENSIÓN',valid:'ESCRIBE UN DOMINIO VÁLIDO',searching:'BUSCANDO…',checking:'VERIFICANDO…',not:'NO DISPONIBLE',possible:'POSIBLEMENTE DISPONIBLE',confirm:'POR CONFIRMAR',available:'✓ DISPONIBLE',inconclusive:'RESULTADO NO CONCLUYENTE',temporary:'BÚSQUEDA TEMPORALMENTE NO DISPONIBLE',select:'Selecciona una sugerencia o escribe un dominio completo como minegocio.com.',example:'Ejemplo: minegocio.com',checkingMsg:'Verificando disponibilidad del dominio…',registered:'Este dominio ya está registrado.',appears:'Parece disponible. Confirmaremos disponibilidad y precio antes de cualquier cobro.',registrar:'Disponibilidad confirmada por el registrador.',retry:'Intenta de nuevo en unos segundos.',failed:'No pudimos completar la búsqueda. Intenta nuevamente.',button:'BUSCAR',year:'/año'},
'en':{choose:'CHOOSE A DOMAIN EXTENSION',valid:'ENTER A VALID DOMAIN',searching:'SEARCHING…',checking:'CHECKING…',not:'NOT AVAILABLE',possible:'POSSIBLY AVAILABLE',confirm:'TO BE CONFIRMED',available:'✓ AVAILABLE',inconclusive:'INCONCLUSIVE RESULT',temporary:'SEARCH TEMPORARILY UNAVAILABLE',select:'Select a suggestion or type a complete domain such as mybusiness.com.',example:'Example: mybusiness.com',checkingMsg:'Checking domain availability…',registered:'This domain is already registered.',appears:'It appears available. We will confirm availability and price before any charge.',registrar:'Availability confirmed by the registrar.',retry:'Try again in a few seconds.',failed:'We could not complete the lookup. Please try again.',button:'SEARCH',year:'/year'},
'fr':{choose:'CHOISISSEZ UNE EXTENSION',valid:'SAISISSEZ UN DOMAINE VALIDE',searching:'RECHERCHE…',checking:'VÉRIFICATION…',not:'INDISPONIBLE',possible:'PEUT-ÊTRE DISPONIBLE',confirm:'À CONFIRMER',available:'✓ DISPONIBLE',inconclusive:'RÉSULTAT NON CONCLUANT',temporary:'RECHERCHE TEMPORAIREMENT INDISPONIBLE',select:'Choisissez une suggestion ou saisissez un domaine complet, par exemple monentreprise.com.',example:'Exemple : monentreprise.com',checkingMsg:'Vérification de la disponibilité du domaine…',registered:'Ce domaine est déjà enregistré.',appears:'Il semble disponible. Nous confirmerons la disponibilité et le prix avant tout débit.',registrar:'Disponibilité confirmée par le registraire.',retry:'Réessayez dans quelques secondes.',failed:'Nous n’avons pas pu terminer la recherche. Réessayez.',button:'RECHERCHER',year:'/an'},
'it':{choose:'SCEGLI UN’ESTENSIONE',valid:'INSERISCI UN DOMINIO VALIDO',searching:'RICERCA…',checking:'VERIFICA…',not:'NON DISPONIBILE',possible:'POSSIBILMENTE DISPONIBILE',confirm:'DA CONFERMARE',available:'✓ DISPONIBILE',inconclusive:'RISULTATO NON CONCLUSIVO',temporary:'RICERCA TEMPORANEAMENTE NON DISPONIBILE',select:'Scegli un suggerimento o inserisci un dominio completo, ad esempio miaazienda.com.',example:'Esempio: miaazienda.com',checkingMsg:'Verifica della disponibilità del dominio…',registered:'Questo dominio è già registrato.',appears:'Sembra disponibile. Confermeremo disponibilità e prezzo prima di qualsiasi addebito.',registrar:'Disponibilità confermata dal registrar.',retry:'Riprova tra qualche secondo.',failed:'Non siamo riusciti a completare la ricerca. Riprova.',button:'CERCA',year:'/anno'},
'pt-BR':{choose:'ESCOLHA UMA EXTENSÃO',valid:'DIGITE UM DOMÍNIO VÁLIDO',searching:'BUSCANDO…',checking:'VERIFICANDO…',not:'INDISPONÍVEL',possible:'POSSIVELMENTE DISPONÍVEL',confirm:'A CONFIRMAR',available:'✓ DISPONÍVEL',inconclusive:'RESULTADO INCONCLUSIVO',temporary:'BUSCA TEMPORARIAMENTE INDISPONÍVEL',select:'Escolha uma sugestão ou digite um domínio completo, como minhaempresa.com.',example:'Exemplo: minhaempresa.com',checkingMsg:'Verificando a disponibilidade do domínio…',registered:'Este domínio já está registrado.',appears:'Parece disponível. Confirmaremos disponibilidade e preço antes de qualquer cobrança.',registrar:'Disponibilidade confirmada pelo registrador.',retry:'Tente novamente em alguns segundos.',failed:'Não foi possível concluir a busca. Tente novamente.',button:'BUSCAR',year:'/ano'},
'de':{choose:'DOMAINENDUNG AUSWÄHLEN',valid:'GÜLTIGE DOMAIN EINGEBEN',searching:'SUCHE…',checking:'PRÜFUNG…',not:'NICHT VERFÜGBAR',possible:'MÖGLICHERWEISE VERFÜGBAR',confirm:'NOCH ZU BESTÄTIGEN',available:'✓ VERFÜGBAR',inconclusive:'KEIN EINDEUTIGES ERGEBNIS',temporary:'SUCHE VORÜBERGEHEND NICHT VERFÜGBAR',select:'Wählen Sie einen Vorschlag oder geben Sie eine vollständige Domain ein, z. B. meinunternehmen.com.',example:'Beispiel: meinunternehmen.com',checkingMsg:'Domain-Verfügbarkeit wird geprüft…',registered:'Diese Domain ist bereits registriert.',appears:'Sie scheint verfügbar zu sein. Verfügbarkeit und Preis werden vor jeder Abbuchung bestätigt.',registrar:'Verfügbarkeit vom Registrar bestätigt.',retry:'Versuchen Sie es in einigen Sekunden erneut.',failed:'Die Suche konnte nicht abgeschlossen werden. Bitte erneut versuchen.',button:'SUCHEN',year:'/Jahr'},
'ar-AE':{choose:'اختر امتداد النطاق',valid:'أدخل نطاقاً صالحاً',searching:'جارٍ البحث…',checking:'جارٍ التحقق…',not:'غير متاح',possible:'قد يكون متاحاً',confirm:'بانتظار التأكيد',available:'✓ متاح',inconclusive:'النتيجة غير حاسمة',temporary:'البحث غير متاح مؤقتاً',select:'اختر اقتراحاً أو اكتب نطاقاً كاملاً مثل mybusiness.com.',example:'مثال: mybusiness.com',checkingMsg:'جارٍ التحقق من توفر النطاق…',registered:'هذا النطاق مسجل بالفعل.',appears:'يبدو متاحاً. سنؤكد التوفر والسعر قبل أي عملية تحصيل.',registrar:'تم تأكيد التوفر من جهة تسجيل النطاق.',retry:'حاول مرة أخرى بعد بضع ثوانٍ.',failed:'تعذر إكمال البحث. حاول مرة أخرى.',button:'بحث',year:'/سنة'},
'ru':{choose:'ВЫБЕРИТЕ ДОМЕННУЮ ЗОНУ',valid:'ВВЕДИТЕ КОРРЕКТНЫЙ ДОМЕН',searching:'ПОИСК…',checking:'ПРОВЕРКА…',not:'НЕДОСТУПЕН',possible:'ВОЗМОЖНО ДОСТУПЕН',confirm:'ТРЕБУЕТ ПОДТВЕРЖДЕНИЯ',available:'✓ ДОСТУПЕН',inconclusive:'НЕОДНОЗНАЧНЫЙ РЕЗУЛЬТАТ',temporary:'ПОИСК ВРЕМЕННО НЕДОСТУПЕН',select:'Выберите вариант или введите полный домен, например mybusiness.com.',example:'Пример: mybusiness.com',checkingMsg:'Проверяем доступность домена…',registered:'Этот домен уже зарегистрирован.',appears:'Похоже, домен доступен. Мы подтвердим доступность и цену до списания средств.',registrar:'Доступность подтверждена регистратором.',retry:'Повторите попытку через несколько секунд.',failed:'Не удалось завершить поиск. Попробуйте снова.',button:'НАЙТИ',year:'/год'},
'he':{choose:'בחרו סיומת לדומיין',valid:'הזינו דומיין תקין',searching:'מחפש…',checking:'בודק…',not:'לא זמין',possible:'ייתכן שזמין',confirm:'ממתין לאישור',available:'✓ זמין',inconclusive:'תוצאה לא חד-משמעית',temporary:'החיפוש אינו זמין זמנית',select:'בחרו הצעה או הזינו דומיין מלא, לדוגמה mybusiness.com.',example:'דוגמה: mybusiness.com',checkingMsg:'בודק את זמינות הדומיין…',registered:'הדומיין הזה כבר רשום.',appears:'נראה שהוא זמין. נאשר זמינות ומחיר לפני כל חיוב.',registrar:'הזמינות אושרה על ידי רשם הדומיינים.',retry:'נסו שוב בעוד כמה שניות.',failed:'לא הצלחנו להשלים את החיפוש. נסו שוב.',button:'חיפוש',year:'/שנה'},
'zh-CN':{choose:'选择域名后缀',valid:'请输入有效域名',searching:'搜索中…',checking:'验证中…',not:'不可用',possible:'可能可用',confirm:'待确认',available:'✓ 可用',inconclusive:'结果不确定',temporary:'搜索暂时不可用',select:'请选择建议，或输入完整域名，例如 mybusiness.com。',example:'示例：mybusiness.com',checkingMsg:'正在检查域名是否可用…',registered:'此域名已被注册。',appears:'该域名似乎可用。我们会在收费前确认可用性和价格。',registrar:'注册商已确认该域名可用。',retry:'请几秒后重试。',failed:'无法完成搜索，请重试。',button:'搜索',year:'/年'},
'ja':{choose:'ドメイン拡張子を選択',valid:'有効なドメインを入力してください',searching:'検索中…',checking:'確認中…',not:'利用できません',possible:'利用できる可能性があります',confirm:'要確認',available:'✓ 利用可能',inconclusive:'結果を確認できません',temporary:'検索は一時的に利用できません',select:'候補を選ぶか、mybusiness.com のような完全なドメインを入力してください。',example:'例：mybusiness.com',checkingMsg:'ドメインの空き状況を確認しています…',registered:'このドメインはすでに登録されています。',appears:'利用できる可能性があります。課金前に空き状況と価格を確認します。',registrar:'レジストラによって利用可能と確認されました。',retry:'数秒後にもう一度お試しください。',failed:'検索を完了できませんでした。もう一度お試しください。',button:'検索',year:'/年'}
};
function locale(){const raw=(document.documentElement.dataset.csLocale||document.documentElement.lang||'en').trim();if(DS[raw])return raw;const low=raw.toLowerCase();if(low.startsWith('pt'))return 'pt-BR';if(low.startsWith('zh'))return 'zh-CN';if(low.startsWith('ar'))return 'ar-AE';const short=low.split('-')[0];return DS[short]?short:'en'}
const dt=()=>DS[locale()];
const TLDS=['.com','.ai','.co','.io','.app','.net'];
const suggest=document.createElement('div');suggest.id='domainSuggestions';suggest.style.cssText='display:none;gap:8px;flex-wrap:wrap;margin-top:10px';(document.querySelector('.searchrow')||input.parentElement).insertAdjacentElement('afterend',suggest);
const norm=v=>String(v||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0].replace(/\.$/,'');
const valid=d=>/^(?=.{3,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(d);
function suggestions(v){const q=norm(v).replace(/\..*$/,'').replace(/[^a-z0-9-]/g,'');if(!q||String(v).includes('.')){suggest.style.display='none';suggest.innerHTML='';return}suggest.innerHTML=TLDS.map(t=>`<button type="button" data-domain="${q+t}" style="border:1px solid #3b3345;background:#12101a;color:#F3F4F8;border-radius:999px;padding:9px 12px;font:800 12px Inter,system-ui;cursor:pointer">${q+t}</button>`).join('');suggest.style.display='flex';suggest.querySelectorAll('[data-domain]').forEach(x=>x.onclick=()=>{input.value=x.dataset.domain;suggest.style.display='none';go()})}
function set(name,status,cls,price='—',renew='—',note=''){ $('domainName').textContent=name||'Domain'; $('availability').className=cls; $('availability').textContent=status; $('price').textContent=price; $('renew').textContent=renew; $('note').textContent=note; result&&result.classList.add('show'); }
async function go(e){if(e){e.preventDefault();e.stopImmediatePropagation()}const d=norm(input.value);input.value=d;purchase&&purchase.classList.remove('show');if(!valid(d)){if(d&&!d.includes('.')){suggestions(d);set(d,dt().choose,'available','—','—',dt().select);return}set(d,dt().valid,'unavailable','—','—',dt().example);return}suggest.style.display='none';btn.disabled=true;btn.textContent=dt().searching;set(d,dt().checking,'available','—','—',dt().checkingMsg);try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);const r=await fetch('/api/domain-quote?domain='+encodeURIComponent(d),{cache:'no-store',headers:{accept:'application/json'},signal:c.signal});clearTimeout(timer);const j=await r.json().catch(()=>({}));if(!r.ok)throw Error('search_failed');if(j.availability==='registered'||j.registrable===false){set(d,dt().not,'unavailable','—','—',dt().registered)}else if(j.provisional||j.availability==='possibly_available'){set(d,dt().possible,'available',dt().confirm,dt().confirm,dt().appears);purchase&&purchase.classList.add('show')}else if(j.registrable===true){const cur=j.currency||'USD',fmt=v=>v==null?'—':new Intl.NumberFormat(locale(),{style:'currency',currency:cur}).format(v);set(d,dt().available,'available',fmt(j.sale_amount??j.normal?.registration),fmt(j.normal?.renewal)+dt().year,dt().registrar);purchase&&purchase.classList.add('show')}else set(d,dt().inconclusive,'unavailable','—','—',dt().retry)}catch(_){set(d,dt().temporary,'unavailable','—','—',dt().failed)}finally{btn.disabled=false;btn.textContent=dt().button}}
input.addEventListener('input',()=>suggestions(input.value));
input.addEventListener('keydown',e=>{if(e.key==='Enter')go(e)},true);
btn.addEventListener('click',go,true);
btn.textContent=dt().button;
window.addEventListener('cloudsales:locale',()=>{btn.textContent=dt().button;if(result&&result.classList.contains('show')&&!valid(norm(input.value)))set(norm(input.value),dt().valid,'unavailable','—','—',dt().example)});
})();
'''

s=s[:pos]+runtime
p.write_text(s,encoding='utf-8')
print('DOMAINS_SEARCH_RUNTIME_V4_11_LOCALES_OK')
