const fs=require('fs'),vm=require('vm');
function literalAfter(src,marker){const m=src.indexOf(marker);if(m<0)throw Error('missing '+marker);const start=src.indexOf('{',m+marker.length);if(start<0)throw Error('missing object');let d=0,q=null,e=false;for(let i=start;i<src.length;i++){const ch=src[i];if(q){if(e){e=false;continue}if(ch==='\\'){e=true;continue}if(ch===q)q=null;continue}if(ch==='"'||ch==="'"||ch==='`'){q=ch;continue}if(ch==='{')d++;else if(ch==='}'&&--d===0)return src.slice(start,i+1)}throw Error('unterminated')}
const code=fs.readFileSync('web/cloudsales-i18n-v1.js','utf8');const T=vm.runInNewContext('('+literalAfter(code,'const T=')+')'),F=vm.runInNewContext('('+literalAfter(code,'const CS_FINAL_TRANSLATIONS=')+')');for(const [k,v] of Object.entries(F))T[k]=Object.assign(T[k]||{},v);
const locales=['en','fr','it','pt-BR','de','ar-AE','ru','he','zh-CN','ja'];
const files=['web/commercial.html','web/commercial/domains-v2.html','web/services.html','web/academy.html','web/affiliate.html'];
const neutral=/^(?:CloudSales|Cloudy|AgentCloud|CloudCo|CRM|PWA|API|SEO|OAuth|Stripe|WhatsApp|Meta|Google|TikTok|LinkedIn|YouTube|HighLevel|Salesforce|HubSpot|Zoho CRM|Microsoft Dynamics 365|Pipedrive|monday CRM|Freshsales|Close|Copper|Twenty|Basic|Pro|Premium|Junk Lead Firewall|WAF|Conversion API|Web Events|CRM Events|Data Signals|USD|Academy|LISTIA|Cloudflare|PayPal|Binance|iPhone|iPad|Android|Windows|macOS|Desktop|AI|STARTER|WORKS)$/i;
function decode(x){return x.replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim()}
function visible(path){let h=fs.readFileSync(path,'utf8').replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<template\b[\s\S]*?<\/template>/gi,' ');const out=[];for(const m of h.matchAll(/>([^<>]+)</g)){const t=decode(m[1]);if(t)out.push(t)}for(const m of h.matchAll(/\b(?:placeholder|aria-label|title)=["']([^"']+)["']/gi)){const t=decode(m[1]);if(t)out.push(t)}return [...new Set(out)]}
function meaningful(t){if(!t||neutral.test(t)||/^[\d\s$€£¥.,:;·+%/—–-]+$/.test(t)||/^https?:\/\//i.test(t)||/^\S+@\S+$/.test(t))return false;if(t.length<2)return false;return /[A-Za-zÁÉÍÓÚÜÑáéíóúüñ¿¡À-žЀ-ӿ֐-׿؀-ۿ぀-ヿ㐀-鿿]/.test(t)}
let total=0;for(const f of files){const texts=visible(f).filter(meaningful);console.log('\nFILE',f,'VISIBLE_KEYS',texts.length);for(const lc of locales){const d=T[lc]||{};const miss=texts.filter(t=>!(t in d)&&!neutral.test(t));console.log('LOCALE',lc,'missing',miss.length,'of',texts.length);if(miss.length)console.log('MISS',lc,JSON.stringify(miss));total+=miss.length}}
console.log('\nTOTAL_VISIBLE_MISSING',total);process.exitCode=0;
