# CloudSales mobile native windows patch — trigger 2026-09-02.
from pathlib import Path
import re

p=Path('web/native-shell-runtime-v1.js')
s=p.read_text()

s=s.replace("const ID='cs-native-shell-v3';","const ID='cs-native-shell-v4';",1)

css_marker=".calMetric b{font-size:19px!important}\n}"
css_add=""".calMetric b{font-size:19px!important}
#page-leads.csLeadsNative>.sectionHead{display:none!important}#csLeadAnalytics.csLeadWindowed{height:100%!important;min-height:0!important;margin:0!important;display:block!important;overflow:hidden!important}.csLeadWindowTabs{display:flex;gap:5px;width:100%;height:36px;margin:0 0 8px}.csLeadWindowTabs button{flex:1;min-width:0;border:1px solid #2c2c39;background:#111119;color:#8f8e9e;border-radius:11px;padding:7px 3px;font-size:8px;font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.csLeadWindowTabs button.active{background:#251528;border-color:#5d3155;color:#fff}.csLeadView{height:calc(100% - 44px)!important;min-height:0!important;overflow:hidden!important}.csLeadView>.csAhero,.csLeadView>.csApanel{height:100%!important;min-height:0!important;margin:0!important;overflow:hidden!important}.csLeadView.csLeadQuality{display:grid;grid-template-rows:minmax(0,1fr) minmax(0,1fr);gap:7px}.csLeadView.csLeadQuality>.csApanel{padding:12px!important}.csLeadView.csLeadList{overflow-y:auto!important;overscroll-behavior:contain;scrollbar-width:none}.csLeadView.csLeadList::-webkit-scrollbar{display:none}.csLeadView.csLeadList .csLeadCards{display:grid!important;gap:7px}.csLeadView.csLeadList .csLeadCard{padding:10px!important;border-radius:14px!important}.csLeadView .csAhero{padding:14px!important}.csLeadView .csAhero h2{font-size:19px!important}.csLeadView .csAkpis{gap:6px!important;margin-top:10px!important}.csLeadView .csAkpi{padding:9px!important}.csLeadView .csAkpi b{font-size:19px!important}.csLeadView .csAkpi small{font-size:8px!important}.csLeadView .csApanel{padding:13px!important}.csSwipeHint{position:absolute;right:15px;bottom:10px;font-size:8px;color:#626171;pointer-events:none}
}"
if css_marker not in s:
    raise SystemExit('mobile css marker not found')
s=s.replace(css_marker,css_add,1)

pat=r"function ensureMore\(\)\{.*?\nfunction openMore"
replacement="""function moreLabels(){const es=(document.documentElement.dataset.csLocale||'').startsWith('es');return es?{marketing:'Marketing',inbox:'Chat IA',calendar:'Calendario',files:'Archivos',connect:'Integraciones',settings:'Cuenta',affiliate:'Afiliados',close:'Cerrar'}:{marketing:'Marketing',inbox:'AI Chat',calendar:'Calendar',files:'Files',connect:'Integrations',settings:'Account',affiliate:'Affiliate',close:'Close'}}
function ensureMore(){const locale=(document.documentElement.dataset.csLocale||'en'),existing=document.getElementById('csMoreSheet');if(existing&&existing.dataset.locale===locale)return;if(existing){existing.remove();document.getElementById('csMoreBackdrop')?.remove()}const L=moreLabels(),back=document.createElement('div');back.id='csMoreBackdrop';back.onclick=closeMore;const sheet=document.createElement('div');sheet.id='csMoreSheet';sheet.dataset.locale=locale;sheet.innerHTML=`<div class=\"csMoreHead\"><b>CloudSales</b><button class=\"csMoreClose\" type=\"button\" aria-label=\"${L.close}\">×</button></div><div class=\"csMoreGrid\"><button class=\"csMoreItem\" data-more=\"marketing\">${icon('marketing')}<span>${L.marketing}</span></button><button class=\"csMoreItem\" data-more=\"inbox\">${icon('inbox')}<span>${L.inbox}</span></button><button class=\"csMoreItem\" data-more=\"calendar\">${icon('calendar')}<span>${L.calendar}</span></button><button class=\"csMoreItem\" data-more=\"files\">${icon('files')}<span>${L.files}</span></button><button class=\"csMoreItem\" data-more=\"connect\">${icon('connect')}<span>${L.connect}</span></button><button class=\"csMoreItem\" data-more=\"settings\">${icon('settings')}<span>${L.settings}</span></button><button class=\"csMoreItem\" data-more=\"affiliate\">${icon('affiliate')}<span>${L.affiliate}</span></button></div>`;document.body.append(back,sheet);sheet.querySelector('.csMoreClose').onclick=closeMore;sheet.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>route(b.dataset.more))}
function openMore"""
s,n=re.subn(pat,replacement,s,count=1,flags=re.S)
if n!=1: raise SystemExit('ensureMore function not patched')

pat=r"function makeWindowed\(page,defs,extraClass=''\)\{.*?\nfunction organizeHome"
replacement="""function bindSwipe(el,count,getIndex,show){if(!el||count<2||el.dataset.csSwipe==='1')return;el.dataset.csSwipe='1';let sx=0,sy=0,blocked=false;el.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;const t=e.target;blocked=Boolean(t?.closest?.('input,textarea,select,button,.pipeline,.tablewrap,.messages,.a2msgs'));sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});el.addEventListener('touchend',e=>{if(blocked||!sx)return;const x=e.changedTouches?.[0]?.clientX??sx,y=e.changedTouches?.[0]?.clientY??sy,dx=x-sx,dy=y-sy;sx=sy=0;if(Math.abs(dx)<48||Math.abs(dx)<=Math.abs(dy)*1.2)return;const cur=getIndex(),next=dx<0?Math.min(count-1,cur+1):Math.max(0,cur-1);if(next!==cur){haptic();show(next)}},{passive:true})}
function makeWindowed(page,defs,extraClass=''){if(!MOBILE()||!page||page.dataset.csWindowed==='1')return;const found=[];for(const d of defs){const block=findBlock(page,d.patterns);if(block&&!found.some(x=>x.block===block))found.push({...d,block})}if(found.length<2)return;page.dataset.csWindowed='1';page.classList.add('csAppWindowed');if(extraClass)page.classList.add(extraClass);const tabs=document.createElement('div');tabs.className='csWindowTabs';tabs.setAttribute('role','tablist');page.insertBefore(tabs,page.firstChild);const allDirect=[...page.children].filter(x=>x!==tabs);allDirect.forEach(x=>{if(found.some(f=>f.block===x))x.classList.add('csWindowPanel');else x.dataset.csWindowAux='1'});let current=0;function show(i){current=i;found.forEach((f,n)=>{f.block.style.display=n===i?'block':'none'});allDirect.filter(x=>x.dataset.csWindowAux==='1').forEach(x=>x.style.display='none');tabs.querySelectorAll('button').forEach((b,n)=>{b.classList.toggle('active',n===i);b.setAttribute('aria-selected',n===i?'true':'false');b.tabIndex=n===i?0:-1})}found.forEach((f,i)=>{const b=document.createElement('button');b.type='button';b.textContent=f.label;b.setAttribute('role','tab');b.onclick=()=>{haptic();show(i)};tabs.appendChild(b)});show(0);bindSwipe(page,found.length,()=>current,show)}
function organizeHome"""
s,n=re.subn(pat,replacement,s,count=1,flags=re.S)
if n!=1: raise SystemExit('makeWindowed function not patched')

pat=r"function organizePipeline\(\)\{.*?\nfunction organizeActive\(\)\{.*?\}"
replacement="""function makeAnalyticsWindows(root,views,className){if(!root||views.length<2)return;root.classList.add(className);const old=root.querySelector(':scope>.csWindowTabs,:scope>.csLeadWindowTabs');if(old)old.remove();const tabs=document.createElement('div');tabs.className=className==='csLeadWindowed'?'csLeadWindowTabs':'csWindowTabs';tabs.setAttribute('role','tablist');root.prepend(tabs);let current=0;function show(i){current=i;views.forEach((v,n)=>{v.el.style.display=n===i?(v.display||'block'):'none'});tabs.querySelectorAll('button').forEach((b,n)=>{b.classList.toggle('active',n===i);b.setAttribute('aria-selected',n===i?'true':'false');b.tabIndex=n===i?0:-1})}views.forEach((v,i)=>{const b=document.createElement('button');b.type='button';b.textContent=v.label;b.setAttribute('role','tab');b.onclick=()=>{haptic();show(i)};tabs.appendChild(b)});show(0);bindSwipe(root,views.length,()=>current,show)}
function organizeLeads(){const page=document.getElementById('page-leads'),root=document.getElementById('csLeadAnalytics');if(!page||!root)return;if(root.dataset.csLeadWindowed==='1'&&root.querySelector('.csLeadWindowTabs'))return;root.dataset.csLeadWindowed='1';page.classList.add('csLeadsNative');const hero=root.querySelector(':scope>.csAhero'),grid=root.querySelector(':scope>.csAgrid'),panels=grid?[...grid.querySelectorAll(':scope>.csApanel')]:[],cards=root.querySelector(':scope>.csLeadCards'),label=root.querySelector(':scope>.csSectionLabel');if(!hero||panels.length<3||!cards)return;const [quality,sources,activity,watch]=panels;const qView=document.createElement('div');qView.className='csLeadView csLeadQuality';qView.append(quality);if(watch)qView.append(watch);const sourceView=document.createElement('div');sourceView.className='csLeadView';sourceView.append(sources);const activityView=document.createElement('div');activityView.className='csLeadView';activityView.append(activity);const listView=document.createElement('div');listView.className='csLeadView csLeadList';listView.append(cards);hero.classList.add('csLeadView');grid?.remove();label?.remove();root.append(qView,sourceView,activityView,listView);makeAnalyticsWindows(root,[{label:'Overview',el:hero},{label:'Quality',el:qView},{label:'Sources',el:sourceView},{label:'Activity',el:activityView},{label:'Leads',el:listView}],'csLeadWindowed')}
function organizePipeline(){const page=document.getElementById('page-pipeline'),root=document.getElementById('csPipelineAnalytics');if(root){if(root.dataset.csPipelineWindowed==='1'&&root.querySelector(':scope>.csWindowTabs'))return;const hero=root.querySelector(':scope>.csAhero'),grid=root.querySelector(':scope>.csAgrid'),panels=grid?[...grid.querySelectorAll(':scope>.csApanel')]:[];if(hero&&panels.length>=2){root.dataset.csPipelineWindowed='1';page?.classList.add('csAppWindowed');const stage=panels[0],value=panels[1];hero.classList.add('csWindowPanel');stage.classList.add('csWindowPanel');value.classList.add('csWindowPanel');grid?.remove();root.append(stage,value);makeAnalyticsWindows(root,[{label:'Overview',el:hero},{label:'Stages',el:stage},{label:'Value',el:value}],'csPipelineWindowed');return}}makeWindowed(page,[{label:'Overview',patterns:[/Pipeline Intelligence/i,/Intelligence/i]},{label:'Stages',patterns:[/Pipeline by stage/i,/by stage/i]},{label:'Value',patterns:[/Value by stage/i]},{label:'Deals',patterns:[/Business opportunities/i,/Opportunit/i]}])}
function organizeActive(){if(!MOBILE())return;organizeHome();organizeLeads();organizePipeline();document.scrollingElement?.scrollTo?.(0,0)}"""
s,n=re.subn(pat,replacement,s,count=1,flags=re.S)
if n!=1: raise SystemExit('organizers not patched')

old="""function observe(){const c=document.querySelector('.content');if(!c)return;new MutationObserver(()=>{sync();organizeActive()}).observe(c,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('hashchange',()=>setTimeout(()=>{sync();organizeActive()},30));window.addEventListener('resize',()=>setTimeout(()=>{build();organizeActive()},50))}"""
new="""function observe(){const c=document.querySelector('.content');if(!c)return;new MutationObserver(()=>{sync();organizeActive()}).observe(c,{subtree:true,attributes:true,attributeFilter:['class']});const leads=document.getElementById('page-leads'),pipeline=document.getElementById('page-pipeline');for(const page of [leads,pipeline].filter(Boolean))new MutationObserver(()=>{requestAnimationFrame(()=>{const lr=document.getElementById('csLeadAnalytics');if(lr&&lr.dataset.csLeadWindowed==='1'&&!lr.querySelector('.csLeadWindowTabs'))lr.dataset.csLeadWindowed='';const pr=document.getElementById('csPipelineAnalytics');if(pr&&pr.dataset.csPipelineWindowed==='1'&&!pr.querySelector(':scope>.csWindowTabs'))pr.dataset.csPipelineWindowed='';organizeActive()})}).observe(page,{subtree:true,childList:true});window.addEventListener('hashchange',()=>setTimeout(()=>{sync();organizeActive()},30));window.addEventListener('resize',()=>setTimeout(()=>{build();organizeActive()},50));window.addEventListener('cloudsales:locale',()=>{document.getElementById('csMoreSheet')?.remove();document.getElementById('csMoreBackdrop')?.remove();build()})}"""
if old not in s: raise SystemExit('observer marker not found')
s=s.replace(old,new,1)

old="""function sync(){const p=activePage();document.querySelectorAll('.bottomnav [data-native-page]').forEach(b=>b.classList.toggle('active',b.dataset.nativePage===p));if(!['marketing','inbox','calendar','files','connect','settings','affiliate'].includes(p))document.querySelector('.bottomnav [data-native-more]')?.classList.remove('active');else document.querySelector('.bottomnav [data-native-more]')?.classList.add('active')}"""
new="""function sync(){const p=activePage();document.querySelectorAll('.bottomnav [data-native-page]').forEach(b=>{const on=b.dataset.nativePage===p;b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});const more=document.querySelector('.bottomnav [data-native-more]'),onMore=['marketing','inbox','calendar','files','connect','settings','affiliate'].includes(p);more?.classList.toggle('active',onMore);if(onMore)more?.setAttribute('aria-current','page');else more?.removeAttribute('aria-current')}"""
if old not in s: raise SystemExit('sync marker not found')
s=s.replace(old,new,1)

for marker in ["cs-native-shell-v4","function bindSwipe","function organizeLeads","csLeadWindowTabs","moreLabels","aria-current","childList:true"]:
    if marker not in s: raise SystemExit('missing '+marker)

p.write_text(s)
print('mobile native windows patch applied')
