import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!,ANON=Deno.env.get("SUPABASE_ANON_KEY")!,SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const origins=new Set(["https://cloudsales.app","https://www.cloudsales.app","https://app.cloudsales.app","http://localhost:3000","http://localhost:5173"]);
function cors(o:string|null){const v=o&&origins.has(o)?o:"https://app.cloudsales.app";return{"Access-Control-Allow-Origin":v,"Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Vary":"Origin"}}
function json(b:unknown,s=200,o:string|null=null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"Content-Type":"application/json;charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
async function autoClaimByVerifiedEmail(svc:any,user:any){
  const email=String(user?.email||'').trim().toLowerCase(); if(!email||!user?.email_confirmed_at)return null;
  const {data:claims}=await svc.from('organization_claim_tokens').select('id,organization_id,role,expected_email,expires_at,consumed_at').eq('expected_email',email).is('consumed_at',null).gt('expires_at',new Date().toISOString()).limit(2);
  if(!claims||claims.length!==1)return null;
  const claim=claims[0]; const {data:org}=await svc.from('organizations').select('id,name,slug,status,plan_key').eq('id',claim.organization_id).maybeSingle(); if(!org||org.status!=='active')return null;
  const requestedRole=['owner','admin','operator','viewer'].includes(String(claim.role||''))?String(claim.role):'operator';
  const {data:owners}=await svc.from('organization_members').select('user_id').eq('organization_id',org.id).eq('status','active').eq('role','owner');
  if(requestedRole==='owner'&&(owners||[]).length&&!(owners||[]).some((x:any)=>x.user_id===user.id))return null;
  const {data:existing}=await svc.from('organization_members').select('role,status').eq('organization_id',org.id).eq('user_id',user.id).maybeSingle();
  const role=existing?.status==='active'&&existing?.role?String(existing.role):requestedRole;
  const {error:me}=await svc.from('organization_members').upsert({organization_id:org.id,user_id:user.id,role,status:'active',updated_at:new Date().toISOString()},{onConflict:'organization_id,user_id'}); if(me)return null;
  const {error:ce}=await svc.from('organization_claim_tokens').update({consumed_at:new Date().toISOString(),consumed_by:user.id}).eq('id',claim.id).is('consumed_at',null); if(ce)return null;
  await svc.from('audit_log').insert({organization_id:org.id,actor_user_id:user.id,actor_type:'user',action:'organization.auto_claimed_verified_email',entity_type:'organization',entity_id:org.id,success:true,context:{role,oauth_or_verified_email:true}});
  return {organization_id:org.id,role};
}
Deno.serve(async req=>{const o=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(o)});if(!["GET","POST"].includes(req.method))return json({error:"method_not_allowed"},405,o);if(o&&!origins.has(o))return json({error:"origin_not_allowed"},403,o);const auth=req.headers.get("authorization");if(!auth)return json({error:"missing_authorization"},401,o);const uc=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:ud,error:ue}=await uc.auth.getUser();const user=ud.user;if(ue||!user)return json({error:"invalid_session"},401,o);const svc=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});const autoClaim=await autoClaimByVerifiedEmail(svc,user).catch(()=>null);const [{data:memberships,error:me},{data:profile},{data:providers},{data:plans},{data:bundles},{data:voices},{data:agentTemplates},{data:aiRuntime},{data:voiceRuntime},{data:cfAiSetting}]=await Promise.all([
svc.from("organization_members").select("organization_id,role,status").eq("user_id",user.id).eq("status","active"),
svc.from("profiles").select("full_name,locale,timezone,avatar_url").eq("id",user.id).maybeSingle(),
svc.from("provider_catalog").select("provider_key,display_name,category,auth_type,availability,sort_order,metadata").neq("availability","disabled").order("sort_order"),
svc.from("subscription_plans").select("plan_key,name,monthly_price,currency,features").eq("active",true).order("monthly_price"),
svc.from("integration_bundles").select("bundle_key,provider_key,display_name,description,product_keys,one_click,availability,metadata,sort_order").neq("availability","disabled").order("sort_order"),
svc.from("cloudy_voice_profiles").select("voice_key,locale,display_name,engine,model,native_reference_required,reference_asset_uri,style_prompt,config").eq("active",true),
svc.from("cloudy_agent_templates").select("template_key,display_name,description,channels,capabilities,default_voice_key,config").eq("active",true),
svc.from("internal_settings").select("value").eq("setting_key","cloudy_ai_runtime").maybeSingle(),
svc.from("internal_settings").select("value").eq("setting_key","cloudy_voice_runtime").maybeSingle(),
svc.from("internal_settings").select("secret_id").in("setting_key",["cloudflare_ai_gateway_token_cloudsales","cloudflare_api_token_cloudsales"]).not("secret_id","is",null).limit(1).maybeSingle()
]);if(me)return json({error:"membership_lookup_failed"},500,o);const orgIds=(memberships||[]).map((m:any)=>m.organization_id);const common={user:{id:user.id,email:user.email,full_name:profile?.full_name||null,locale:profile?.locale||"en",timezone:profile?.timezone||null,avatar_url:profile?.avatar_url||null},auto_claim:autoClaim,providers:(providers||[]).filter((p:any)=>p.metadata?.internal_only!==true),plans:plans||[],integration_bundles:bundles||[],cloudy:{ai_ready:Boolean(cfAiSetting?.secret_id),ai_runtime:{enabled:Boolean(aiRuntime?.value?.enabled),default_route:aiRuntime?.value?.default_route||"cloudy_general"},voice_runtime:{enabled:Boolean(voiceRuntime?.value?.enabled),preferred_identity_engine:voiceRuntime?.value?.preferred_identity_engine||"chatterbox_v3",preferred_identity_ready:Boolean(voiceRuntime?.value?.preferred_identity_ready),fallback_tts_model:voiceRuntime?.value?.tts_fallback_model||null,asr_model:voiceRuntime?.value?.asr_model||null},voice_profiles:voices||[],agent_templates:agentTemplates||[]}};if(!orgIds.length)return json({...common,organizations:[]},200,o);
const [orgsR,summaryR,connR,gatesR,subsR,healthR,agentsR,jobsR,supportR,toolR,aiRunsR]=await Promise.all([
svc.from("organizations").select("id,name,slug,status,plan_key,country_code,timezone").in("id",orgIds),
svc.from("organization_dashboard_summary").select("organization_id,name,status,plan_key,connected_providers,lead_attempts_30d,leads_accepted_30d,leads_rejected_30d,avg_quality_score_30d,appointments_30d,won_30d").in("organization_id",orgIds),
svc.from("connections").select("id,organization_id,provider_key,status,external_account_name,external_account_id,scopes,expires_at,last_sync_at,metadata").in("organization_id",orgIds),
svc.from("gate_configs").select("id,organization_id,slug,status,hostname,allowed_origins,primary_crm_connection_id,min_accept_score,challenge_score,config").in("organization_id",orgIds),
svc.from("subscriptions").select("id,organization_id,plan_key,status,billing_provider,current_period_start,current_period_end,cancel_at_period_end").in("organization_id",orgIds),
svc.from("connection_health_checks").select("organization_id,connection_id,status,latency_ms,error,checked_at").in("organization_id",orgIds).order("checked_at",{ascending:false}).limit(150),
svc.from("cloudy_agents").select("id,organization_id,name,template_key,status,autonomy_mode,channels,capabilities,voice_key,updated_at").in("organization_id",orgIds).order("created_at",{ascending:false}),
svc.from("automation_jobs").select("id,organization_id,job_type,status,requires_approval,error,created_at,finished_at,input,output").in("organization_id",orgIds).in("status",["waiting_approval","queued","running","failed"]).order("created_at",{ascending:false}).limit(150),
svc.from("cloudy_support_cases").select("id,organization_id,status,severity,category,title,summary,created_at,updated_at,resolved_at").in("organization_id",orgIds).in("status",["open","investigating"]).order("created_at",{ascending:false}).limit(100),
svc.from("cloudy_tool_runs").select("id,organization_id,provider_key,action_key,status,error,created_at,finished_at").in("organization_id",orgIds).order("created_at",{ascending:false}).limit(100),
svc.from("cloudy_ai_runs").select("id,organization_id,route_key,model_key,model_id,provider_key,status,latency_ms,input_tokens,output_tokens,total_tokens,tool_calls,error,started_at,finished_at").in("organization_id",orgIds).order("started_at",{ascending:false}).limit(50)
]);const roleBy=Object.fromEntries((memberships||[]).map((x:any)=>[x.organization_id,x.role]));const summaries=new Map((summaryR.data||[]).map((x:any)=>[x.organization_id,x]));const conns=connR.data||[],gates=gatesR.data||[],subs=subsR.data||[],health=healthR.data||[],agents=agentsR.data||[],jobs=jobsR.data||[],support=supportR.data||[],tools=toolR.data||[],aiRuns=aiRunsR.data||[];const organizations=(orgsR.data||[]).map((org:any)=>{const orgJobs=jobs.filter((x:any)=>x.organization_id===org.id),orgAgents=agents.filter((x:any)=>x.organization_id===org.id),orgSupport=support.filter((x:any)=>x.organization_id===org.id),orgTools=tools.filter((x:any)=>x.organization_id===org.id),orgAi=aiRuns.filter((x:any)=>x.organization_id===org.id);return{...org,role:roleBy[org.id],metrics:summaries.get(org.id)||null,connections:conns.filter((x:any)=>x.organization_id===org.id),gates:gates.filter((x:any)=>x.organization_id===org.id),subscription:subs.find((x:any)=>x.organization_id===org.id)||null,connection_health:health.filter((x:any)=>x.organization_id===org.id),cloudy:{agents:orgAgents,pending_approvals:orgJobs.filter((x:any)=>x.status==="waiting_approval"),active_jobs:orgJobs.filter((x:any)=>["queued","running"].includes(x.status)),recent_failures:orgJobs.filter((x:any)=>x.status==="failed").slice(0,10),support_cases:orgSupport,recent_tool_runs:orgTools.slice(0,20),recent_ai_runs:orgAi.slice(0,10),counts:{agents:orgAgents.length,agents_active:orgAgents.filter((x:any)=>x.status==="active").length,pending_approvals:orgJobs.filter((x:any)=>x.status==="waiting_approval").length,active_jobs:orgJobs.filter((x:any)=>["queued","running"].includes(x.status)).length,open_support_cases:orgSupport.length}}}});return json({...common,organizations},200,o)});