import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import {ensureZernioProfile,startZernioConnect,verifyZernioConnect,zernioConfigured} from './zernio.ts';
const U=Deno.env.get("SUPABASE_URL")!,A=Deno.env.get("SUPABASE_ANON_KEY")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ORIGINS=new Set(["https://cloudsales.app","https://www.cloudsales.app","https://app.cloudsales.app","http://localhost:3000","http://localhost:5173"]);
function cors(o:string|null){const v=o&&ORIGINS.has(o)?o:"https://app.cloudsales.app";return{"Access-Control-Allow-Origin":v,"Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
function json(b:unknown,s=200,o:string|null=null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"content-type":"application/json;charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}})}
Deno.serve(async req=>{const o=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(o)});if(req.method!=="POST")return json({error:"method_not_allowed"},405,o);if(o&&!ORIGINS.has(o))return json({error:"origin_not_allowed"},403,o);const auth=req.headers.get("authorization");if(!auth)return json({error:"missing_authorization"},401,o);const uc=createClient(U,A,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:ud}=await uc.auth.getUser();const user=ud.user;if(!user)return json({error:"invalid_session"},401,o);let b:any={};try{b=await req.json()}catch{}const org=String(b.organization_id||"");if(!org)return json({error:"organization_id_required"},400,o);const svc=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});const {data:m}=await svc.from("organization_members").select("role,status").eq("organization_id",org).eq("user_id",user.id).maybeSingle();if(!m||m.status!=="active")return json({error:"forbidden"},403,o);const action=String(b.action||'');
try{
 if(action==='zernio_status'){const [{data:p},configured]=await Promise.all([svc.from('integration_aggregator_profiles').select('status,external_profile_id,last_error,metadata,updated_at').eq('organization_id',org).eq('provider_key','zernio').maybeSingle(),zernioConfigured(svc)]);return json({provider:'zernio',configured,profile:p||null,connected_accounts:Array.isArray(p?.metadata?.connected_accounts)?p.metadata.connected_accounts:[]},200,o)}
 if(action==='zernio_profile_ensure'){const p=await ensureZernioProfile(svc,org);return json({provider:'zernio',profile_id:p.external_profile_id,status:p.status},200,o)}
 if(action==='zernio_connect_start'){const redirect='https://app.cloudsales.app/?zernio_callback=1';const r=await startZernioConnect(svc,org,String(b.platform||''),redirect);return json(r,200,o)}
 if(action==='zernio_connect_finalize'){const r=await verifyZernioConnect(svc,org,b);await svc.from('audit_log').insert({organization_id:org,actor_user_id:user.id,actor_type:'user',action:'integration.zernio.account.connected',entity_type:'integration_account',success:true,context:{platform:r.account.platform,account_id:r.account.account_id}});return json(r,200,o)}
}catch(e){const code=String((e as Error).message||e);await svc.from('audit_log').insert({organization_id:org,actor_user_id:user.id,actor_type:'user',action:`integration.${action||'unknown'}.failed`,entity_type:'integration',success:false,context:{error:code.slice(0,180)}});return json({error:code},code==='zernio_not_configured'?503:400,o)}
if(action==="resolve_route"){
 const capability=String(b.capability_key||"");if(!capability)return json({error:"capability_key_required"},400,o);const preferred=String(b.preferred_provider||"");
 const [{data:connections},{data:routes},{data:caps},{data:readiness},{data:aggregators}]=await Promise.all([
  svc.from("connections").select("id,provider_key,status,external_account_id,external_account_name,metadata").eq("organization_id",org).eq("status","connected"),svc.from("integration_provider_routes").select("capability_key,provider_key,route_type,priority,enabled,minimum_support_status,quality_weight,cost_weight,latency_weight,metadata").eq("capability_key",capability).eq("enabled",true).order("priority"),svc.from("provider_capabilities").select("provider_key,capability_key,support_status,write_capable,metadata").eq("capability_key",capability),svc.from("integration_readiness").select("provider_key,status,priority,next_action"),svc.from('integration_aggregator_profiles').select('provider_key,status,external_profile_id,metadata').eq('organization_id',org)]);
 const connBy=new Map((connections||[]).map((c:any)=>[c.provider_key,c])),capBy=new Map((caps||[]).map((c:any)=>[c.provider_key,c])),readyBy=new Map((readiness||[]).map((r:any)=>[r.provider_key,r])),aggBy=new Map((aggregators||[]).map((r:any)=>[r.provider_key,r])),rank:any={implemented:3,beta:2,planned:1,unsupported:0};
 const candidates=(routes||[]).map((r:any)=>{const c:any=capBy.get(r.provider_key),cn:any=connBy.get(r.provider_key),rd:any=readyBy.get(r.provider_key),ag:any=aggBy.get(r.provider_key);const capabilityReady=!!c&&rank[String(c.support_status||"")]>=rank[String(r.minimum_support_status||"beta")];const aggregatorAccounts=Array.isArray(ag?.metadata?.connected_accounts)?ag.metadata.connected_accounts.length:0;const infrastructureReady=r.route_type==="direct"?!!cn:(rd?.status==="ready"&&ag?.status==='ready'&&aggregatorAccounts>0);const usable=capabilityReady&&infrastructureReady;return{...r,support_status:c?.support_status||null,readiness_status:rd?.status||null,write_capable:!!c?.write_capable,connected:!!cn,connection_id:cn?.id||null,aggregator_profile_ready:ag?.status==='ready',aggregator_accounts:aggregatorAccounts,usable,blocked_reason:usable?null:(!capabilityReady?"capability_not_ready":(r.route_type==="direct"?"connection_required":"aggregator_tenant_not_ready")),score:Number(r.priority)+(preferred===r.provider_key?-10000:0)}}).sort((a:any,b:any)=>a.score-b.score);
 const selected=candidates.find((x:any)=>x.usable)||null;await svc.from("audit_log").insert({organization_id:org,actor_user_id:user.id,actor_type:"user",action:"integration.route.resolved",entity_type:"integration_route",success:!!selected,context:{capability_key:capability,selected_provider:selected?.provider_key||null,candidate_count:candidates.length}});return json({organization_id:org,capability_key:capability,selected,candidates},selected?200:409,o);
}
const [providers,products,bundles,caps,ready,connections,routes,aiProviders,aiModels,aiRoutes,routeModels,voices,templates]=await Promise.all([svc.from("provider_catalog").select("provider_key,display_name,category,auth_type,availability,sort_order,metadata").neq("availability","disabled").order("sort_order"),svc.from("provider_products").select("provider_key,product_key,display_name,category,availability,capabilities,requested_scopes,metadata,sort_order").neq("availability","disabled").order("sort_order"),svc.from("integration_bundles").select("bundle_key,provider_key,display_name,description,product_keys,requested_scopes,one_click,availability,metadata,sort_order").neq("availability","disabled").order("sort_order"),svc.from("provider_capabilities").select("provider_key,capability_key,support_status,write_capable,requires_provider_review,notes,metadata"),svc.from("integration_readiness").select("provider_key,phase,priority,status,owner,required_items,next_action,notes"),svc.from("connections").select("id,provider_key,status,external_account_name,scopes,expires_at,last_sync_at,metadata").eq("organization_id",org),svc.from("integration_provider_routes").select("capability_key,provider_key,route_type,priority,enabled,minimum_support_status,quality_weight,cost_weight,latency_weight,metadata").eq("enabled",true).order("priority"),svc.from("ai_provider_catalog").select("provider_key,display_name,gateway_mode,availability,modalities,capabilities,sort_order,metadata").neq("availability","disabled").order("sort_order"),svc.from("ai_model_catalog").select("model_key,provider_key,model_id,display_name,availability,modalities,capabilities,context_tokens,cost_tier,quality_tier,speed_tier,metadata").not("availability","in","(disabled,deprecated)"),svc.from("ai_route_catalog").select("route_key,display_name,task_type,primary_provider_key,fallback_provider_keys,selector,max_cost_tier,latency_target_ms,enabled,metadata").eq("enabled",true),svc.from("ai_route_models").select("route_key,model_key,priority,conditions,enabled").eq("enabled",true).order("priority"),svc.from("cloudy_voice_profiles").select("voice_key,locale,display_name,engine,model,native_reference_required,style_prompt,config,active").eq("active",true),svc.from("cloudy_agent_templates").select("template_key,display_name,description,channels,capabilities,default_voice_key,system_instructions,config,active").eq("active",true)]);
const HIDDEN_INTERNAL=new Set(["highlevel"]),conn=connections.data||[],byProvider=Object.fromEntries(conn.map((x:any)=>[x.provider_key,x]));const providerRows=(providers.data||[]).filter((p:any)=>!HIDDEN_INTERNAL.has(p.provider_key)&&p.metadata?.internal_only!==true).map((p:any)=>({...p,connection:byProvider[p.provider_key]||null,capabilities:(caps.data||[]).filter((c:any)=>c.provider_key===p.provider_key),readiness:(ready.data||[]).find((r:any)=>r.provider_key===p.provider_key)||null,products:(products.data||[]).filter((x:any)=>x.provider_key===p.provider_key)}));const clientBundles=(bundles.data||[]).filter((x:any)=>!HIDDEN_INTERNAL.has(x.provider_key)&&!(providers.data||[]).find((p:any)=>p.provider_key===x.provider_key)?.metadata?.internal_only).map((x:any)=>({...x,connection:byProvider[x.provider_key]||null}));return json({organization_id:org,role:m.role,bundles:clientBundles,providers:providerRows,provider_routes:routes.data||[],internal_crm:{provider_key:"highlevel",display_name:"HIGHLEVEL",included:true,status:byProvider.highlevel?.status||"preparing",connection:byProvider.highlevel||null,description:"CRM infrastructure operated by CloudSales through HIGHLEVEL."},ai:{providers:aiProviders.data||[],models:aiModels.data||[],routes:aiRoutes.data||[],route_models:routeModels.data||[]},voice_profiles:voices.data||[],agent_templates:templates.data||[]},200,o)});