(()=>{'use strict';
const ENDPOINT='https://fkahaqprzgcimgyathqx.supabase.co/functions/v1/pennyworth-now';
const GATE='69a3dc7f-d733-41b4-aec5-08d7ca521d81';
const HOST='pennyworth.cloudsales.app';
const TURNSTILE_SITEKEY='0x4AAAAAAEiK97f4nFyAgMYx';
const qs=new URLSearchParams(location.search);
const clean=(v,n=600)=>String(v||'').trim().slice(0,n);
const uuid=()=>{try{return crypto.randomUUID()}catch{return Date.now().toString(36)+Math.random().toString(36).slice(2)}};
const getStore=(s,k)=>{try{return s.getItem(k)||''}catch{return''}};
const setStore=(s,k,v)=>{try{s.setItem(k,v)}catch{}};
let anon=getStore(localStorage,'pw_anon_v1');if(!anon){anon=uuid();setStore(localStorage,'pw_anon_v1',anon)}
let session=getStore(sessionStorage,'pw_session_v1');if(!session){session=uuid();setStore(sessionStorage,'pw_session_v1',session)}
const cookie=name=>{for(const part of document.cookie.split(';')){const bits=part.trim().split('=');const key=bits.shift();if(key===name)return decodeURIComponent(bits.join('='))}return''};
let attr={};try{attr=JSON.parse(getStore(localStorage,'pw_attr_v1')||'{}')||{}}catch{attr={}}
const take=(key,vals)=>{for(const v of vals){if(clean(v)){attr[key]=clean(v);return}}};
take('fbclid',[qs.get('fbclid')]);take('fbc',[cookie('_fbc')]);take('fbp',[cookie('_fbp')]);
take('campaign_id',[qs.get('campaign_id'),qs.get('utm_id'),qs.get('campaign')]);
take('ad_group_id',[qs.get('adset_id'),qs.get('ad_set_id'),qs.get('adgroup_id')]);
take('ad_id',[qs.get('ad_id'),qs.get('adid')]);
take('utm_source',[qs.get('utm_source')]);take('utm_medium',[qs.get('utm_medium')]);take('utm_campaign',[qs.get('utm_campaign')]);take('utm_content',[qs.get('utm_content')]);
try{setStore(localStorage,'pw_attr_v1',JSON.stringify(attr))}catch{}
const ref=clean(document.referrer,1800);const sourceText=((attr.utm_source||'')+' '+ref).toLowerCase();const isMeta=Boolean(attr.fbclid)||/facebook|instagram|meta|\bfb\b|\big\b/.test(sourceText);
const provider=isMeta?'meta':clean(attr.utm_source||'direct',80);
const metaBase=()=>({page_title:clean(document.title,300),timezone:clean(Intl.DateTimeFormat().resolvedOptions().timeZone,120),viewport:String(innerWidth)+'x'+String(innerHeight)});
const propertyFrom=el=>{if(!el)return{};const d=el.dataset||{};return{inventory_id:clean(d.inventoryId||'',180),property_key:clean(d.propertyKey||d.property||'',180)}};
const body=(name,extra={})=>Object.assign({event_name:name,event_id:name.toLowerCase()+':'+uuid(),session_id:session,anonymous_id:anon,landing_url:clean(location.href,1800),referrer:ref,source_provider:provider,campaign_id:clean(attr.campaign_id,180),ad_group_id:clean(attr.ad_group_id,180),ad_id:clean(attr.ad_id,180),fbclid:clean(attr.fbclid,600),fbc:clean(attr.fbc,600),fbp:clean(attr.fbp,600),utm_source:clean(attr.utm_source,180),utm_medium:clean(attr.utm_medium,180),utm_campaign:clean(attr.utm_campaign,300),utm_content:clean(attr.utm_content,300),locale:clean(document.documentElement.lang||navigator.language,80),qa:qs.get('qa')==='1',metadata:metaBase(),occurred_at:new Date().toISOString()},extra);
const send=(name,extra={})=>{try{return fetch(ENDPOINT,{method:'POST',mode:'cors',credentials:'omit',keepalive:true,headers:{'content-type':'application/json','x-pennyworth-gate':GATE},body:JSON.stringify(body(name,extra))}).catch(()=>null)}catch{return Promise.resolve(null)}};
const once=(key,fn)=>{const k='pw_once:'+key+':'+session;if(getStore(sessionStorage,k))return;setStore(sessionStorage,k,'1');fn()};
once('landing',()=>send('LandingView'));if(isMeta)once('meta_landing',()=>send('MetaLandingView'));
const initialProperty={inventory_id:clean(qs.get('inventory_id')||qs.get('property_id'),180),property_key:clean(qs.get('property_key')||qs.get('property'),180)};if(initialProperty.inventory_id||initialProperty.property_key)once('property:'+initialProperty.inventory_id+':'+initialProperty.property_key,()=>send('PropertyView',initialProperty));
document.addEventListener('click',ev=>{const t=ev.target instanceof Element?ev.target:null;if(!t)return;const p=t.closest('[data-inventory-id],[data-property-key],[data-property]');if(p){const x=propertyFrom(p);if(x.inventory_id||x.property_key)send('PropertyView',x)}const a=t.closest('a');const href=(a&&a.getAttribute('href')||'').toLowerCase();if(t.closest('#pwWaLaunch,.wa,[data-channel="whatsapp"]')||href.includes('wa.me')||href.includes('whatsapp'))send('WhatsAppClick');if(t.closest('#pwChatLaunch,[data-channel="chat"]'))send('ChatOpen')},{capture:true,passive:true});
let formStarted=false;const form=()=>document.getElementById('leadForm');const startForm=()=>{if(formStarted)return;formStarted=true;const f=form();const purpose=f&&f.querySelector('[name="purpose"]');const budget=f&&f.querySelector('[name="budget_range"]');const timeframe=f&&f.querySelector('[name="purchase_timeframe"]');send('FormStart',{metadata:Object.assign(metaBase(),{purpose:clean(purpose&&purpose.value,120),budget_range:clean(budget&&budget.value,120),purchase_timeframe:clean(timeframe&&timeframe.value,120)})})};
document.addEventListener('focusin',ev=>{const f=form();if(f&&f.contains(ev.target))startForm()});document.addEventListener('change',ev=>{const f=form();if(f&&f.contains(ev.target))startForm()});document.addEventListener('submit',ev=>{const f=form();if(!f||ev.target!==f)return;startForm();const val=n=>clean((f.querySelector('[name="'+n+'"]')||{}).value,120);send('FormSubmit',{metadata:Object.assign(metaBase(),{purpose:val('purpose'),budget_range:val('budget_range'),purchase_timeframe:val('purchase_timeframe')})})},true);
let turnstileToken='';
const mountTurnstile=()=>{const f=form();if(!f||document.getElementById('pwTurnstileBox'))return;const box=document.createElement('div');box.id='pwTurnstileBox';box.style.cssText='margin:12px 0;min-height:65px';const sendBtn=document.getElementById('send');(sendBtn&&sendBtn.parentNode?sendBtn.parentNode:f).insertBefore(box,sendBtn||null);const render=()=>{try{if(window.turnstile)window.turnstile.render(box,{sitekey:TURNSTILE_SITEKEY,theme:'auto',size:'flexible',callback:t=>{turnstileToken=t||''},'expired-callback':()=>{turnstileToken=''},'error-callback':()=>{turnstileToken=''}})}catch{}};if(window.turnstile)render();else{let sc=document.querySelector('script[data-pw-turnstile]');if(!sc){sc=document.createElement('script');sc.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';sc.async=true;sc.defer=true;sc.dataset.pwTurnstile='1';sc.onload=render;document.head.appendChild(sc)}else sc.addEventListener('load',render,{once:true})}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountTurnstile,{once:true});else setTimeout(mountTurnstile,0);
const originalFetch=window.fetch.bind(window);
window.fetch=async function(input,init){const url=typeof input==='string'?input:(input&&input.url)||'';try{const u0=new URL(url,location.href);if(u0.hostname===HOST&&u0.pathname==='/lead'&&init&&typeof init.body==='string'){const pb=JSON.parse(init.body);pb.turnstile_token=turnstileToken||clean(document.querySelector('[name="cf-turnstile-response"]')?.value,2048);init=Object.assign({},init,{body:JSON.stringify(pb)})}}catch{}const r=await originalFetch(input,init);try{const u=new URL(url,location.href);if(u.hostname===HOST&&u.pathname==='/lead'){const d=await r.clone().json().catch(()=>null);if(d&&typeof d==='object'){const status=String(d.status||'').toLowerCase(),score=Number(d.quality_score);if(status==='accepted')send('LeadAccepted',{metadata:Object.assign(metaBase(),{decision:'accepted',quality_score:Number.isFinite(score)?score:null})});else if(status==='rejected'||status==='challenge_required'||status==='challenge')send('LeadRejected',{metadata:Object.assign(metaBase(),{decision:status,quality_score:Number.isFinite(score)?score:null})})}}}catch{}return r};
})();