import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")!;
const S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const VERSION="v25";
const API=`https://googleads.googleapis.com/${VERSION}`;
const ALLOWED=new Set(["ads.google.accounts","ads.google.account.select","ads.google.sync","ads.google.pause","ads.google.resume","ads.google.budget","ads.google.create_campaign"]);
const HIGH_RISK=new Set(["ads.google.account.select","ads.google.pause","ads.google.resume","ads.google.budget","ads.google.create_campaign"]);
const svc=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});
const now=()=>new Date().toISOString();
const text=(v:any,n=600)=>String(v??"").trim().slice(0,n);
const customerId=(v:any)=>String(v??"").replace(/\D/g,"").slice(0,20);
const major=(v:any)=>Number(v||0)/1_000_000;
const micros=(v:any)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new Error("google_budget_must_be_positive");return Math.round(n*1_000_000)};
const localStatus=(v:any)=>{const s=String(v||"").toUpperCase();if(s==="ENABLED")return"active";if(s==="PAUSED")return"paused";if(s==="REMOVED")return"archived";return"draft"};
function json(b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}})}
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function same(a:string,b:string){if(!a||!b)return false;const[x,y]=await Promise.all([hash(a),hash(b)]);if(x.length!==y.length)return false;let r=0;for(let i=0;i<x.length;i++)r|=x.charCodeAt(i)^y.charCodeAt(i);return r===0}
async function readSecret(id:string){const{data,error}=await svc.rpc("service_read_secret",{p_secret_id:id});if(error||!data)throw new Error("secret_unavailable");return String(data)}
function sensitivePaymentData(v:any,depth=0):boolean{if(depth>4||v==null)return false;if(Array.isArray(v))return v.some(x=>sensitivePaymentData(x,depth+1));if(typeof v!=="object")return false;for(const[k,x]of Object.entries(v)){if(/(^|_)(card|card_number|pan|cvc|cvv|expiry|expiration|security_code)(_|$)/i.test(k))return true;if(sensitivePaymentData(x,depth+1))return true}return false}
function apiError(data:any,status:number){const detail=data?.error?.details?.[0]?.errors?.[0]?.message||data?.error?.message||data?.message||`HTTP ${status}`;return`google_ads_request_failed:${status}:${text(detail)}`}

Deno.serve(async req=>{
  if(req.method!=="POST")return json({error:"method_not_allowed"},405);
  const supplied=req.headers.get("x-cloudsales-worker-token")||"";
  const{data:setting}=await svc.from("internal_settings").select("secret_id").eq("setting_key","automation_worker_token").maybeSingle();
  if(!setting?.secret_id)return json({error:"worker_not_configured"},503);
  const expected=await readSecret(setting.secret_id);
  if(!(await same(supplied,expected)))return json({error:"forbidden"},403);
  let body:any;try{body=await req.json()}catch{return json({error:"invalid_json"},400)}
  const jobId=String(body.job_id||"");if(!jobId)return json({error:"job_id_required"},400);
  const{data:job}=await svc.from("automation_jobs").select("id,organization_id,job_type,status,requested_by,requires_approval,approved_by,input").eq("id",jobId).maybeSingle();
  if(!job)return json({error:"job_not_found"},404);
  if(!ALLOWED.has(String(job.job_type)))return json({error:"unsupported_google_job"},400);
  if(job.status!=="queued")return json({ok:true,status:job.status,idempotent:true});
  if(job.requires_approval&&!job.approved_by)return json({error:"approval_required"},409);
  if(HIGH_RISK.has(String(job.job_type))&&!job.approved_by)return json({error:"owner_admin_approval_required"},409);
  if(job.approved_by){const{data:approver}=await svc.from("organization_members").select("role,status").eq("organization_id",job.organization_id).eq("user_id",job.approved_by).maybeSingle();if(!approver||approver.status!=="active"||!["owner","admin"].includes(String(approver.role)))return json({error:"invalid_approver"},403)}
  const input=job.input&&typeof job.input==="object"?job.input:{};
  if(sensitivePaymentData(input))return json({error:"payment_card_data_not_allowed",billing_mode:"provider_managed"},400);
  const{data:locked}=await svc.from("automation_jobs").update({status:"running",started_at:now()}).eq("id",jobId).eq("status","queued").select("id").maybeSingle();
  if(!locked)return json({ok:true,status:"already_claimed",idempotent:true});
  const org=String(job.organization_id),action=String(job.job_type),actor=job.requested_by||job.approved_by||null;

  async function finish(status:"succeeded"|"failed",output:any,error:string|null=null){
    await svc.from("automation_jobs").update({status,output:output||null,error,finished_at:now()}).eq("id",jobId);
    await svc.from("cloudy_tool_runs").update({status,status:status==="succeeded"?"succeeded":"failed",output:output||null,error,finished_at:now()}).eq("automation_job_id",jobId).eq("organization_id",org);
    await svc.from("audit_log").insert({organization_id:org,actor_user_id:actor,actor_type:"worker",action:status==="succeeded"?"google_ads.automation.succeeded":"google_ads.automation.failed",entity_type:"automation_job",entity_id:jobId,success:status==="succeeded",context:{job_type:action,approved_by:job.approved_by||null,error}});
  }

  try{
    const{data:conn}=await svc.from("connections").select("id,status,external_account_id,external_account_name,scopes,expires_at,metadata,last_sync_at").eq("organization_id",org).eq("provider_key","google_ads").eq("status","connected").order("created_at",{ascending:false}).limit(1).maybeSingle();
    if(!conn)throw new Error("google_ads_connection_required");
    if(input.connection_id&&String(input.connection_id)!==String(conn.id))throw new Error("google_ads_connection_mismatch");
    const{data:sec}=await svc.from("connection_secrets").select("access_token_secret_id,refresh_token_secret_id").eq("connection_id",conn.id).maybeSingle();
    if(!sec?.access_token_secret_id)throw new Error("google_ads_access_token_missing");
    const[{data:cred},{data:devSetting}]=await Promise.all([svc.from("provider_app_credentials").select("client_id,client_secret_secret_id,redirect_uri,enabled").eq("provider_key","google_ads").maybeSingle(),svc.from("internal_settings").select("secret_id").eq("setting_key","google_ads_developer_token").maybeSingle()]);
    if(!cred?.enabled||!cred.client_id||!cred.client_secret_secret_id||!devSetting?.secret_id)throw new Error("google_ads_platform_not_configured");
    const developerToken=await readSecret(devSetting.secret_id);
    async function accessToken(){
      const exp=conn.expires_at?new Date(conn.expires_at).getTime():0;
      const current=await readSecret(sec.access_token_secret_id);
      if(current&&(!exp||exp>Date.now()+90_000))return current;
      if(!sec.refresh_token_secret_id)throw new Error("google_ads_refresh_token_missing");
      const[refresh,clientSecret]=await Promise.all([readSecret(sec.refresh_token_secret_id),readSecret(cred.client_secret_secret_id)]);
      const form=new URLSearchParams({client_id:String(cred.client_id),client_secret:clientSecret,refresh_token:refresh,grant_type:"refresh_token"});
      const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded",accept:"application/json"},body:form});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)throw new Error(apiError(d,r.status));
      await svc.rpc("service_update_secret",{p_secret_id:sec.access_token_secret_id,p_secret:String(d.access_token),p_name:`cloudsales/google_ads/${conn.id}/access`,p_description:"Google Ads OAuth access token"});
      const expiresAt=new Date(Date.now()+Number(d.expires_in||3600)*1000).toISOString();await svc.from("connections").update({expires_at:expiresAt,updated_at:now()}).eq("id",conn.id);conn.expires_at=expiresAt;return String(d.access_token)
    }
    async function call(path:string,method="GET",payload:any=null,loginId:string|null=null){const token=await accessToken();const h:any={Authorization:`Bearer ${token}`,"developer-token":developerToken,accept:"application/json"};if(loginId)h["login-customer-id"]=customerId(loginId);if(payload!==null)h["content-type"]="application/json";const r=await fetch(`${API}/${String(path).replace(/^\/+/,"")}`,{method,headers:h,body:payload===null?undefined:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||d?.error)throw new Error(apiError(d,r.status));return d}
    async function search(cid:string,query:string,login:string|null=null){return await call(`customers/${customerId(cid)}/googleAds:search`,"POST",{query,pageSize:10000},login)}
    async function accounts(){const a=await call("customers:listAccessibleCustomers");const ids=(a.resourceNames||[]).map((x:string)=>customerId(x)).filter(Boolean),out:any[]=[];for(const id of ids.slice(0,25)){try{const d=await search(id,"SELECT customer.id, customer.descriptive_name, customer.currency_code, customer.time_zone, customer.manager, customer.status FROM customer LIMIT 1");const c=d.results?.[0]?.customer;if(c)out.push({id:customerId(c.id||id),name:text(c.descriptiveName||`Google Ads ${id}`,200),currency:String(c.currencyCode||"USD"),timezone:text(c.timeZone,100),manager:Boolean(c.manager),status:String(c.status||""),login_customer_id:null})}catch{out.push({id,name:`Google Ads ${id}`,currency:"",timezone:"",manager:false,status:"",login_customer_id:null})}}const expanded=[...out];for(const mgr of out.filter(x=>x.manager).slice(0,10)){try{const d=await search(mgr.id,"SELECT customer_client.client_customer, customer_client.descriptive_name, customer_client.currency_code, customer_client.time_zone, customer_client.manager, customer_client.status, customer_client.level FROM customer_client WHERE customer_client.level <= 1",mgr.id);for(const r of d.results||[]){const c=r.customerClient||{},id=customerId(c.clientCustomer);if(id&&!c.manager)expanded.push({id,name:text(c.descriptiveName||`Google Ads ${id}`,200),currency:String(c.currencyCode||""),timezone:text(c.timeZone,100),manager:false,status:String(c.status||""),login_customer_id:mgr.id})}}catch{}}const map=new Map<string,any>();for(const x of expanded)if(x.id&&!map.has(x.id))map.set(x.id,x);return[...map.values()]}
    async function requireAccount(requested:any=null){const list=await accounts();let id=customerId(requested||conn.metadata?.selected_customer_id||"");if(!id){const eligible=list.filter((x:any)=>!x.manager);if(eligible.length===1)id=eligible[0].id;else throw new Error("google_ads_customer_selection_required")}const account=list.find((x:any)=>x.id===id&&!x.manager);if(!account)throw new Error("google_ads_customer_not_authorized");return{list,account}}
    async function localCampaign(id:string){const{data}=await svc.from("marketing_campaigns").select("*").eq("id",id).eq("organization_id",org).eq("provider_key","google_ads").maybeSingle();if(!data)throw new Error("google_campaign_not_found");return data}
    async function syncRow(account:any,r:any){const c=r.campaign||{},b=r.campaignBudget||{},mt=r.metrics||{},ext=String(c.id||"");if(!ext)return null;const{data:existing}=await svc.from("marketing_campaigns").select("id,metadata").eq("organization_id",org).eq("provider_key","google_ads").eq("external_campaign_id",ext).maybeSingle();const row:any={organization_id:org,provider_key:"google_ads",external_campaign_id:ext,name:text(c.name||`Google Ads ${ext}`,180),objective:text(c.advertisingChannelType,120),status:localStatus(c.status),daily_budget:major(b.amountMicros),lifetime_budget:null,currency:account.currency||"USD",spend:major(mt.costMicros),leads:0,last_sync_at:now(),updated_at:now(),metadata:{...(existing?.metadata||{}),google_customer_id:account.id,google_login_customer_id:account.login_customer_id||null,google_campaign_resource:c.resourceName||`customers/${account.id}/campaigns/${ext}`,google_campaign_budget_resource:c.campaignBudget||b.resourceName||null,google_advertising_channel_type:c.advertisingChannelType||null,google_conversions:Number(mt.conversions||0),google_all_conversions:Number(mt.allConversions||0),provider_confirmed_at:now()}};if(existing?.id){const{data,error}=await svc.from("marketing_campaigns").update(row).eq("id",existing.id).select("*").single();if(error)throw new Error("google_campaign_local_sync_failed");return data}row.qualified_leads=0;row.revenue=0;row.created_by=actor;const{data,error}=await svc.from("marketing_campaigns").insert(row).select("*").single();if(error)throw new Error("google_campaign_local_insert_failed");return data}

    let output:any;
    if(action==="ads.google.accounts"){const list=await accounts();output={connected:true,accounts:list,selected_customer_id:customerId(conn.metadata?.selected_customer_id||"")||null,api_version:VERSION}}
    else if(action==="ads.google.account.select"){const{account}=await requireAccount(input.customer_id);const metadata={...(conn.metadata||{}),selected_customer_id:account.id,selected_customer_name:account.name,selected_customer_currency:account.currency,selected_customer_timezone:account.timezone,selected_login_customer_id:account.login_customer_id||null,customer_selected_at:now()};await svc.from("connections").update({metadata,last_sync_at:now()}).eq("id",conn.id);output={selected:account}}
    else if(action==="ads.google.sync"){const{account}=await requireAccount(input.customer_id);const q="SELECT campaign.id, campaign.resource_name, campaign.name, campaign.status, campaign.advertising_channel_type, campaign.campaign_budget, campaign_budget.resource_name, campaign_budget.amount_micros, metrics.cost_micros, metrics.conversions, metrics.all_conversions FROM campaign WHERE campaign.status != 'REMOVED' AND segments.date DURING LAST_30_DAYS ORDER BY campaign.id";const d=await search(account.id,q,account.login_customer_id);const rows=[];for(const r of d.results||[]){const x=await syncRow(account,r);if(x)rows.push(x)}await svc.from("connections").update({metadata:{...(conn.metadata||{}),selected_customer_id:account.id,selected_customer_name:account.name,selected_customer_currency:account.currency,selected_customer_timezone:account.timezone,selected_login_customer_id:account.login_customer_id||null,campaigns_last_sync_at:now()},last_sync_at:now()}).eq("id",conn.id);output={account,campaigns:rows,count:rows.length,synced_at:now()}}
    else if(action==="ads.google.pause"||action==="ads.google.resume"){const local=await localCampaign(String(input.id||input.campaign_id||""));const{account}=await requireAccount(local.metadata?.google_customer_id||input.customer_id);const status=action==="ads.google.pause"?"PAUSED":"ENABLED",resource=String(local.metadata?.google_campaign_resource||`customers/${account.id}/campaigns/${local.external_campaign_id}`);await call(`customers/${account.id}/campaigns:mutate`,"POST",{operations:[{update:{resourceName:resource,status},updateMask:"status"}],responseContentType:"MUTABLE_RESOURCE"},account.login_customer_id);const d=await search(account.id,`SELECT campaign.id, campaign.resource_name, campaign.name, campaign.status, campaign.advertising_channel_type, campaign.campaign_budget, campaign_budget.resource_name, campaign_budget.amount_micros FROM campaign WHERE campaign.id = ${customerId(local.external_campaign_id)} LIMIT 1`,account.login_customer_id);if(String(d.results?.[0]?.campaign?.status||"")!==status)throw new Error("google_campaign_status_confirmation_failed");output={campaign:await syncRow(account,d.results[0]),provider_status:status,confirmed:true,confirmed_at:now()}}
    else if(action==="ads.google.budget"){const local=await localCampaign(String(input.id||input.campaign_id||""));const{account}=await requireAccount(local.metadata?.google_customer_id||input.customer_id);const resource=String(local.metadata?.google_campaign_budget_resource||"");if(!resource)throw new Error("google_campaign_budget_resource_missing");const amount=micros(input.daily_budget);await call(`customers/${account.id}/campaignBudgets:mutate`,"POST",{operations:[{update:{resourceName:resource,amountMicros:String(amount)},updateMask:"amount_micros"}],responseContentType:"MUTABLE_RESOURCE"},account.login_customer_id);const d=await search(account.id,`SELECT campaign.id, campaign.resource_name, campaign.name, campaign.status, campaign.advertising_channel_type, campaign.campaign_budget, campaign_budget.resource_name, campaign_budget.amount_micros FROM campaign WHERE campaign.id = ${customerId(local.external_campaign_id)} LIMIT 1`,account.login_customer_id);const confirmed=Number(d.results?.[0]?.campaignBudget?.amountMicros||0);if(confirmed!==amount)throw new Error("google_daily_budget_confirmation_failed");output={campaign:await syncRow(account,d.results[0]),provider:{daily_budget:major(confirmed),currency:account.currency},confirmed:true,confirmed_at:now()}}
    else if(action==="ads.google.create_campaign"){const{account}=await requireAccount(input.customer_id);const name=text(input.name,180);if(!name)throw new Error("google_campaign_name_required");const amount=micros(input.daily_budget);const b=await call(`customers/${account.id}/campaignBudgets:mutate`,"POST",{operations:[{create:{name:`${name} Budget ${Date.now()}`,amountMicros:String(amount),deliveryMethod:"STANDARD",explicitlyShared:false}}],responseContentType:"MUTABLE_RESOURCE"},account.login_customer_id);const budgetResource=String(b.results?.[0]?.resourceName||b.results?.[0]?.campaignBudget?.resourceName||"");if(!budgetResource)throw new Error("google_campaign_budget_create_failed");const c=await call(`customers/${account.id}/campaigns:mutate`,"POST",{operations:[{create:{campaignBudget:budgetResource,name,advertisingChannelType:"SEARCH",status:"PAUSED",manualCpc:{},networkSettings:{targetGoogleSearch:true,targetSearchNetwork:true,targetContentNetwork:false,targetPartnerSearchNetwork:false}}}],responseContentType:"MUTABLE_RESOURCE"},account.login_customer_id);const resource=String(c.results?.[0]?.resourceName||c.results?.[0]?.campaign?.resourceName||"");if(!resource)throw new Error("google_campaign_create_failed");const id=customerId(resource.split('/').pop());const d=await search(account.id,`SELECT campaign.id, campaign.resource_name, campaign.name, campaign.status, campaign.advertising_channel_type, campaign.campaign_budget, campaign_budget.resource_name, campaign_budget.amount_micros FROM campaign WHERE campaign.id = ${id} LIMIT 1`,account.login_customer_id);if(String(d.results?.[0]?.campaign?.status||"")!=="PAUSED")throw new Error("google_campaign_pause_confirmation_failed");output={campaign:await syncRow(account,d.results[0]),provider_campaign:{resource_name:resource,name,status:"PAUSED"},provider_budget:{resource_name:budgetResource,daily_budget:major(amount),currency:account.currency},confirmed:true}}
    await finish("succeeded",output,null);return json({ok:true,job_id:jobId,action,output});
  }catch(e){const error=text((e as Error).message,800);await finish("failed",null,error);return json({error,job_id:jobId},502)}
});
