(()=>{'use strict';
const START=Date.parse('2026-08-31T05:00:00Z'),END=Date.parse('2026-12-01T00:00:00Z');
const path=location.pathname.replace(/\/$/,'')||'/';
function patchCanonicalPricing(){
 const cards=[...document.querySelectorAll('h3')];
 for(const h of cards){
   const label=(h.textContent||'').trim().toLowerCase(),box=h.closest('article,.card,.pricing-card,.price-card,div');
   if(!box)continue;
   let usageText='';
   if(label==='basic'||label==='starter'){
     h.textContent='BASIC'; usageText='Uso variable: costo real ×1.50 (+50%)';
     const w=document.createTreeWalker(box,NodeFilter.SHOW_TEXT);let n;
     while((n=w.nextNode())){const s=n.nodeValue||'';if(/\$49\s*USD\s*\/\s*mes/i.test(s))n.nodeValue=s.replace(/\$49\s*USD\s*\/\s*mes/ig,'$47 USD / mes');if(/Elegir Basic/i.test(s))n.nodeValue=s.replace(/Elegir Basic/ig,'Elegir BASIC');if(/Elegir STARTER/i.test(s))n.nodeValue=s.replace(/Elegir STARTER/ig,'Elegir BASIC')}
   }
   if(label==='pro'){
     usageText='Uso variable: costo real ×1.35 (+35%)';
     const w=document.createTreeWalker(box,NodeFilter.SHOW_TEXT);let n;
     while((n=w.nextNode())){const s=n.nodeValue||'';if(/Todo Basic/i.test(s))n.nodeValue=s.replace(/Todo Basic/ig,'Todo BASIC');if(/Todo STARTER/i.test(s))n.nodeValue=s.replace(/Todo STARTER/ig,'Todo BASIC')}
   }
   if(label==='premium'){
     usageText='Uso variable: costo real ×1.25 (+25%)';
     const w=document.createTreeWalker(box,NodeFilter.SHOW_TEXT);let n;
     while((n=w.nextNode())){const s=n.nodeValue||'';if(/\$197\s*USD\s*\/\s*mes/i.test(s))n.nodeValue=s.replace(/\$197\s*USD\s*\/\s*mes/ig,'$147 USD / mes')}
     if(!box.querySelector('[data-cs-premium-seats]')){const d=document.createElement('div');d.dataset.csPremiumSeats='1';d.style.cssText='font-size:11px;color:#9695a7;margin:8px 0 2px';d.textContent='suscripción individual por persona · asiento extra US$47/mes';h.insertAdjacentElement('afterend',d)}
   }
   if(usageText&&!box.querySelector('[data-cs-usage-markup]')){const d=document.createElement('div');d.dataset.csUsageMarkup='1';d.style.cssText='margin:9px 0 3px;padding:8px 10px;border:1px solid #3b3140;background:#171119;border-radius:10px;font-size:10px;color:#d8c7d5;line-height:1.35';d.innerHTML=usageText+'<br><a href="/usage-pricing" style="color:#ff8fc9;text-decoration:underline">Ver Usage Pricing</a>';h.insertAdjacentElement('afterend',d)}
 }
 if(!document.querySelector('[data-cs-domain-pricing-note]')){const pricing=document.querySelector('#pricing,.plans')?.closest('section')||document.querySelector('.plans')?.parentElement;if(pricing){const n=document.createElement('div');n.dataset.csDomainPricingNote='1';n.style.cssText='margin:18px 0 0;border:1px solid #343443;background:#101018;border-radius:14px;padding:12px 14px;color:#aaa9b8;font-size:11px;line-height:1.5';n.innerHTML='<b style="color:#fff">Uso y dominios.</b> El uso medido se calcula sobre costo real aterrizado según el plan. Dominios: costo real ×2. Los costos pueden variar por país, carrier, modelo de IA, canal o proveedor. <a href="/usage-pricing" style="color:#ff8fc9;text-decoration:underline">Detalles</a>.';pricing.appendChild(n)}}
 document.documentElement.dataset.csCanonicalPricing='2026-09-01';
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patchCanonicalPricing,{once:true});else patchCanonicalPricing();
if(Date.now()<START||Date.now()>=END)return;
if(['/terms','/privacy','/domains','/usage-pricing'].includes(path))return;
const salesRoutes=new Set(['/','/cloudco','/academy','/services','/affiliate','/upsells']);if(!salesRoutes.has(path))return;
const KEY='cs_public_visitor_v1';function visitor(){let v=localStorage.getItem(KEY);if(!v){v='v_'+crypto.randomUUID().replaceAll('-','')+Date.now().toString(36);localStorage.setItem(KEY,v)}return v}
function attr(){const u=new URL(location.href);return{utm_source:u.searchParams.get('utm_source'),utm_medium:u.searchParams.get('utm_medium'),utm_campaign:u.searchParams.get('utm_campaign'),utm_content:u.searchParams.get('utm_content'),utm_term:u.searchParams.get('utm_term'),fbclid:u.searchParams.get('fbclid'),gclid:u.searchParams.get('gclid'),referrer:document.referrer}}
let opened=false,offer=null,checkout=null,armed=false;setTimeout(()=>armed=true,12000);
const css=`#csExitOverlay{position:fixed;inset:0;z-index:2147483600;background:rgba(3,3,8,.82);backdrop-filter:blur(12px);display:none;align-items:center;justify-content:center;padding:16px;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}#csExitOverlay.open{display:flex}.csExitCard{width:min(510px,100%);max-height:92vh;overflow:auto;background:linear-gradient(180deg,#14141d,#09090f);color:#f8f7fa;border:1px solid #3a3542;border-radius:28px;padding:24px;box-shadow:0 35px 120px #000c;position:relative}.csExitClose{position:absolute;right:15px;top:14px;border:0;background:#24222b;color:#fff;width:36px;height:36px;border-radius:50%;font-size:21px;cursor:pointer}.csExitLogo{height:30px;width:auto;max-width:165px}.csExitBadge{display:inline-flex;margin-top:22px;padding:7px 10px;border-radius:999px;background:#261222;color:#ff74bd;border:1px solid #57334e;font-size:10px;font-weight:950;letter-spacing:.12em}.csExitCard h2{font-size:clamp(34px,8vw,54px);line-height:.95;letter-spacing:-.06em;margin:13px 0 10px}.csExitCard h2 span{color:#ff4eac}.csExitSub{color:#bbb7c3;font-size:14px;line-height:1.5}.csTimer{font-size:50px;font-weight:950;font-variant-numeric:tabular-nums;letter-spacing:-.05em;text-align:center;margin:18px 0 4px}.csTimerNote{text-align:center;color:#8e8997;font-size:10px;margin-bottom:16px}.csFields{display:grid;gap:8px}.csInput{width:100%;background:#08080d;border:1px solid #373440;color:#fff;border-radius:13px;padding:13px 14px;font:inherit}.csConsent{display:flex;gap:8px;color:#8f8b98;font-size:10px;line-height:1.4;margin:9px 0}.csExitBuy{width:100%;border:0;border-radius:999px;padding:14px;background:linear-gradient(90deg,#ff2b9b,#8c5cff);color:#fff;font-weight:950;font-size:14px;cursor:pointer}.csExitBuy:disabled{opacity:.5}.csExitMsg{display:none;margin-top:9px;padding:10px;border-radius:10px;background:#35171c;color:#ffd4dc;font-size:11px}.csExitMsg.show{display:block}.csCheckout{display:none;margin-top:14px;min-height:420px}.csCheckout.show{display:block}.csExpired{text-align:center;color:#aaa6b1;padding:24px 0;font-size:14px}@media(max-width:560px){.csExitCard{padding:20px}.csTimer{font-size:42px}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const overlay=document.createElement('div');overlay.id='csExitOverlay';overlay.innerHTML=`<div class="csExitCard"><button class="csExitClose" type="button" aria-label="Cerrar">×</button><img class="csExitLogo" src="/cloudsales-logo-official-v2.png" alt="CloudSales"><div class="csExitBadge">OFERTA ÚNICA · 15 MINUTOS</div><h2>CloudSales <span>Pro</span><br>por US$47/mes</h2><div class="csExitSub">Obtén los beneficios del plan Pro al precio normal del plan BASIC. El precio regular de Pro es US$97/mes. Esta oportunidad se muestra una sola vez y el cronómetro no se reinicia.</div><div class="csTimer">15:00</div><div class="csTimerNote">Si la cierras o vence, esta oferta no vuelve a empezar.</div><div class="csFields"><input class="csInput" data-f="name" placeholder="Nombre completo" autocomplete="name"><input class="csInput" data-f="phone" placeholder="WhatsApp / Teléfono" autocomplete="tel"><input class="csInput" data-f="email" type="email" placeholder="Correo electrónico" autocomplete="email"></div><label class="csConsent"><input data-f="marketing" type="checkbox"><span>Acepto recibir promociones, novedades y ofertas de CloudSales. Es opcional.</span></label><button class="csExitBuy" type="button">QUIERO PRO POR US$47/MES</button><div class="csExitMsg"></div><div class="csCheckout"></div></div>`;document.body.appendChild(overlay);
const close=overlay.querySelector('.csExitClose'),btn=overlay.querySelector('.csExitBuy'),msg=overlay.querySelector('.csExitMsg'),timer=overlay.querySelector('.csTimer'),mount=overlay.querySelector('.csCheckout');close.onclick=()=>overlay.classList.remove('open');overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')overlay.classList.remove('open')});
async function requestOffer(){if(opened)return;opened=true;try{const r=await fetch('/api/promo-offer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({visitor_id:visitor(),offer_type:'cloudsales_pro_49',path,referrer:document.referrer})}),j=await r.json();if(!r.ok||!j.eligible)return;offer=j;overlay.classList.add('open');tick()}catch{}}
function tick(){if(!offer)return;const end=new Date(offer.expires_at).getTime(),s=Math.max(0,Math.floor((end-Date.now())/1000));timer.textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');if(s<=0){btn.disabled=true;btn.style.display='none';overlay.querySelector('.csFields').style.display='none';overlay.querySelector('.csConsent').style.display='none';msg.className='csExitMsg show';msg.textContent='La oferta terminó y no se reinicia.';return}setTimeout(tick,1000)}
document.addEventListener('mouseout',e=>{if(!armed||opened||e.clientY>0||e.relatedTarget)return;armed=false;requestOffer()});
let touchStarted=Date.now();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&armed&&!opened&&Date.now()-touchStarted>30000){armed=false;requestOffer()}});
btn.onclick=async()=>{if(!offer)return;const name=overlay.querySelector('[data-f="name"]').value.trim(),phone=overlay.querySelector('[data-f="phone"]').value.trim(),email=overlay.querySelector('[data-f="email"]').value.trim();if(name.length<2||phone.replace(/\D/g,'').length<8||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){msg.className='csExitMsg show';msg.textContent='Completa nombre, teléfono y email válido.';return}btn.disabled=true;btn.textContent='PREPARANDO PAGO…';try{const r=await fetch('/api/promo-checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({offer_id:offer.offer_id,name,phone,email,marketing_consent:overlay.querySelector('[data-f="marketing"]').checked,source:path==='/academy'?'academy':path==='/services'?'services':path==='/affiliate'?'affiliate':path==='/cloudco'?'cloudco':path==='/upsells'?'upsells':'cloudsales',return_path:path,attribution:attr()})}),j=await r.json();if(!r.ok)throw new Error(j.error||'checkout_failed');if(!window.Stripe){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://js.stripe.com/v3/';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}const stripe=Stripe(j.publishable_key);checkout=await stripe.initEmbeddedCheckout({clientSecret:j.client_secret});mount.classList.add('show');btn.style.display='none';overlay.querySelector('.csFields').style.display='none';overlay.querySelector('.csConsent').style.display='none';checkout.mount(mount)}catch{msg.className='csExitMsg show';msg.textContent='No pudimos abrir el checkout. Intenta nuevamente.';btn.disabled=false;btn.textContent='QUIERO PRO POR US$47/MES'}};
})();