import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")!,A=Deno.env.get("SUPABASE_ANON_KEY")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BASE="https://services.leadconnectorhq.com",TOKEN_URL=`${BASE}/oauth/token`;
const ORIGINS=new Set(["https://cloudsales.app","https://www.cloudsales.app","https://app.cloudsales.app","http://localhost:3000","http://localhost:5173"]);
const ED='MCowBQYDK2VwAyEAi2HR1srL4o18O8BRa7gVJY7G7bupbN3H9AwJrHCDiOg=';
const RSA='MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAokvo/r9tVgcfZ5DysOSCFrm602qYV0MaAiNnX9O8KxMbiyRKWeL9JpCpVpt4XHIcBOK4u3cLSqJGOLaPuXw6dO0t6Q/ZVdAV5Phz+ZtzPL16iCGeK9po6D6JHBpbi989mmzMryUnQJezlYJ3DVfBcsedpinheNnyYeFXolrJvcsjDtfAeRx5ByHQmTnSdFUzuAnC9/GepgLT9SM4nCpvuxmZMxrJt5Rw+VUaQ9B8JSvbMPpez4peKaJPZHBbU3OdeCVx5klVXXZQGNHOs8gF3kvoV5rTnXV0IknLBXlcKKAQLZcY/Q9rG6Ifi9c+5vqlvHPCUJFT5XUGG5RKgOKUJ062fRtN+rLYZUV+BjafxQauvC8wSWeYja63VSUruvmNj8xkx2zE/Juc+yjLjTXpIocmaiFeAO6fUtNjDeFVkhf5LNb59vECyrHD2SQIrhgXpO4Q3dVNA5rw576PwTzNh/AMfHKIjE4xQA1SZuYJmNnmVZLIZBlQAF9Ntd03rfadZ+yDiOXCCs9FkHibELhCHULgCsnuDJHcrGNd5/Ddm5hxGQ0ASitgHeMZ0kcIOwKDOzOU53lDza6/Y09T7sYJPQe7z0cvj7aE4B+Ax1ZoZGPzpJlZtGXCsu9aTEGEnKzmsFqwcSsnw3JB31IGKAykT1hhTiaCeIY/OwwwNUY2yvcCAwEAAQ==';
const svc=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});
function cors(o:string|null){const v=o&&ORIGINS.has(o)?o:"https://app.cloudsales.app";return{"Access-Control-Allow-Origin":v,"Access-Control-Allow-Headers":"authorization,content-type,apikey,x-client-info","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Vary":"Origin"}}
function json(b:unknown,s=200,o:string|null=null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"content-type":"application/json;charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}})}
function randomUrl(n=48){const b=new Uint8Array(n);crypto.getRandomValues(b);let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
const b64=(s:string)=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};
async function verifyWebhook(raw:string,req:Request){const ed=req.headers.get('x-ghl-signature'),legacy=req.headers.get('x-wh-signature'),data=new TextEncoder().encode(raw);try{if(ed&&ed!=='N/A'){const key=await crypto.subtle.importKey('spki',b64(ED),{name:'Ed25519'},false,['verify']);return await crypto.subtle.verify({name:'Ed25519'},key,b64(ed),data)}if(legacy&&legacy!=='N/A'){const key=await crypto.subtle.importKey('spki',b64(RSA),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);return await crypto.subtle.verify({name:'RSASSA-PKCS1-v1_5'},key,b64(legacy),data)}return false}catch{return false}}
function clean(v:any,n=320){const x=String(v??'').trim();return x?x.slice(0,n):null}
function installKey(p:any){const l=clean(p.locationId),c=clean(p.companyId);return l?`location:${l}`:c?`company:${c}`:null}
function slug(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,55)||'cloudsales'}
function reqIp(req:Request){return (req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')||'unknown').split(',')[0].trim().slice(0,80)}
async function userFrom(req:Request){const auth=req.headers.get('authorization');if(!auth)return{auth:null,user:null};const uc=createClient(U,A,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const{data}=await uc.auth.getUser();return{auth,user:data.user||null}}
async function credentials(){const{data:c}=await svc.from('provider_app_credentials').select('client_id,client_secret_secret_id,redirect_uri,enabled,metadata').eq('provider_key','highlevel').maybeSingle();if(!c?.enabled||!c.client_id||!c.client_secret_secret_id||!c.redirect_uri)throw new Error('provider_not_configured');const{data:s}=await svc.rpc('service_read_secret',{p_secret_id:c.client_secret_secret_id});if(!s)throw new Error('provider_secret_unavailable');return{c,secret:String(s)}}

async function marketplaceIntake(req:Request,b:any,o:string|null){
  if(o&&!ORIGINS.has(o))return json({error:'origin_not_allowed'},403,o);
  const{data:allowed}=await svc.rpc('consume_rate_limit',{p_bucket_key:`hl-marketplace-intake:${reqIp(req)}`,p_limit:12,p_window_seconds:3600});if(allowed!==true)return json({error:'rate_limited'},429,o);
  const code=String(b.code||'').trim(),userType=String(b.user_type||b.userType||'Location').toLowerCase()==='company'?'Company':'Location';if(!code||code.length>2048)return json({error:'invalid_oauth_code'},400,o);
  let cfg:any;try{cfg=await credentials()}catch(e){return json({error:String((e as Error).message)},503,o)}
  const form=new URLSearchParams({client_id:String(cfg.c.client_id),client_secret:cfg.secret,grant_type:'authorization_code',code,user_type:userType,redirect_uri:String(cfg.c.redirect_uri)});let t:any={};
  try{const r=await fetch(TOKEN_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',accept:'application/json',Version:'v3'},body:form});t=await r.json().catch(()=>({}));if(!r.ok||!t.access_token)return json({error:'highlevel_oauth_exchange_failed',status:r.status},502,o)}catch{return json({error:'highlevel_oauth_provider_unreachable'},502,o)}
  const locationId=clean(t.locationId),companyId=clean(t.companyId),hlUserId=clean(t.userId),actualType=locationId?'Location':'Company';if(!locationId&&!companyId)return json({error:'highlevel_account_identifier_missing'},502,o);
  const key=locationId?`location:${locationId}`:`company:${companyId}`,scopes=String(t.scope||'').split(/\s+/).filter(Boolean),tokenExpiresAt=new Date(Date.now()+Math.max(60,Number(t.expires_in||86400))*1000).toISOString(),claimToken=randomUrl(),claimHash=await sha(claimToken),claimExpiresAt=new Date(Date.now()+86400000).toISOString();
  const{data:old}=await svc.from('highlevel_marketplace_installations').select('id,access_token_secret_id,refresh_token_secret_id,metadata').eq('installation_key',key).maybeSingle();let accessId=old?.access_token_secret_id,refreshId=old?.refresh_token_secret_id;
  if(accessId)await svc.rpc('service_update_secret',{p_secret_id:accessId,p_secret:String(t.access_token),p_name:`cloudsales/highlevel/marketplace/${key}/access`,p_description:'HighLevel Marketplace OAuth access token'});else{const{data:id}=await svc.rpc('service_store_secret',{p_secret:String(t.access_token),p_name:`cloudsales/highlevel/marketplace/${key}/access`,p_description:'HighLevel Marketplace OAuth access token'});accessId=id}
  if(t.refresh_token){if(refreshId)await svc.rpc('service_update_secret',{p_secret_id:refreshId,p_secret:String(t.refresh_token),p_name:`cloudsales/highlevel/marketplace/${key}/refresh`,p_description:'HighLevel Marketplace OAuth refresh token'});else{const{data:id}=await svc.rpc('service_store_secret',{p_secret:String(t.refresh_token),p_name:`cloudsales/highlevel/marketplace/${key}/refresh`,p_description:'HighLevel Marketplace OAuth refresh token'});refreshId=id}}
  if(!accessId)return json({error:'highlevel_token_storage_failed'},500,o);
  let accountName:string|null=null,accountEmail:string|null=null;if(locationId&&scopes.includes('locations.readonly'))try{const r=await fetch(`${BASE}/locations/${encodeURIComponent(locationId)}`,{headers:{Authorization:`Bearer ${t.access_token}`,Accept:'application/json',Version:'2021-07-28'}});if(r.ok){const j=await r.json(),x=j.location||j;accountName=clean(x.name,120);accountEmail=clean(x.email,320)}}catch{}
  const row={installation_key:key,app_id:clean(b.app_id||b.appId),version_id:clean(b.version_id||b.versionId||cfg.c.metadata?.version_id),location_id:locationId,company_id:companyId,highlevel_user_id:hlUserId,install_type:actualType,status:'pending_claim',claim_token_hash:claimHash,claim_expires_at:claimExpiresAt,access_token_secret_id:accessId,refresh_token_secret_id:refreshId||null,token_expires_at:tokenExpiresAt,scopes,installed_at:new Date().toISOString(),uninstalled_at:null,last_event_at:new Date().toISOString(),metadata:{...(old?.metadata||{}),oauth_source:'highlevel_marketplace',token_type:t.token_type||'Bearer',is_bulk_installation:Boolean(t.isBulkInstallation),account_name:accountName,account_email:accountEmail,intake_at:new Date().toISOString()}};
  let id='';if(old?.id){id=old.id;const{error}=await svc.from('highlevel_marketplace_installations').update({...row,updated_at:new Date().toISOString()}).eq('id',id);if(error)return json({error:'marketplace_installation_update_failed'},500,o)}else{const{data:c,error}=await svc.from('highlevel_marketplace_installations').insert(row).select('id').single();if(error||!c)return json({error:'marketplace_installation_create_failed'},500,o);id=c.id}
  await svc.from('audit_log').insert({actor_type:'system',action:'highlevel.marketplace.oauth_received',entity_type:'highlevel_marketplace_installation',entity_id:id,success:true,context:{location_id:locationId,company_id:companyId,scopes_count:scopes.length}});
  return json({claim_token:claimToken,claim_expires_at:claimExpiresAt,installation:{id,install_type:actualType,account_name:accountName,location_id:locationId,company_id:companyId,scopes},next_action:'sign_in_or_create_cloudsales_account'},200,o);
}

async function marketplaceClaim(req:Request,b:any,o:string|null){
  if(o&&!ORIGINS.has(o))return json({error:'origin_not_allowed'},403,o);const{auth,user}=await userFrom(req);if(!auth)return json({error:'missing_authorization'},401,o);if(!user)return json({error:'invalid_session'},401,o);
  const token=String(b.claim_token||b.token||'').trim();if(token.length<32||token.length>512)return json({error:'invalid_claim_token'},400,o);const{data:allowed}=await svc.rpc('consume_rate_limit',{p_bucket_key:`hl-marketplace-claim:${user.id}`,p_limit:12,p_window_seconds:3600});if(allowed!==true)return json({error:'rate_limited'},429,o);
  const hash=await sha(token),{data:i}=await svc.from('highlevel_marketplace_installations').select('*').eq('claim_token_hash',hash).maybeSingle();if(!i||!['pending_claim','webhook_seen','updated'].includes(String(i.status)))return json({error:'claim_invalid_or_used'},409,o);if(!i.claim_expires_at||new Date(i.claim_expires_at).getTime()<=Date.now())return json({error:'claim_expired'},410,o);if(!i.access_token_secret_id)return json({error:'installation_token_missing'},409,o);
  let org=String(b.organization_id||'').trim();if(org){const{data:m}=await svc.from('organization_members').select('role,status').eq('organization_id',org).eq('user_id',user.id).maybeSingle();if(!m||m.status!=='active'||!['owner','admin'].includes(String(m.role)))return json({error:'forbidden'},403,o)}else{const{data:mm}=await svc.from('organization_members').select('organization_id,role,status,created_at').eq('user_id',user.id).eq('status','active').in('role',['owner','admin']).order('created_at',{ascending:true}).limit(1);org=String(mm?.[0]?.organization_id||'')}
  if(!org){const name=String(i.metadata?.account_name||i.metadata?.company_name||'CloudSales Workspace').trim().slice(0,120),base=slug(name),suffix=String(i.id).replace(/-/g,'').slice(0,6);let s=base;const{data:x}=await svc.from('organizations').select('id').eq('slug',s).maybeSingle();if(x)s=`${base}-${suffix}`.slice(0,63);const{data:n,error:e}=await svc.from('organizations').insert({name,slug:s,status:'active',plan_key:'basic',created_by:user.id,timezone:'America/Cancun'}).select('id').single();if(e||!n)return json({error:'organization_create_failed'},500,o);const{error:me}=await svc.from('organization_members').insert({organization_id:n.id,user_id:user.id,role:'owner',status:'active'});if(me){await svc.from('organizations').delete().eq('id',n.id);return json({error:'membership_create_failed'},500,o)}org=n.id}
  const externalId=String(i.location_id||i.company_id||'');if(!externalId)return json({error:'installation_account_missing'},409,o);const scopes=Array.isArray(i.scopes)?i.scopes:[],required=['contacts.readonly','contacts.write','opportunities.readonly','opportunities.write','calendars.readonly','calendars/events.write','conversations.readonly','conversations/message.write','locations.readonly'],missing=required.filter((x:string)=>!scopes.includes(x));
  const metadata={auth_mode:'marketplace_oauth',marketplace_installation_id:i.id,app_id:i.app_id||null,version_id:i.version_id||null,user_type:i.install_type,company_id:i.company_id||null,location_id:i.location_id||null,highlevel_user_id:i.highlevel_user_id||null,marketplace_first:true,permissions_complete:missing.length===0,missing_core_scopes:missing,connected_at:new Date().toISOString()};
  let connectionId='';const{data:old}=await svc.from('connections').select('id').eq('organization_id',org).eq('provider_key','highlevel').eq('external_account_id',externalId).maybeSingle();if(old?.id){connectionId=old.id;const{error}=await svc.from('connections').update({status:'connected',scopes,expires_at:i.token_expires_at,last_sync_at:new Date().toISOString(),metadata}).eq('id',connectionId);if(error)return json({error:'connection_update_failed'},500,o)}else{const{data:c,error}=await svc.from('connections').insert({organization_id:org,provider_key:'highlevel',status:'connected',external_account_id:externalId,external_account_name:String(i.metadata?.account_name||'HighLevel'),scopes,expires_at:i.token_expires_at,last_sync_at:new Date().toISOString(),created_by:user.id,metadata}).select('id').single();if(error||!c)return json({error:'connection_create_failed'},500,o);connectionId=c.id}
  await svc.from('connection_secrets').upsert({connection_id:connectionId,access_token_secret_id:i.access_token_secret_id,refresh_token_secret_id:i.refresh_token_secret_id||null,rotated_at:new Date().toISOString()},{onConflict:'connection_id'});await svc.from('highlevel_marketplace_installations').update({status:'connected',organization_id:org,connection_id:connectionId,claimed_by_user_id:user.id,claimed_at:new Date().toISOString(),claim_token_hash:null,updated_at:new Date().toISOString(),last_event_at:new Date().toISOString()}).eq('id',i.id);await svc.from('audit_log').insert({organization_id:org,actor_user_id:user.id,actor_type:'user',action:'highlevel.marketplace.claimed',entity_type:'connection',entity_id:connectionId,connection_id:connectionId,success:true,context:{location_id:i.location_id,company_id:i.company_id,scopes_count:scopes.length,missing_core_scopes:missing}});
  return json({organization_id:org,connection:{id:connectionId,status:'connected',external_account_id:externalId,scopes},permissions:{complete:missing.length===0,missing_core_scopes:missing},marketplace_installation_id:i.id},200,o);
}

async function lifecycleWebhook(req:Request,raw:string){
  if(raw.length>1048576)return json({error:'payload_too_large'},413);if(!await verifyWebhook(raw,req))return json({error:'invalid_signature'},401);let p:any={};try{p=JSON.parse(raw)}catch{return json({error:'invalid_json'},400)}const type=String(p.type||''),upper=type.toUpperCase(),key=installKey(p),now=new Date().toISOString(),webhookId=clean(p.webhookId)||await sha(raw);
  if(['INSTALL','APPINSTALL'].includes(upper)){if(!key)return json({error:'installation_identifier_missing'},400);const row={installation_key:key,app_id:clean(p.appId),version_id:clean(p.versionId),location_id:clean(p.locationId),company_id:clean(p.companyId),highlevel_user_id:clean(p.userId),install_type:p.locationId?'Location':'Company',installed_at:now,last_event_at:now,metadata:{install_webhook_id:webhookId,company_name:clean(p.companyName),plan_id:clean(p.planId),trial:p.trial||null,is_whitelabel_company:Boolean(p.isWhitelabelCompany),whitelabel_details:p.whitelabelDetails||{},install_webhook_at:now}};const{data:old}=await svc.from('highlevel_marketplace_installations').select('id,status,metadata').eq('installation_key',key).maybeSingle();if(old?.id)await svc.from('highlevel_marketplace_installations').update({...row,status:old.status==='connected'?'connected':'webhook_seen',metadata:{...(old.metadata||{}),...row.metadata},updated_at:now}).eq('id',old.id);else await svc.from('highlevel_marketplace_installations').insert({...row,status:'webhook_seen'});return json({ok:true,event:'INSTALL'})}
  if(['UNINSTALL','APPUNINSTALL'].includes(upper)){if(!key)return json({error:'installation_identifier_missing'},400);const{data:i}=await svc.from('highlevel_marketplace_installations').select('*').eq('installation_key',key).maybeSingle();if(i?.id){await svc.from('highlevel_marketplace_installations').update({status:'uninstalled',uninstalled_at:now,claim_token_hash:null,last_event_at:now,updated_at:now,metadata:{...(i.metadata||{}),uninstall_webhook_id:webhookId,uninstall_webhook_at:now}}).eq('id',i.id);if(i.connection_id){const{data:c}=await svc.from('connections').select('metadata').eq('id',i.connection_id).maybeSingle();await svc.from('connections').update({status:'revoked',metadata:{...(c?.metadata||{}),marketplace_uninstalled_at:now}}).eq('id',i.connection_id)}for(const[id,name]of[[i.access_token_secret_id,'access'],[i.refresh_token_secret_id,'refresh']]as any[]){if(id)await svc.rpc('service_update_secret',{p_secret_id:id,p_secret:`revoked:${crypto.randomUUID()}`,p_name:`cloudsales/highlevel/marketplace/${key}/${name}`,p_description:`Revoked HighLevel Marketplace ${name} token`})}}return json({ok:true,event:'UNINSTALL'})}
  if(['UPDATE','APPUPDATE'].includes(upper)){if(key){const{data:i}=await svc.from('highlevel_marketplace_installations').select('id,status,metadata').eq('installation_key',key).maybeSingle();if(i?.id)await svc.from('highlevel_marketplace_installations').update({status:i.status==='connected'?'connected':'updated',version_id:clean(p.versionId),last_event_at:now,updated_at:now,metadata:{...(i.metadata||{}),previous_version_id:clean(p.previousVersionId),update_webhook_id:webhookId,update_webhook_at:now}}).eq('id',i.id)}return json({ok:true,event:'UPDATE'})}
  const locationId=clean(p.locationId||p.data?.locationId||p.location?.id),{data:c}=locationId?await svc.from('connections').select('id,organization_id').eq('provider_key','highlevel').eq('external_account_id',locationId).eq('status','connected').limit(1).maybeSingle():{data:null as any};const{error}=await svc.from('webhook_events').insert({organization_id:c?.organization_id||null,provider_key:'highlevel',external_event_id:webhookId,status:'received',payload:p});if(error&&String(error.code)!=='23505')return json({error:'persist_failed'},500);return json({ok:true,event:type||'unknown',status:'received'});
}

async function normalPrivateConnect(req:Request,b:any,o:string|null){
  if(o&&!ORIGINS.has(o))return json({error:'origin_not_allowed'},403,o);const{auth,user}=await userFrom(req);if(!auth)return json({error:'missing_authorization'},401,o);if(!user)return json({error:'invalid_session'},401,o);const{data:members}=await svc.from('organization_members').select('organization_id,role,status').eq('user_id',user.id).eq('status','active');const organizationId=String(b.organization_id||'').trim(),locationId=String(b.location_id||'').trim(),token=String(b.token||'').trim();if(!organizationId||!locationId||!token)return json({error:'organization_location_token_required'},400,o);if(!/^[A-Za-z0-9_-]{8,80}$/.test(locationId)||token.length<20||token.length>10000)return json({error:'invalid_highlevel_credentials'},400,o);const member=(members||[]).find((m:any)=>m.organization_id===organizationId&&['owner','admin','operator'].includes(m.role));if(!member)return json({error:'forbidden'},403,o);const{data:allowed}=await svc.rpc('consume_rate_limit',{p_bucket_key:`highlevel-private-connect:${user.id}:${reqIp(req)}`,p_limit:10,p_window_seconds:900});if(allowed!==true)return json({error:'rate_limited'},429,o);
  const r=await fetch(`${BASE}/locations/${encodeURIComponent(locationId)}`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json',Version:'v3'}}),raw=await r.text();let d:any={};try{d=JSON.parse(raw)}catch{}if(!r.ok||!d?.location?.id||String(d.location.id)!==locationId)return json({error:'highlevel_token_validation_failed',provider_status:r.status},422,o);const loc=d.location;let permissions:string[]=[];try{const pr=await fetch(`${BASE}/locations/${encodeURIComponent(locationId)}/permissions`,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json',Version:'v3'}});if(pr.ok){const pd=await pr.json();permissions=Array.isArray(pd?.permissions)?pd.permissions.map(String):[]}}catch{}
  const{data:existing}=await svc.from('connections').select('id,metadata').eq('organization_id',organizationId).eq('provider_key','highlevel').eq('external_account_id',locationId).maybeSingle();let connection:any;const metadata={...(existing?.metadata||{}),auth_mode:'private_integration',location_id:locationId,company_id:loc.companyId||null,user_type:'Location',connected_at:new Date().toISOString(),token_rotation_recommended_days:90,location_permissions:permissions};if(existing?.id){const{data:c,error}=await svc.from('connections').update({status:'connected',external_account_name:String(loc.name||'HighLevel'),expires_at:null,last_sync_at:new Date().toISOString(),metadata}).eq('id',existing.id).select('id,organization_id,provider_key,status,external_account_id,external_account_name,metadata').single();if(error)return json({error:'connection_update_failed'},500,o);connection=c}else{const{data:c,error}=await svc.from('connections').insert({organization_id:organizationId,provider_key:'highlevel',status:'connected',external_account_id:locationId,external_account_name:String(loc.name||'HighLevel'),expires_at:null,last_sync_at:new Date().toISOString(),metadata,created_by:user.id}).select('id,organization_id,provider_key,status,external_account_id,external_account_name,metadata').single();if(error||!c)return json({error:'connection_create_failed'},500,o);connection=c}
  const{data:sec}=await svc.from('connection_secrets').select('access_token_secret_id').eq('connection_id',connection.id).maybeSingle();let secretId=sec?.access_token_secret_id;if(secretId)await svc.rpc('service_update_secret',{p_secret_id:secretId,p_secret:token,p_name:`cloudsales/highlevel/${connection.id}/private`,p_description:'HighLevel Private Integration token'});else{const{data:id,error}=await svc.rpc('service_store_secret',{p_secret:token,p_name:`cloudsales/highlevel/${connection.id}/private`,p_description:'HighLevel Private Integration token'});if(error||!id)return json({error:'secret_store_failed'},500,o);secretId=id}await svc.from('connection_secrets').upsert({connection_id:connection.id,access_token_secret_id:secretId,refresh_token_secret_id:null,rotated_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'connection_id'});await svc.from('audit_log').insert({organization_id:organizationId,actor_user_id:user.id,actor_type:'user',action:'highlevel.private_integration.connected',entity_type:'connection',entity_id:connection.id,connection_id:connection.id,success:true,context:{location_id:locationId,location_name:loc.name||null,company_id:loc.companyId||null,token_stored_in_vault:true}});return json({ok:true,connection:{id:connection.id,status:'connected',provider_key:'highlevel',location_id:locationId,location_name:loc.name||null,company_id:loc.companyId||null,auth_mode:'private_integration',token_stored_in_vault:true,permissions}},200,o);
}

Deno.serve(async req=>{
  const o=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(o)});
  if(req.headers.get('x-ghl-signature')||req.headers.get('x-wh-signature')){if(req.method!=='POST')return json({error:'method_not_allowed'},405,o);return lifecycleWebhook(req,await req.text())}
  if(req.method==='GET'){const{auth,user}=await userFrom(req);if(!auth||!user)return json({ok:true,service:'cloudsales-highlevel-connect',marketplace_lifecycle:true,revision:'2026-08-31'},200,o);const{data:mm}=await svc.from('organization_members').select('organization_id,role,status').eq('user_id',user.id).eq('status','active');const ids=(mm||[]).filter((m:any)=>['owner','admin','operator'].includes(m.role)).map((m:any)=>m.organization_id);if(!ids.length)return json({organizations:[],connections:[]},200,o);const[{data:orgs},{data:conns}]=await Promise.all([svc.from('organizations').select('id,name,slug,status,plan_key').in('id',ids).eq('status','active').order('name'),svc.from('connections').select('id,organization_id,provider_key,status,external_account_id,external_account_name,metadata,last_sync_at').in('organization_id',ids).eq('provider_key','highlevel')]);return json({organizations:orgs||[],connections:conns||[]},200,o)}
  if(req.method!=='POST')return json({error:'method_not_allowed'},405,o);let b:any={};try{b=await req.json()}catch{return json({error:'invalid_json'},400,o)}const action=String(b.action||'');if(action==='marketplace_intake')return marketplaceIntake(req,b,o);if(action==='marketplace_claim')return marketplaceClaim(req,b,o);return normalPrivateConnect(req,b,o);
});