import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")!,A=Deno.env.get("SUPABASE_ANON_KEY")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ORIGINS=new Set(["https://cloudsales.app","https://www.cloudsales.app","https://app.cloudsales.app","http://localhost:3000","http://localhost:5173"]);
function cors(o:string|null){const v=o&&ORIGINS.has(o)?o:"https://app.cloudsales.app";return{"Access-Control-Allow-Origin":v,"Access-Control-Allow-Headers":"authorization,apikey,content-type,x-client-info","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
function json(b:unknown,s=200,o:string|null=null){return new Response(JSON.stringify(b),{status:s,headers:{...cors(o),"content-type":"application/json;charset=utf-8","cache-control":"no-store"}})}
function freshBase(raw:string){let v=raw.trim();if(!/^https?:\/\//i.test(v))v=`https://${v}`;const u=new URL(v);if(u.protocol!=="https:")throw new Error("https_required");const h=u.hostname.toLowerCase();if(!(h.endsWith(".myfreshworks.com")||h.endsWith(".freshworks.com")))throw new Error("invalid_freshsales_domain");let p=u.pathname.replace(/\/$/,"");if(!p||p==="/")p="/crm/sales";if(!p.startsWith("/crm/sales"))throw new Error("invalid_freshsales_path");return `${u.origin}${p}`}
function normalizePhone(v:unknown){const raw=String(v??"").trim();if(!raw)return"";if(raw.startsWith("+"))return`+${raw.slice(1).replace(/\D/g,"")}`;const d=raw.replace(/\D/g,"");return d?`+${d}`:""}
function endpointPhone(v:any){if(typeof v==="string")return normalizePhone(v);if(v&&typeof v==="object")return normalizePhone(v.phone_number??v.phoneNumber??v.number);return""}
function decodeBase64(v:string){const n=v.trim().replace(/-/g,"+").replace(/_/g,"/");const p=n.padEnd(Math.ceil(n.length/4)*4,"=");const r=atob(p);return Uint8Array.from(r,c=>c.charCodeAt(0))}
function publicKeyBytes(v:string){let x=v.trim();if(x.includes("BEGIN PUBLIC KEY"))x=x.replace(/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----|\s+/g,"");if(/^[0-9a-fA-F]{64}$/.test(x))return Uint8Array.from(x.match(/../g)!.map(h=>parseInt(h,16)));const decoded=decodeBase64(x);if(decoded.length===44&&decoded[0]===0x30)return decoded.slice(-32);return decoded}
async function verifyTelnyxWebhook(raw:string,sig:string|null,ts:string|null,keyText:string){if(!sig||!ts||!keyText)return false;const n=Number(ts);if(!Number.isFinite(n)||Math.abs(Math.floor(Date.now()/1000)-n)>300)return false;try{const kb=publicKeyBytes(keyText);if(kb.length!==32)return false;const key=await crypto.subtle.importKey("raw",kb,{name:"Ed25519"},false,["verify"]);return await crypto.subtle.verify({name:"Ed25519"},key,decodeBase64(sig),new TextEncoder().encode(`${ts}|${raw}`))}catch{return false}}
async function telnyxFetch(apiKey:string,path:string,init:RequestInit={}){const r=await fetch(`https://api.telnyx.com/v2${path}`,{...init,headers:{Authorization:`Bearer ${apiKey}`,Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(init.headers||{})}});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{}return{ok:r.ok,status:r.status,text,data}}
async function fingerprint(secret:string){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(secret));return[...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,"0")).join("").slice(0,16)}
function telnyxFacts(e:any){const d=e?.data||{},p=d.payload||{},type=String(p.type||p.channel||"").toLowerCase(),channel=type.includes("whatsapp")?"whatsapp":"sms",direction=String(p.direction||"").toLowerCase();const from=endpointPhone(p.from),to=endpointPhone(Array.isArray(p.to)?p.to[0]:p.to),own=direction==="inbound"?to:from,remote=direction==="inbound"?from:to;const status=String((Array.isArray(p.to)&&p.to[0]?.status)||p.status||"");return{eventId:String(d.id||""),eventType:String(d.event_type||"unknown"),occurredAt:String(d.occurred_at||new Date().toISOString()),payload:p,channel,direction,own,remote,messageId:String(p.id||""),text:String(p.text||p.body||p.whatsapp_message?.text?.body||""),media:Array.isArray(p.media)?p.media:[],status}}
function normalizedJobStatus(eventType:string,providerStatus:string){const e=eventType.toLowerCase(),s=providerStatus.toLowerCase();if(e==="message.sent")return"sent";if(e==="message.delivered"||e==="message.finalized"&&["delivered","delivery_success","sent"].includes(s))return"delivered";if(e==="message.read")return"read";if(e==="message.failed"||e==="message.finalized"&&["delivery_failed","failed","undelivered","rejected"].includes(s))return"failed";return null}
async function handleTelnyxWebhook(req:Request,raw:string,svc:any){
  let envelope:any;try{envelope=JSON.parse(raw)}catch{return json({error:"invalid_json"},400)}
  const f=telnyxFacts(envelope);if(!f.eventId||!f.messageId||!f.own)return json({error:"invalid_telnyx_event"},400);
  let org:string|null=null,connectionId:string|null=null,contactId:string|null=null;
  if(f.direction==="outbound"){const {data:j}=await svc.from("communications_engine_jobs").select("organization_id,connection_id,contact_id").eq("provider_key","telnyx").eq("provider_message_id",f.messageId).limit(1).maybeSingle();if(j){org=j.organization_id;connectionId=j.connection_id;contactId=j.contact_id}}
  if(!connectionId){const {data:b}=await svc.from("channel_provider_bindings").select("organization_id,connection_id").eq("provider_key","telnyx").eq("channel",f.channel).eq("provider_channel_id",f.own).neq("status","disabled").limit(1).maybeSingle();if(b){org=b.organization_id;connectionId=b.connection_id}}
  if(!org||!connectionId)return json({error:"unmapped_telnyx_sender"},404);
  const {data:sec}=await svc.from("connection_secrets").select("webhook_secret_secret_id").eq("connection_id",connectionId).maybeSingle();if(!sec?.webhook_secret_secret_id)return json({error:"webhook_public_key_not_configured"},503);
  const {data:pk}=await svc.rpc("service_read_secret",{p_secret_id:sec.webhook_secret_secret_id});if(!pk)return json({error:"webhook_public_key_unavailable"},503);
  if(!(await verifyTelnyxWebhook(raw,req.headers.get("telnyx-signature-ed25519"),req.headers.get("telnyx-timestamp"),String(pk)))){await svc.from("audit_log").insert({organization_id:org,actor_type:"system",action:"communications.telnyx.webhook_signature_failed",entity_type:"connection",entity_id:connectionId,connection_id:connectionId,success:false,context:{event_id:f.eventId,event_type:f.eventType}}).catch(()=>{});return json({error:"invalid_signature"},403)}
  const {data:dupe}=await svc.from("communications_engine_events").select("id").eq("provider_key","telnyx").eq("provider_event_id",f.eventId).maybeSingle();if(dupe)return json({ok:true,duplicate:true},200);
  if(!contactId&&f.remote){const {data:c}=await svc.from("contacts").select("id").eq("organization_id",org).eq("phone_e164",f.remote).limit(1).maybeSingle();contactId=c?.id||null}
  const {data:event,error:ee}=await svc.from("communications_engine_events").insert({organization_id:org,provider_key:"telnyx",channel:f.channel,provider_event_id:f.eventId,provider_message_id:f.messageId,event_type:f.eventType,occurred_at:f.occurredAt,payload:f.payload}).select("id").single();if(ee){if(String(ee.code)==="23505")return json({ok:true,duplicate:true},200);return json({error:"event_persist_failed"},500)}
  const status=normalizedJobStatus(f.eventType,f.status);
  const {data:job}=await svc.from("communications_engine_jobs").select("id,contact_id").eq("provider_key","telnyx").eq("provider_message_id",f.messageId).limit(1).maybeSingle();
  if(job){const patch:any={};if(status)patch.status=status;if(status==="delivered")patch.delivered_at=f.occurredAt;if(status==="read")patch.read_at=f.occurredAt;if(status==="failed")patch.last_error=`telnyx_delivery_failed:${f.status}`;if(Object.keys(patch).length)await svc.from("communications_engine_jobs").update(patch).eq("id",job.id);await svc.from("communications_engine_events").update({job_id:job.id}).eq("id",event.id);if(!contactId&&job.contact_id)contactId=job.contact_id}
  const external=`${f.channel}:${f.own}:${f.remote}`,preview=f.text.slice(0,300);
  const {data:conv}=await svc.from("universal_conversations").upsert({organization_id:org,contact_id:contactId,source_provider:"telnyx",external_conversation_id:external,primary_channel:f.channel,status:"open",last_message_at:f.occurredAt,last_message_preview:preview,metadata:{connection_id:connectionId,sender:f.own}},{onConflict:"organization_id,source_provider,external_conversation_id"}).select("id,unread_count").single();
  if(conv?.id){await svc.from("universal_messages").upsert({organization_id:org,conversation_id:conv.id,contact_id:contactId,source_provider:"telnyx",external_message_id:f.messageId,direction:f.direction==="inbound"?"inbound":"outbound",channel:f.channel,message_type:String(f.payload.type||"text").toLowerCase(),body:f.text||null,attachments:f.media,status:status||f.status||null,sender_identifier:f.direction==="inbound"?f.remote:f.own,recipient_identifier:f.direction==="inbound"?f.own:f.remote,occurred_at:f.occurredAt,metadata:{provider_event_id:f.eventId,connection_id:connectionId}},{onConflict:"organization_id,source_provider,external_message_id"});if(f.direction==="inbound")await svc.from("universal_conversations").update({unread_count:Number(conv.unread_count||0)+1,last_message_at:f.occurredAt,last_message_preview:preview}).eq("id",conv.id)}
  if(f.direction==="inbound"&&f.channel==="sms"){const kw=f.text.trim().toUpperCase(),phone=normalizePhone(f.remote);if(["STOP","STOPALL","UNSUBSCRIBE","CANCEL","END","QUIT"].includes(kw)){const {data:x}=await svc.from("contact_suppressions").select("id").eq("organization_id",org).eq("phone_normalized",phone).eq("active",true).limit(1).maybeSingle();const p={contact_id:contactId,phone_normalized:phone,reason:"sms_opt_out",active:true,metadata:{provider:"telnyx",event_id:f.eventId,keyword:kw}};if(x?.id)await svc.from("contact_suppressions").update(p).eq("id",x.id);else await svc.from("contact_suppressions").insert({organization_id:org,...p});await svc.from("audit_log").insert({organization_id:org,actor_type:"system",action:"communications.sms.opt_out",entity_type:"contact",entity_id:contactId,connection_id:connectionId,success:true,context:{phone,provider:"telnyx",keyword:kw}}).catch(()=>{})}else if(["START","UNSTOP"].includes(kw)){const {data:x}=await svc.from("contact_suppressions").select("id").eq("organization_id",org).eq("phone_normalized",phone).eq("active",true).limit(1).maybeSingle();if(x?.id){await svc.from("contact_suppressions").update({active:false,metadata:{provider:"telnyx",event_id:f.eventId,keyword:kw,reopened_at:new Date().toISOString()}}).eq("id",x.id);await svc.from("audit_log").insert({organization_id:org,actor_type:"system",action:"communications.sms.opt_in",entity_type:"contact",entity_id:contactId,connection_id:connectionId,success:true,context:{phone,provider:"telnyx",keyword:kw}}).catch(()=>{})}}}
  await svc.from("communications_engine_providers").update({last_health_at:new Date().toISOString()}).eq("provider_key","telnyx").eq("channel",f.channel);
  return json({ok:true,event_id:f.eventId,event_type:f.eventType},200);
}
async function saveSecret(svc:any,connectionId:string,currentId:string|null|undefined,value:string,name:string,description:string){if(currentId){const {error}=await svc.rpc("service_update_secret",{p_secret_id:currentId,p_secret:value,p_name:name,p_description:description});if(error)throw new Error("secret_update_failed");return currentId}const {data:id,error}=await svc.rpc("service_store_secret",{p_secret:value,p_name:name,p_description:description});if(error||!id)throw new Error("secret_storage_failed");return id}
async function handleFreshsales(b:any,org:string,user:any,svc:any,o:string|null){
  const apiKey=String(b.api_key||"").trim(),accountUrl=String(b.account_url||"").trim();if(apiKey.length<10||!accountUrl)return json({error:"api_key_and_account_url_required"},400,o);let base:string;try{base=freshBase(accountUrl)}catch(e){return json({error:String((e as Error).message)},400,o)}
  const verify=await fetch(`${base}/api/settings/contacts/fields`,{headers:{Authorization:`Token token=${apiKey}`,Accept:"application/json"}});if(!verify.ok){await svc.from("audit_log").insert({organization_id:org,actor_user_id:user.id,actor_type:"user",action:"connection.freshsales.validation_failed",entity_type:"connection",success:false,context:{status:verify.status,host:new URL(base).hostname}});return json({error:"freshsales_validation_failed",status:verify.status},422,o)}
  const host=new URL(base).hostname,externalId=host;const {data:existing}=await svc.from("connections").select("id").eq("organization_id",org).eq("provider_key","freshsales").eq("external_account_id",externalId).maybeSingle();let connectionId:string;if(existing?.id){connectionId=existing.id;await svc.from("connections").update({status:"connected",external_account_name:host,last_sync_at:new Date().toISOString(),expires_at:null,scopes:[],metadata:{api_base_url:base,auth_mode:"api_key"}}).eq("id",connectionId)}else{const {data:c,error}=await svc.from("connections").insert({organization_id:org,provider_key:"freshsales",status:"connected",external_account_id:externalId,external_account_name:host,scopes:[],expires_at:null,last_sync_at:new Date().toISOString(),created_by:user.id,metadata:{api_base_url:base,auth_mode:"api_key"}}).select("id").single();if(error||!c)return json({error:"connection_create_failed"},500,o);connectionId=c.id}
  const {data:sec}=await svc.from("connection_secrets").select("access_token_secret_id").eq("connection_id",connectionId).maybeSingle();let secretId:string;try{secretId=await saveSecret(svc,connectionId,sec?.access_token_secret_id,apiKey,`cloudsales/freshsales/${connectionId}/api_key`,"Freshsales API key")}catch{return json({error:"secret_storage_failed"},500,o)}
  await svc.from("connection_secrets").upsert({connection_id:connectionId,access_token_secret_id:secretId,refresh_token_secret_id:null,rotated_at:new Date().toISOString()},{onConflict:"connection_id"});await svc.from("audit_log").insert({organization_id:org,actor_user_id:user.id,actor_type:"user",action:"connection.freshsales.connected",entity_type:"connection",entity_id:connectionId,connection_id:connectionId,success:true,context:{host}});return json({connection:{id:connectionId,provider_key:"freshsales",status:"connected",external_account_name:host}},200,o)
}
async function handleTelnyxUser(b:any,org:string,user:any,svc:any,o:string|null){
  const action=String(b.action||"connect");
  if(action==="connect"){
    const apiKey=String(b.api_key||"").trim();if(apiKey.length<20)return json({error:"telnyx_api_key_required"},400,o);
    const [profiles,numbers]=await Promise.all([telnyxFetch(apiKey,"/messaging_profiles?page[size]=100"),telnyxFetch(apiKey,"/phone_numbers?page[size]=100")]);
    if(!profiles.ok){await svc.from("audit_log").insert({organization_id:org,actor_user_id:user.id,actor_type:"user",action:"connection.telnyx.validation_failed",entity_type:"connection",success:false,context:{status:profiles.status}}).catch(()=>{});return json({error:"telnyx_validation_failed",status:profiles.status},422,o)}
    if(!numbers.ok)return json({error:"telnyx_phone_numbers_read_failed",status:numbers.status},422,o);
    const fp=await fingerprint(apiKey),externalId=`telnyx:${fp}`,phoneRows=Array.isArray(numbers.data?.data)?numbers.data.data:[],profileRows=Array.isArray(profiles.data?.data)?profiles.data.data:[];
    const meta={auth_mode:"api_key",account_fingerprint:fp,api_base:"https://api.telnyx.com/v2",messaging_profiles:profileRows.map((p:any)=>({id:String(p.id||""),name:String(p.name||""),enabled:p.enabled!==false})),phone_numbers:phoneRows.map((n:any)=>({id:String(n.id||""),phone_number:normalizePhone(n.phone_number),messaging_profile_id:String(n.messaging_profile_id||""),status:String(n.status||"")})),webhook_signature:"ed25519",webhook_public_key_configured:false};
    const {data:existing}=await svc.from("connections").select("id,metadata").eq("organization_id",org).eq("provider_key","telnyx").eq("external_account_id",externalId).maybeSingle();let connectionId:string;
    if(existing?.id){connectionId=existing.id;await svc.from("connections").update({status:"connected",external_account_name:`Telnyx ${fp.slice(-6)}`,last_sync_at:new Date().toISOString(),metadata:{...(existing.metadata||{}),...meta,webhook_public_key_configured:Boolean(existing.metadata?.webhook_public_key_configured)}}).eq("id",connectionId)}else{const {data:c,error}=await svc.from("connections").insert({organization_id:org,provider_key:"telnyx",status:"connected",external_account_id:externalId,external_account_name:`Telnyx ${fp.slice(-6)}`,scopes:["messaging"],expires_at:null,last_sync_at:new Date().toISOString(),created_by:user.id,metadata:meta}).select("id").single();if(error||!c)return json({error:"connection_create_failed",detail:error?.message||null},500,o);connectionId=c.id}
    const {data:sec}=await svc.from("connection_secrets").select("access_token_secret_id,webhook_secret_secret_id").eq("connection_id",connectionId).maybeSingle();let apiSecretId:string;try{apiSecretId=await saveSecret(svc,connectionId,sec?.access_token_secret_id,apiKey,`cloudsales/telnyx/${connectionId}/api_key`,"Telnyx API key")}catch{return json({error:"secret_storage_failed"},500,o)}
    await svc.from("connection_secrets").upsert({connection_id:connectionId,access_token_secret_id:apiSecretId,webhook_secret_secret_id:sec?.webhook_secret_secret_id||null,rotated_at:new Date().toISOString()},{onConflict:"connection_id"});
    const {data:primary}=await svc.from("channel_provider_bindings").select("id").eq("organization_id",org).eq("channel","sms").eq("is_primary",true).neq("status","disabled").limit(1).maybeSingle();let assigned=Boolean(primary?.id),bound=0;
    for(const n of phoneRows){const phone=normalizePhone(n.phone_number);if(!phone||!n.messaging_profile_id)continue;const isPrimary=!assigned;const {error}=await svc.from("channel_provider_bindings").upsert({organization_id:org,channel:"sms",provider_key:"telnyx",connection_id:connectionId,provider_account_id:externalId,provider_channel_id:phone,provider_channel_name:phone,status:"connected",inbound_enabled:true,outbound_enabled:true,is_primary:isPrimary,capabilities:["sms.send","sms.receive","message.status"],metadata:{phone_number_id:String(n.id||""),messaging_profile_id:String(n.messaging_profile_id||"")}},{onConflict:"organization_id,channel,provider_key,provider_channel_id"});if(!error){bound++;if(isPrimary)assigned=true}}
    await svc.from("audit_log").insert({organization_id:org,actor_user_id:user.id,actor_type:"user",action:"connection.telnyx.connected",entity_type:"connection",entity_id:connectionId,connection_id:connectionId,success:true,context:{phone_count:phoneRows.length,messaging_profile_count:profileRows.length,sms_bindings:bound}});
    return json({ok:true,connection:{id:connectionId,provider_key:"telnyx",status:"connected",external_account_name:`Telnyx ${fp.slice(-6)}`},discovered:{phone_numbers:phoneRows.length,messaging_profiles:profileRows.length,sms_bindings:bound},webhook_url:`${U}/functions/v1/connection-secret-setup`,next:"configure_webhook_public_key"},200,o)
  }
  const connectionId=String(b.connection_id||"");if(!connectionId)return json({error:"connection_id_required"},400,o);
  const {data:connection}=await svc.from("connections").select("id,metadata").eq("id",connectionId).eq("organization_id",org).eq("provider_key","telnyx").maybeSingle();if(!connection)return json({error:"telnyx_connection_not_found"},404,o);
  if(action==="configure_webhook_public_key"){
    const key=String(b.public_key||"").trim();try{if(publicKeyBytes(key).length!==32)throw new Error()}catch{return json({error:"invalid_ed25519_public_key"},400,o)}
    const {data:sec}=await svc.from("connection_secrets").select("access_token_secret_id,webhook_secret_secret_id").eq("connection_id",connectionId).maybeSingle();let id:string;try{id=await saveSecret(svc,connectionId,sec?.webhook_secret_secret_id,key,`cloudsales/telnyx/${connectionId}/webhook_public_key`,"Telnyx Ed25519 webhook public key")}catch{return json({error:"webhook_key_storage_failed"},500,o)}
    await svc.from("connection_secrets").upsert({connection_id:connectionId,access_token_secret_id:sec?.access_token_secret_id||null,webhook_secret_secret_id:id,rotated_at:new Date().toISOString()},{onConflict:"connection_id"});await svc.from("connections").update({metadata:{...(connection.metadata||{}),webhook_public_key_configured:true,webhook_url:`${U}/functions/v1/connection-secret-setup`}}).eq("id",connectionId);return json({ok:true,connection_id:connectionId,webhook_public_key_configured:true,webhook_url:`${U}/functions/v1/connection-secret-setup`},200,o)
  }
  if(action==="bind_whatsapp_number"){
    const phone=normalizePhone(b.phone_number);if(!phone)return json({error:"phone_number_required"},400,o);const known=Array.isArray(connection.metadata?.phone_numbers)&&connection.metadata.phone_numbers.some((n:any)=>normalizePhone(n.phone_number)===phone);if(!known)return json({error:"phone_number_not_owned_by_connection"},422,o);const verified=b.verified===true;const {data:primary}=await svc.from("channel_provider_bindings").select("id").eq("organization_id",org).eq("channel","whatsapp").eq("is_primary",true).neq("status","disabled").limit(1).maybeSingle();const {data:binding,error}=await svc.from("channel_provider_bindings").upsert({organization_id:org,channel:"whatsapp",provider_key:"telnyx",connection_id:connectionId,provider_account_id:String(connection.metadata?.account_fingerprint||""),provider_channel_id:phone,provider_channel_name:phone,status:verified?"connected":"pending",inbound_enabled:verified,outbound_enabled:verified,is_primary:!primary?.id,capabilities:["whatsapp.send","whatsapp.receive","whatsapp.template.send","whatsapp.media.send","message.status"],metadata:{waba_id:b.waba_id?String(b.waba_id):null,telnyx_whatsapp_enabled:verified}},{onConflict:"organization_id,channel,provider_key,provider_channel_id"}).select("id,status").single();if(error||!binding)return json({error:"whatsapp_binding_failed",detail:error?.message||null},500,o);return json({ok:true,binding,phone_number:phone},200,o)
  }
  if(action==="test_send"){
    const channel=String(b.channel||"").toLowerCase(),recipient=normalizePhone(b.recipient),body=String(b.body||"");if(!["sms","whatsapp"].includes(channel)||!recipient||(!body&&!b.template_key&&!Array.isArray(b.media)))return json({error:"channel_recipient_content_required"},400,o);
    const {data:sup}=await svc.from("contact_suppressions").select("id,reason").eq("organization_id",org).eq("phone_normalized",recipient).eq("active",true).limit(1).maybeSingle();if(sup)return json({error:"recipient_suppressed",reason:sup.reason},423,o);
    const {data:bindings}=await svc.from("channel_provider_bindings").select("*").eq("organization_id",org).eq("channel",channel).eq("provider_key","telnyx").eq("connection_id",connectionId).eq("status","connected").eq("outbound_enabled",true).order("is_primary",{ascending:false}).limit(1);const binding=bindings?.[0];if(!binding)return json({error:"telnyx_sender_binding_missing",channel},409,o);
    const {data:sec}=await svc.from("connection_secrets").select("access_token_secret_id").eq("connection_id",connectionId).maybeSingle();if(!sec?.access_token_secret_id)return json({error:"telnyx_api_key_missing"},503,o);const {data:apiKey}=await svc.rpc("service_read_secret",{p_secret_id:sec.access_token_secret_id});if(!apiKey)return json({error:"telnyx_api_key_unavailable"},503,o);
    const sender=normalizePhone(binding.provider_channel_id),idempotency=String(b.idempotency_key||crypto.randomUUID());const {data:job,error:je}=await svc.from("communications_engine_jobs").insert({organization_id:org,contact_id:b.contact_id||null,channel,purpose:"provider_e2e_test",recipient,body:body||null,template_key:b.template_key?String(b.template_key):null,media:Array.isArray(b.media)?b.media:[],idempotency_key:idempotency,authorization_mode:"explicit_user",authorization_ref:`user:${user.id}`,provider_key:"telnyx",connection_id:connectionId,status:"sending",attempts:1,metadata:{test_mode:true,requested_by:user.id}}).select("id").single();if(je||!job)return json({error:"job_create_failed",detail:je?.message||null},500,o);
    let endpoint="/messages",payload:any={from:sender,to:recipient,text:body};if(channel==="sms"){const profile=String(binding.metadata?.messaging_profile_id||"");if(profile)payload.messaging_profile_id=profile;if(Array.isArray(b.media)&&b.media.length)payload.media_urls=b.media.map((m:any)=>typeof m==="string"?m:m?.url).filter(Boolean).slice(0,10)}else{endpoint="/messages/whatsapp";if(b.template_key)payload={from:sender,to:recipient,whatsapp_message:{type:"template",template:{name:String(b.template_key),language:{policy:"deterministic",code:String(b.language||"en_US")},components:Array.isArray(b.template_components)?b.template_components:[]}}};else if(Array.isArray(b.media)&&b.media.length){const m=b.media[0],url=typeof m==="string"?m:String(m?.url||""),type=String(typeof m==="object"&&m?.type||"image");payload={from:sender,to:recipient,whatsapp_message:{type,[type]:{link:url,...(body?{caption:body}:{})}}}}else payload={from:sender,to:recipient,whatsapp_message:{type:"text",text:{body,preview_url:false}}}}
    const result=await telnyxFetch(String(apiKey),endpoint,{method:"POST",body:JSON.stringify(payload)});if(!result.ok){const err=result.text.slice(0,1200);await svc.from("communications_engine_jobs").update({status:"failed",last_error:`telnyx_${result.status}:${err}`}).eq("id",job.id);await svc.from("communications_engine_events").insert({job_id:job.id,organization_id:org,provider_key:"telnyx",channel,event_type:"send.failed",occurred_at:new Date().toISOString(),payload:{status:result.status,error:err}});return json({error:"telnyx_send_failed",status:result.status,detail:err},502,o)}
    const messageId=String(result.data?.data?.id||result.data?.id||""),now=new Date().toISOString();await svc.from("communications_engine_jobs").update({status:"sent",provider_message_id:messageId||null,sent_at:now,last_error:null}).eq("id",job.id);await svc.from("communications_engine_events").insert({job_id:job.id,organization_id:org,provider_key:"telnyx",channel,provider_message_id:messageId||null,event_type:"send.accepted",occurred_at:now,payload:{test_mode:true}});
    return json({ok:true,test_mode:true,job_id:job.id,provider_message_id:messageId,channel,from:sender,to:recipient},200,o)
  }
  return json({error:"unsupported_telnyx_action",supported:["connect","configure_webhook_public_key","bind_whatsapp_number","test_send"]},400,o)
}
Deno.serve(async req=>{
  const o=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(o)});if(req.method!=="POST")return json({error:"method_not_allowed"},405,o);
  const raw=await req.text(),svc=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});
  if(req.headers.get("telnyx-signature-ed25519"))return await handleTelnyxWebhook(req,raw,svc);
  if(o&&!ORIGINS.has(o))return json({error:"origin_not_allowed"},403,o);
  const auth=req.headers.get("authorization");if(!auth)return json({error:"missing_authorization"},401,o);const uc=createClient(U,A,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:ud}=await uc.auth.getUser();const user=ud.user;if(!user)return json({error:"invalid_session"},401,o);
  let b:any;try{b=JSON.parse(raw)}catch{return json({error:"invalid_json"},400,o)}const org=String(b.organization_id||""),provider=String(b.provider_key||"");if(!org||!provider)return json({error:"missing_required_fields"},400,o);
  const {data:m}=await svc.from("organization_members").select("role,status").eq("organization_id",org).eq("user_id",user.id).maybeSingle();if(!m||m.status!=="active"||!["owner","admin"].includes(m.role))return json({error:"forbidden"},403,o);
  if(provider==="freshsales")return await handleFreshsales(b,org,user,svc,o);
  if(provider==="telnyx")return await handleTelnyxUser(b,org,user,svc,o);
  return json({error:"secret_setup_not_supported",provider_key:provider},409,o);
});