(()=>{
'use strict';
const ID='cs-i18n-v1',STORE='cs_locale';
const LANGS=[
 ['es','ES','Español'],['en','EN','English'],['fr','FR','Français'],['it','IT','Italiano'],['pt-BR','PT','Português'],['de','DE','Deutsch'],['ar-AE','AR','العربية'],['ru','RU','Русский'],['he','HE','עברית'],['zh-CN','中文','简体中文'],['ja','日本語','日本語']
];
const RTL=new Set(['ar-AE','he']);
const T={
 en:{
 'Qué es':'What it is','Servicios':'Services','Afiliados':'Affiliates','Entrar':'Sign in','Empezar':'Get started','Ver planes':'View plans','Abrir la aplicación':'Open the app',
 'Mejores leads.':'Better leads.','Tu CRM en la palma de tu mano.':'Your CRM in the palm of your hand.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Less junk. More real prospects. More appointments. Control your operation from your phone.',
 'More Qualified Leads':'More Qualified Leads','Reduce junk y prioriza oportunidades con mayor intención.':'Reduce junk and prioritize higher-intent opportunities.','More Appointments':'More Appointments','Seguimiento y automatización enfocados en convertir intención en citas.':'Follow-up and automation focused on turning intent into appointments.','More Sales':'More Sales','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, conversations and next steps in the palm of your hand.',
 'Qué es CloudSales':'What is CloudSales','Cloudy':'Cloudy','Lead Quality':'Lead Quality','Planes':'Plans','Preguntas frecuentes':'Frequently asked questions','Descarga CloudSales':'Download CloudSales','Todo tu negocio comercial en un solo lugar.':'Your entire sales operation in one place.','Elige el plan que se adapte a tu operación.':'Choose the plan that fits your operation.','Recomendado':'Recommended','por mes':'per month','Crear cuenta':'Create account','Hablar con ventas':'Talk to sales','Más información':'Learn more'
 },
 fr:{
 'Qué es':'Présentation','Servicios':'Services','Afiliados':'Affiliés','Entrar':'Connexion','Empezar':'Commencer','Ver planes':'Voir les offres','Abrir la aplicación':'Ouvrir l’application','Mejores leads.':'De meilleurs prospects.','Tu CRM en la palma de tu mano.':'Votre CRM dans la paume de votre main.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Moins de faux prospects. Plus de vrais prospects. Plus de rendez-vous. Pilotez votre activité depuis votre téléphone.','Reduce junk y prioriza oportunidades con mayor intención.':'Réduisez les faux prospects et priorisez les opportunités à forte intention.','Seguimiento y automatización enfocados en convertir intención en citas.':'Suivi et automatisation conçus pour transformer l’intention en rendez-vous.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, conversations et prochaines actions dans la paume de votre main.','Qué es CloudSales':'Qu’est-ce que CloudSales','Planes':'Offres','Preguntas frecuentes':'Questions fréquentes','Descarga CloudSales':'Télécharger CloudSales','Todo tu negocio comercial en un solo lugar.':'Toute votre activité commerciale au même endroit.','Elige el plan que se adapte a tu operación.':'Choisissez l’offre adaptée à votre activité.','Recomendado':'Recommandé','por mes':'par mois','Crear cuenta':'Créer un compte','Hablar con ventas':'Parler aux ventes','Más información':'En savoir plus'
 },
 it:{
 'Qué es':'Cos’è','Servicios':'Servizi','Afiliados':'Affiliati','Entrar':'Accedi','Empezar':'Inizia','Ver planes':'Vedi piani','Abrir la aplicación':'Apri l’app','Mejores leads.':'Lead migliori.','Tu CRM en la palma de tu mano.':'Il tuo CRM nel palmo della mano.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Meno lead spazzatura. Più prospect reali. Più appuntamenti. Gestisci l’attività dal telefono.','Reduce junk y prioriza oportunidades con mayor intención.':'Riduci i lead spazzatura e dai priorità alle opportunità con maggiore intenzione.','Seguimiento y automatización enfocados en convertir intención en citas.':'Follow-up e automazione pensati per trasformare l’intenzione in appuntamenti.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, conversazioni e prossimi passi nel palmo della mano.','Qué es CloudSales':'Cos’è CloudSales','Planes':'Piani','Preguntas frecuentes':'Domande frequenti','Descarga CloudSales':'Scarica CloudSales','Todo tu negocio comercial en un solo lugar.':'Tutta la tua attività commerciale in un unico posto.','Elige el plan que se adapte a tu operación.':'Scegli il piano adatto alla tua attività.','Recomendado':'Consigliato','por mes':'al mese','Crear cuenta':'Crea account','Hablar con ventas':'Parla con le vendite','Más información':'Scopri di più'
 },
 'pt-BR':{
 'Qué es':'O que é','Servicios':'Serviços','Afiliados':'Afiliados','Entrar':'Entrar','Empezar':'Começar','Ver planes':'Ver planos','Abrir la aplicación':'Abrir o app','Mejores leads.':'Leads melhores.','Tu CRM en la palma de tu mano.':'Seu CRM na palma da sua mão.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Menos leads ruins. Mais prospects reais. Mais reuniões. Controle sua operação pelo celular.','Reduce junk y prioriza oportunidades con mayor intención.':'Reduza leads ruins e priorize oportunidades com maior intenção.','Seguimiento y automatización enfocados en convertir intención en citas.':'Follow-up e automação focados em transformar intenção em reuniões.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, conversas e próximos passos na palma da sua mão.','Qué es CloudSales':'O que é o CloudSales','Planes':'Planos','Preguntas frecuentes':'Perguntas frequentes','Descarga CloudSales':'Baixe o CloudSales','Todo tu negocio comercial en un solo lugar.':'Toda a sua operação comercial em um só lugar.','Elige el plan que se adapte a tu operación.':'Escolha o plano ideal para sua operação.','Recomendado':'Recomendado','por mes':'por mês','Crear cuenta':'Criar conta','Hablar con ventas':'Falar com vendas','Más información':'Saiba mais'
 },
 de:{
 'Qué es':'Was ist es','Servicios':'Services','Afiliados':'Partner','Entrar':'Anmelden','Empezar':'Loslegen','Ver planes':'Tarife ansehen','Abrir la aplicación':'App öffnen','Mejores leads.':'Bessere Leads.','Tu CRM en la palma de tu mano.':'Ihr CRM in Ihrer Hand.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Weniger Junk-Leads. Mehr echte Interessenten. Mehr Termine. Steuern Sie Ihren Vertrieb vom Smartphone.','Reduce junk y prioriza oportunidades con mayor intención.':'Reduzieren Sie Junk-Leads und priorisieren Sie Chancen mit hoher Kaufabsicht.','Seguimiento y automatización enfocados en convertir intención en citas.':'Follow-up und Automatisierung, die Kaufabsicht in Termine umwandeln.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, Gespräche und nächste Schritte direkt in Ihrer Hand.','Qué es CloudSales':'Was ist CloudSales','Planes':'Tarife','Preguntas frecuentes':'Häufige Fragen','Descarga CloudSales':'CloudSales herunterladen','Todo tu negocio comercial en un solo lugar.':'Ihr gesamter Vertrieb an einem Ort.','Elige el plan que se adapte a tu operación.':'Wählen Sie den passenden Tarif für Ihr Unternehmen.','Recomendado':'Empfohlen','por mes':'pro Monat','Crear cuenta':'Konto erstellen','Hablar con ventas':'Vertrieb kontaktieren','Más información':'Mehr erfahren'
 },
 'ar-AE':{
 'Qué es':'ما هو','Servicios':'الخدمات','Afiliados':'الشركاء','Entrar':'تسجيل الدخول','Empezar':'ابدأ الآن','Ver planes':'عرض الخطط','Abrir la aplicación':'فتح التطبيق','Mejores leads.':'عملاء محتملون أفضل.','Tu CRM en la palma de tu mano.':'نظام CRM الخاص بك في راحة يدك.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'عملاء غير صالحين أقل، فرص حقيقية أكثر، ومواعيد أكثر. أدر عملياتك من هاتفك.','Reduce junk y prioriza oportunidades con mayor intención.':'قلّل العملاء غير الصالحين وأعطِ الأولوية للفرص الأعلى نية.','Seguimiento y automatización enfocados en convertir intención en citas.':'متابعة وأتمتة لتحويل الاهتمام إلى مواعيد.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'خط المبيعات والمحادثات والخطوات التالية في راحة يدك.','Qué es CloudSales':'ما هو CloudSales','Planes':'الخطط','Preguntas frecuentes':'الأسئلة الشائعة','Descarga CloudSales':'تنزيل CloudSales','Todo tu negocio comercial en un solo lugar.':'كل عمليات المبيعات في مكان واحد.','Elige el plan que se adapte a tu operación.':'اختر الخطة المناسبة لعملياتك.','Recomendado':'موصى به','por mes':'شهرياً','Crear cuenta':'إنشاء حساب','Hablar con ventas':'تحدث مع المبيعات','Más información':'اعرف المزيد'
 },
 ru:{
 'Qué es':'Что это','Servicios':'Услуги','Afiliados':'Партнёры','Entrar':'Войти','Empezar':'Начать','Ver planes':'Смотреть тарифы','Abrir la aplicación':'Открыть приложение','Mejores leads.':'Более качественные лиды.','Tu CRM en la palma de tu mano.':'Ваша CRM прямо в ладони.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Меньше мусорных лидов. Больше реальных клиентов. Больше встреч. Управляйте продажами с телефона.','Reduce junk y prioriza oportunidades con mayor intención.':'Сокращайте мусорные лиды и уделяйте внимание наиболее перспективным возможностям.','Seguimiento y automatización enfocados en convertir intención en citas.':'Фоллоу-ап и автоматизация, превращающие интерес во встречи.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Воронка, диалоги и следующие шаги у вас под рукой.','Qué es CloudSales':'Что такое CloudSales','Planes':'Тарифы','Preguntas frecuentes':'Частые вопросы','Descarga CloudSales':'Скачать CloudSales','Todo tu negocio comercial en un solo lugar.':'Вся коммерческая работа в одном месте.','Elige el plan que se adapte a tu operación.':'Выберите тариф под ваш бизнес.','Recomendado':'Рекомендуем','por mes':'в месяц','Crear cuenta':'Создать аккаунт','Hablar con ventas':'Связаться с отделом продаж','Más información':'Подробнее'
 },
 he:{
 'Qué es':'מה זה','Servicios':'שירותים','Afiliados':'שותפים','Entrar':'כניסה','Empezar':'התחלה','Ver planes':'הצגת תוכניות','Abrir la aplicación':'פתיחת האפליקציה','Mejores leads.':'לידים איכותיים יותר.','Tu CRM en la palma de tu mano.':'ה-CRM שלך בכף היד.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'פחות לידים לא רלוונטיים. יותר לקוחות פוטנציאליים אמיתיים. יותר פגישות. ניהול המכירות מהטלפון.','Reduce junk y prioriza oportunidades con mayor intención.':'צמצום לידים לא רלוונטיים ותעדוף הזדמנויות בעלות כוונה גבוהה.','Seguimiento y automatización enfocados en convertir intención en citas.':'מעקב ואוטומציה שמטרתם להפוך כוונה לפגישות.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'פייפליין, שיחות והצעדים הבאים בכף היד.','Qué es CloudSales':'מה זה CloudSales','Planes':'תוכניות','Preguntas frecuentes':'שאלות נפוצות','Descarga CloudSales':'הורדת CloudSales','Todo tu negocio comercial en un solo lugar.':'כל פעילות המכירות במקום אחד.','Elige el plan que se adapte a tu operación.':'בחרו תוכנית שמתאימה לפעילות שלכם.','Recomendado':'מומלץ','por mes':'לחודש','Crear cuenta':'יצירת חשבון','Hablar con ventas':'שיחה עם מכירות','Más información':'מידע נוסף'
 },
 'zh-CN':{
 'Qué es':'产品介绍','Servicios':'服务','Afiliados':'联盟伙伴','Entrar':'登录','Empezar':'开始使用','Ver planes':'查看方案','Abrir la aplicación':'打开应用','Mejores leads.':'更优质的销售线索。','Tu CRM en la palma de tu mano.':'把 CRM 掌握在手中。','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'更少垃圾线索，更多真实客户，更多预约。通过手机管理销售运营。','Reduce junk y prioriza oportunidades con mayor intención.':'减少垃圾线索，优先处理意向更高的机会。','Seguimiento y automatización enfocados en convertir intención en citas.':'通过跟进和自动化将意向转化为预约。','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'销售管道、对话和下一步行动尽在掌中。','Qué es CloudSales':'什么是 CloudSales','Planes':'方案','Preguntas frecuentes':'常见问题','Descarga CloudSales':'下载 CloudSales','Todo tu negocio comercial en un solo lugar.':'在一个平台管理全部销售运营。','Elige el plan que se adapte a tu operación.':'选择适合您业务的方案。','Recomendado':'推荐','por mes':'每月','Crear cuenta':'创建账户','Hablar con ventas':'联系销售','Más información':'了解更多'
 },
 ja:{
 'Qué es':'概要','Servicios':'サービス','Afiliados':'アフィリエイト','Entrar':'ログイン','Empezar':'始める','Ver planes':'プランを見る','Abrir la aplicación':'アプリを開く','Mejores leads.':'より質の高いリード。','Tu CRM en la palma de tu mano.':'CRMを手のひらに。','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'無効なリードを減らし、見込み客と商談を増やします。スマートフォンから営業を管理できます。','Reduce junk y prioriza oportunidades con mayor intención.':'無効なリードを減らし、意欲の高い商談機会を優先します。','Seguimiento y automatización enfocados en convertir intención en citas.':'フォローアップと自動化で関心を商談へつなげます。','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'パイプライン、会話、次のアクションを手元で管理。','Qué es CloudSales':'CloudSalesとは','Planes':'プラン','Preguntas frecuentes':'よくある質問','Descarga CloudSales':'CloudSalesをダウンロード','Todo tu negocio comercial en un solo lugar.':'営業活動を一か所で管理。','Elige el plan que se adapte a tu operación.':'営業体制に合ったプランを選択してください。','Recomendado':'おすすめ','por mes':'月額','Crear cuenta':'アカウント作成','Hablar con ventas':'営業に相談','Más información':'詳しく見る'
 }
};
function canonicalLocale(x){x=String(x||'').trim();const l=LANGS.find(v=>v[0].toLowerCase()===x.toLowerCase());if(l)return l[0];const short=x.toLowerCase().split('-')[0];return LANGS.find(v=>v[0].toLowerCase().split('-')[0]===short)?.[0]||'es'}
function detect(){const q=new URLSearchParams(location.search).get('lang');if(q)return canonicalLocale(q);try{const s=localStorage.getItem(STORE);if(s)return canonicalLocale(s)}catch{}return canonicalLocale(navigator.language||'es')}
function style(){if(document.getElementById(ID+'-css'))return;const s=document.createElement('style');s.id=ID+'-css';s.textContent=`.csLang{position:relative}.csLangBtn{border:1px solid #343443;background:#111119;color:#f5f4f8;border-radius:999px;padding:8px 10px;font-size:11px;font-weight:850;min-width:48px}.csLangMenu{display:none;position:absolute;right:0;top:calc(100% + 8px);width:210px;max-height:min(430px,70vh);overflow:auto;background:#111119;border:1px solid #343443;border-radius:17px;padding:7px;box-shadow:0 24px 70px #000b;z-index:120}.csLang.open .csLangMenu{display:grid}.csLangOpt{border:0;background:transparent;color:#d5d3dd;border-radius:11px;padding:9px 10px;text-align:left;font-size:11px;display:flex;justify-content:space-between;gap:10px}.csLangOpt:hover,.csLangOpt.active{background:#211725;color:#fff}.csLangOpt span:last-child{color:#77768a;font-size:9px}.csLangMobile{display:none}@media(max-width:940px){.csLangDesktop{display:none}.csLangMobile{display:block;margin-left:auto}.navin{gap:10px}}[dir="rtl"] .csLangMenu{right:auto;left:0}[dir="rtl"] .csLangOpt{text-align:right}`;document.head.appendChild(s)}
function translateText(locale){const dict=T[locale]||{};const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue?.trim())return NodeFilter.FILTER_REJECT;const p=n.parentElement;if(!p||['SCRIPT','STYLE','TEXTAREA','OPTION'].includes(p.tagName))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){if(!n.__csOriginal)n.__csOriginal=n.nodeValue;const base=n.__csOriginal.trim();if(locale==='es'){n.nodeValue=n.__csOriginal;continue}const tr=dict[base];if(tr)n.nodeValue=n.__csOriginal.replace(base,tr)}}
function meta(locale){const desc={es:'CloudSales mejora la calidad de tus leads, reduce junk leads y te permite controlar tu CRM, conversaciones, citas y pipeline desde la palma de tu mano.',en:'CloudSales improves lead quality, reduces junk leads, and lets you manage your CRM, conversations, appointments, and pipeline from your phone.',fr:'CloudSales améliore la qualité des prospects, réduit les faux leads et vous permet de gérer CRM, conversations, rendez-vous et pipeline depuis votre téléphone.',it:'CloudSales migliora la qualità dei lead, riduce i lead spazzatura e ti permette di gestire CRM, conversazioni, appuntamenti e pipeline dal telefono.','pt-BR':'CloudSales melhora a qualidade dos leads, reduz leads ruins e permite controlar CRM, conversas, reuniões e pipeline pelo celular.',de:'CloudSales verbessert die Lead-Qualität, reduziert Junk-Leads und ermöglicht CRM, Gespräche, Termine und Pipeline vom Smartphone aus.','ar-AE':'يحسن CloudSales جودة العملاء المحتملين ويقلل العملاء غير الصالحين ويتيح إدارة CRM والمحادثات والمواعيد وخط المبيعات من الهاتف.',ru:'CloudSales повышает качество лидов, сокращает мусорные лиды и позволяет управлять CRM, диалогами, встречами и воронкой с телефона.',he:'CloudSales משפר את איכות הלידים, מפחית לידים לא רלוונטיים ומאפשר לנהל CRM, שיחות, פגישות ופייפליין מהטלפון.','zh-CN':'CloudSales 提升销售线索质量、减少垃圾线索，并可通过手机管理 CRM、对话、预约和销售管道。',ja:'CloudSalesはリード品質を高め、無効なリードを減らし、CRM・会話・商談・パイプラインをスマートフォンから管理できます。'};document.querySelector('meta[name="description"]')?.setAttribute('content',desc[locale]||desc.es);document.title=locale==='es'?'CloudSales — Better Leads. Full CRM Control.':'CloudSales — Better Leads. Full CRM Control.'}
function menu(locale){const html=LANGS.map(([code,short,name])=>`<button class="csLangOpt ${code===locale?'active':''}" data-lang="${code}"><b>${name}</b><span>${short}</span></button>`).join('');return `<div class="csLang"><button class="csLangBtn" aria-label="Language">${LANGS.find(x=>x[0]===locale)?.[1]||'ES'} ▾</button><div class="csLangMenu">${html}</div></div>`}
function mount(locale){document.querySelectorAll('.csLang').forEach(x=>x.remove());const links=document.querySelector('.navlinks');if(links){const d=document.createElement('div');d.className='csLangDesktop';d.innerHTML=menu(locale);links.insertBefore(d,links.firstChild)}const navin=document.querySelector('.navin');if(navin){const m=document.createElement('div');m.className='csLangMobile';m.innerHTML=menu(locale);navin.appendChild(m)}document.querySelectorAll('.csLangBtn').forEach(b=>b.onclick=e=>{e.stopPropagation();b.closest('.csLang')?.classList.toggle('open')});document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLocale(b.dataset.lang));document.addEventListener('click',()=>document.querySelectorAll('.csLang.open').forEach(x=>x.classList.remove('open')),{once:true,capture:true})}
function setLocale(x){const locale=canonicalLocale(x);try{localStorage.setItem(STORE,locale)}catch{}const u=new URL(location.href);u.searchParams.set('lang',locale);history.replaceState(null,'',u);apply(locale)}
function apply(locale){document.documentElement.lang=locale;document.documentElement.dir=RTL.has(locale)?'rtl':'ltr';translateText(locale);meta(locale);mount(locale);document.documentElement.dataset.csLocale=locale;window.dispatchEvent(new CustomEvent('cloudsales:locale',{detail:{locale}}))}
style();const locale=detect();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>apply(locale),{once:true});else apply(locale);window.CloudSalesI18n={setLocale,getLocale:()=>canonicalLocale(document.documentElement.dataset.csLocale||locale),languages:LANGS.map(x=>x[0])};
})();
