(()=>{
'use strict';
const ID='cs-i18n-v1',STORE='cs_locale';
const LANGS=[
 ['es','ES','Español'],['en','EN','English'],['fr','FR','Français'],['it','IT','Italiano'],['pt-BR','PT','Português'],['de','DE','Deutsch'],['ar-AE','AR','العربية'],['ru','RU','Русский'],['he','HE','עברית'],['zh-CN','中文','简体中文'],['ja','日本語','日本語']
];
const RTL=new Set(['ar-AE','he']);
const T={
 en:{
 'Qué es':'What it is','Servicios':'Services','Afiliados':'Affiliates','Entrar':'Sign in','Empezar':'Get started','Ver planes':'View plans','Abrir la aplicación':'Open the app',
 'Mejores leads.':'Better leads.','Tu CRM en la palma de tu mano.':'Your CRM in the palm of your hand.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Less junk. More real prospects. More appointments. Control your operation from your phone.',
 'More Qualified Leads':'More Qualified Leads','Reduce junk y prioriza oportunidades con mayor intención.':'Reduce junk and prioritize higher-intent opportunities.','More Appointments':'More Appointments','Seguimiento y automatización enfocados en convertir intención en citas.':'Follow-up and automation focused on turning intent into appointments.','More Sales':'More Sales','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, conversations and next steps in the palm of your hand.',
 'Qué es CloudSales':'What is CloudSales','Cloudy':'Cloudy','Lead Quality':'Lead Quality','Planes':'Plans','Preguntas frecuentes':'Frequently asked questions','Descarga CloudSales':'Download CloudSales','Todo tu negocio comercial en un solo lugar.':'Your entire sales operation in one place.','Elige el plan que se adapte a tu operación.':'Choose the plan that fits your operation.','Recomendado':'Recommended','por mes':'per month','Crear cuenta':'Create account','Hablar con ventas':'Talk to sales','Más información':'Learn more'
 },
 fr:{
 'Qué es':'Présentation','Servicios':'Services','Afiliados':'Affiliés','Entrar':'Connexion','Empezar':'Commencer','Ver planes':'Voir les offres','Abrir la aplicación':'Ouvrir l’application','Mejores leads.':'De meilleurs prospects.','Tu CRM en la palma de tu mano.':'Votre CRM dans la paume de votre main.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Moins de faux prospects. Plus de vrais prospects. Plus de rendez-vous. Pilotez votre activité depuis votre téléphone.','Reduce junk y prioriza oportunidades con mayor intención.':'Réduisez les faux prospects et priorisez les opportunités à forte intention.','Seguimiento y automatización enfocados en convertir intención en citas.':'Suivi et automatisation conçus pour transformer l’intention en rendez-vous.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, conversations et prochaines actions dans la paume de votre main.','Qué es CloudSales':'Qu’est-ce que CloudSales','Planes':'Offres','Preguntas frecuentes':'Questions fréquentes','Descarga CloudSales':'Télécharger CloudSales','Todo tu negocio comercial en un solo lugar.':'Toute votre activité commerciale au même endroit.','Elige el plan que se adapte a tu operación.':'Choisissez l’offre adaptée à votre activité.','Recomendado':'Recommandé','por mes':'par mois','Crear cuenta':'Créer un compte','Hablar con ventas':'Parler aux ventes','Más información':'En savoir plus'
 },
 it:{
 'Qué es':'Cos’è','Servicios':'Servizi','Afiliados':'Affiliati','Entrar':'Accedi','Empezar':'Inizia','Ver planes':'Vedi piani','Abrir la aplicación':'Apri l’app','Mejores leads.':'Lead migliori.','Tu CRM en la palma de tu mano.':'Il tuo CRM nel palmo della mano.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Meno lead spazzatura. Più prospect reali. Più appuntamenti. Gestisci l’attività dal telefono.','Reduce junk y prioriza oportunidades con mayor intención.':'Riduci i lead spazzatura e dai priorità alle opportunità con maggiore intenzione.','Seguimiento y automatización enfocados en convertir intención en citas.':'Follow-up e automazione pensati per trasformare l’intenzione in appuntamenti.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, conversazioni e prossimi passi nel palmo della mano.','Qué es CloudSales':'Cos’è CloudSales','Planes':'Piani','Preguntas frecuentes':'Domande frequenti','Descarga CloudSales':'Scarica CloudSales','Todo tu negocio comercial en un solo lugar.':'Tutta la tua attività commerciale in un unico posto.','Elige el plan que se adapte a tu operación.':'Scegli il piano adatto alla tua attività.','Recomendado':'Consigliato','por mes':'al mese','Crear cuenta':'Crea account','Hablar con ventas':'Parla con le vendite','Más información':'Scopri di più'
 },
 'pt-BR':{
 'Qué es':'O que é','Servicios':'Serviços','Afiliados':'Afiliados','Entrar':'Entrar','Empezar':'Começar','Ver planes':'Ver planos','Abrir la aplicación':'Abrir o app','Mejores leads.':'Leads melhores.','Tu CRM en la palma de tu mano.':'Seu CRM na palma da sua mão.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Menos leads ruins. Mais prospects reais. Mais reuniões. Controle sua operação pelo celular.','Reduce junk y prioriza oportunidades con mayor intención.':'Reduza leads ruins e priorize oportunidades com maior intenção.','Seguimiento y automatización enfocados en convertir intención en citas.':'Follow-up e automação focados em transformar intenção em reuniões.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, conversas e próximos passos na palma da sua mão.','Qué es CloudSales':'O que é o CloudSales','Planes':'Planos','Preguntas frecuentes':'Perguntas frequentes','Descarga CloudSales':'Baixe o CloudSales','Todo tu negocio comercial en un solo lugar.':'Toda a sua operação comercial em um só lugar.','Elige el plan que se adapte a tu operación.':'Escolha o plano ideal para sua operação.','Recomendado':'Recomendado','por mes':'por mês','Crear cuenta':'Criar conta','Hablar con ventas':'Falar com vendas','Más información':'Saiba mais'
 },
 de:{
 'Qué es':'Was ist es','Servicios':'Services','Afiliados':'Partner','Entrar':'Anmelden','Empezar':'Loslegen','Ver planes':'Tarife ansehen','Abrir la aplicación':'App öffnen','Mejores leads.':'Bessere Leads.','Tu CRM en la palma de tu mano.':'Ihr CRM in Ihrer Hand.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Weniger Junk-Leads. Mehr echte Interessenten. Mehr Termine. Steuern Sie Ihren Vertrieb vom Smartphone.','Reduce junk y prioriza oportunidades con mayor intención.':'Reduzieren Sie Junk-Leads und priorisieren Sie Chancen mit hoher Kaufabsicht.','Seguimiento y automatización enfocados en convertir intención en citas.':'Follow-up und Automatisierung, die Kaufabsicht in Termine umwandeln.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Pipeline, Gespräche und nächste Schritte direkt in Ihrer Hand.','Qué es CloudSales':'Was ist CloudSales','Planes':'Tarife','Preguntas frecuentes':'Häufige Fragen','Descarga CloudSales':'CloudSales herunterladen','Todo tu negocio comercial en un solo lugar.':'Ihr gesamter Vertrieb an einem Ort.','Elige el plan que se adapte a tu operación.':'Wählen Sie den passenden Tarif für Ihr Unternehmen.','Recomendado':'Empfohlen','por mes':'pro Monat','Crear cuenta':'Konto erstellen','Hablar con ventas':'Vertrieb kontaktieren','Más información':'Mehr erfahren'
 },
 'ar-AE':{
 'Qué es':'ما هو','Servicios':'الخدمات','Afiliados':'الشركاء','Entrar':'تسجيل الدخول','Empezar':'ابدأ الآن','Ver planes':'عرض الخطط','Abrir la aplicación':'فتح التطبيق','Mejores leads.':'عملاء محتملون أفضل.','Tu CRM en la palma de tu mano.':'نظام CRM الخاص بك في راحة يدك.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'عملاء غير صالحين أقل، فرص حقيقية أكثر، ومواعيد أكثر. أدر عملياتك من هاتفك.','Reduce junk y prioriza oportunidades con mayor intención.':'قلّل العملاء غير الصالحين وأعطِ الأولوية للفرص الأعلى نية.','Seguimiento y automatización enfocados en convertir intención en citas.':'متابعة وأتمتة لتحويل الاهتمام إلى مواعيد.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'خط المبيعات والمحادثات والخطوات التالية في راحة يدك.','Qué es CloudSales':'ما هو CloudSales','Planes':'الخطط','Preguntas frecuentes':'الأسئلة الشائعة','Descarga CloudSales':'تنزيل CloudSales','Todo tu negocio comercial en un solo lugar.':'كل عمليات المبيعات في مكان واحد.','Elige el plan que se adapte a tu operación.':'اختر الخطة المناسبة لعملياتك.','Recomendado':'موصى به','por mes':'شهرياً','Crear cuenta':'إنشاء حساب','Hablar con ventas':'تحدث مع المبيعات','Más información':'اعرف المزيد'
 },
 ru:{
 'Qué es':'Что это','Servicios':'Услуги','Afiliados':'Партнёры','Entrar':'Войти','Empezar':'Начать','Ver planes':'Смотреть тарифы','Abrir la aplicación':'Открыть приложение','Mejores leads.':'Более качественные лиды.','Tu CRM en la palma de tu mano.':'Ваша CRM прямо в ладони.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'Меньше мусорных лидов. Больше реальных клиентов. Больше встреч. Управляйте продажами с телефона.','Reduce junk y prioriza oportunidades con mayor intención.':'Сокращайте мусорные лиды и уделяйте внимание наиболее перспективным возможностям.','Seguimiento y automatización enfocados en convertir intención en citas.':'Фоллоу-ап и автоматизация, превращающие интерес во встречи.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'Воронка, диалоги и следующие шаги у вас под рукой.','Qué es CloudSales':'Что такое CloudSales','Planes':'Тарифы','Preguntas frecuentes':'Частые вопросы','Descarga CloudSales':'Скачать CloudSales','Todo tu negocio comercial en un solo lugar.':'Вся коммерческая работа в одном месте.','Elige el plan que se adapte a tu operación.':'Выберите тариф под ваш бизнес.','Recomendado':'Рекомендуем','por mes':'в месяц','Crear cuenta':'Создать аккаунт','Hablar con ventas':'Связаться с отделом продаж','Más información':'Подробнее'
 },
 he:{
 'Qué es':'מה זה','Servicios':'שירותים','Afiliados':'שותפים','Entrar':'כניסה','Empezar':'התחלה','Ver planes':'הצגת תוכניות','Abrir la aplicación':'פתיחת האפליקציה','Mejores leads.':'לידים איכותיים יותר.','Tu CRM en la palma de tu mano.':'ה-CRM שלך בכף היד.','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'פחות לידים לא רלוונטיים. יותר לקוחות פוטנציאליים אמיתיים. יותר פגישות. ניהול המכירות מהטלפון.','Reduce junk y prioriza oportunidades con mayor intención.':'צמצום לידים לא רלוונטיים ותעדוף הזדמנויות בעלות כוונה גבוהה.','Seguimiento y automatización enfocados en convertir intención en citas.':'מעקב ואוטומציה שמטרתם להפוך כוונה לפגישות.','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'פייפליין, שיחות והצעדים הבאים בכף היד.','Qué es CloudSales':'מה זה CloudSales','Planes':'תוכניות','Preguntas frecuentes':'שאלות נפוצות','Descarga CloudSales':'הורדת CloudSales','Todo tu negocio comercial en un solo lugar.':'כל פעילות המכירות במקום אחד.','Elige el plan que se adapte a tu operación.':'בחרו תוכנית שמתאימה לפעילות שלכם.','Recomendado':'מומלץ','por mes':'לחודש','Crear cuenta':'יצירת חשבון','Hablar con ventas':'שיחה עם מכירות','Más información':'מידע נוסף'
 },
 'zh-CN':{
 'Qué es':'产品介绍','Servicios':'服务','Afiliados':'联盟伙伴','Entrar':'登录','Empezar':'开始使用','Ver planes':'查看方案','Abrir la aplicación':'打开应用','Mejores leads.':'更优质的销售线索。','Tu CRM en la palma de tu mano.':'把 CRM 掌握在手中。','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'更少垃圾线索，更多真实客户，更多预约。通过手机管理销售运营。','Reduce junk y prioriza oportunidades con mayor intención.':'减少垃圾线索，优先处理意向更高的机会。','Seguimiento y automatización enfocados en convertir intención en citas.':'通过跟进和自动化将意向转化为预约。','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'销售管道、对话和下一步行动尽在掌中。','Qué es CloudSales':'什么是 CloudSales','Planes':'方案','Preguntas frecuentes':'常见问题','Descarga CloudSales':'下载 CloudSales','Todo tu negocio comercial en un solo lugar.':'在一个平台管理全部销售运营。','Elige el plan que se adapte a tu operación.':'选择适合您业务的方案。','Recomendado':'推荐','por mes':'每月','Crear cuenta':'创建账户','Hablar con ventas':'联系销售','Más información':'了解更多'
 },
 ja:{
 'Qué es':'概要','Servicios':'サービス','Afiliados':'アフィリエイト','Entrar':'ログイン','Empezar':'始める','Ver planes':'プランを見る','Abrir la aplicación':'アプリを開く','Mejores leads.':'より質の高いリード。','Tu CRM en la palma de tu mano.':'CRMを手のひらに。','Menos junk. Más prospectos reales. Más citas. Controla tu operación desde el celular.':'無効なリードを減らし、見込み客と商談を増やします。スマートフォンから営業を管理できます。','Reduce junk y prioriza oportunidades con mayor intención.':'無効なリードを減らし、意欲の高い商談機会を優先します。','Seguimiento y automatización enfocados en convertir intención en citas.':'フォローアップと自動化で関心を商談へつなげます。','Pipeline, conversaciones y próximos pasos en la palma de tu mano.':'パイプライン、会話、次のアクションを手元で管理。','Qué es CloudSales':'CloudSalesとは','Planes':'プラン','Preguntas frecuentes':'よくある質問','Descarga CloudSales':'CloudSalesをダウンロード','Todo tu negocio comercial en un solo lugar.':'営業活動を一か所で管理。','Elige el plan que se adapte a tu operación.':'営業体制に合ったプランを選択してください。','Recomendado':'おすすめ','por mes':'月額','Crear cuenta':'アカウント作成','Hablar con ventas':'営業に相談','Más información':'詳しく見る'
 }
};
const EN_FULL={
'CloudSales ayuda a reducir junk leads, prioriza oportunidades reales y simplifica tu operación comercial. Leads, conversaciones, citas, pipeline, automatización y Cloudy desde una sola aplicación.':'CloudSales helps reduce junk leads, prioritize real opportunities, and simplify your sales operation. Leads, conversations, appointments, pipeline, automation, and Cloudy in one app.',
'Cloudy online':'Cloudy online','Alta intención':'High intent','Por aprobar':'Pending approval','Revisa los leads de hoy, sigue los de mayor intención y dime qué necesita mi aprobación.':'Review today’s leads, follow up with the highest-intent ones, and tell me what needs my approval.',
'No es otro software que tienes que aprender.':'It is not another piece of software you have to learn.',
'CloudSales es la capa operativa que conecta las herramientas de tu negocio y las convierte en trabajo ejecutado. Tu CRM puede seguir siendo la infraestructura; CloudSales es la experiencia, el cerebro operativo y el control desde tu celular.':'CloudSales is the operating layer that connects your business tools and turns them into executed work. Your CRM can remain the infrastructure; CloudSales is the experience, the operating brain, and the control layer on your phone.',
'La BMP donde ves lo importante: leads, pipeline, conversaciones, archivos, campañas, citas, señales y resultados. Menos menús. Menos fricción.':'The BMP where you see what matters: leads, pipeline, conversations, files, campaigns, appointments, signals, and results. Fewer menus. Less friction.',
'El operador central. Entiende lo que necesitas, revisa contexto y datos, coordina herramientas, ejecuta tareas permitidas y te pide aprobación cuando una acción lo requiere.':'The central operator. It understands what you need, reviews context and data, coordinates tools, executes allowed tasks, and asks for approval when an action requires it.',
'Agentes especializados que trabajan bajo la coordinación de Cloudy: seguimiento, citas, contenido, mensajes, campañas, operaciones y otras tareas repetitivas.':'Specialized agents working under Cloudy’s coordination: follow-up, appointments, content, messages, campaigns, operations, and other repetitive tasks.',
'Cloudy no te dice cómo hacerlo. Lo hace contigo.':'Cloudy does not just tell you how. It does it with you.',
'Pídele resultados en lenguaje normal. Cloudy convierte una instrucción corta en acciones sobre las cuentas y herramientas que tú hayas conectado y autorizado.':'Ask for outcomes in normal language. Cloudy turns a short instruction into actions across the accounts and tools you have connected and authorized.',
'Tu mano derecha operativa.':'Your operational right hand.',
'Puede revisar leads, preparar seguimiento, crear contenido, organizar campañas, analizar actividad, coordinar citas, trabajar con archivos conectados y ejecutar tareas comerciales.':'It can review leads, prepare follow-up, create content, organize campaigns, analyze activity, coordinate appointments, work with connected files, and execute sales tasks.',
'Un equipo de agentes dentro de CloudSales.':'A team of agents inside CloudSales.',
'Cloudy asigna trabajo especializado a AgentCloud según el canal y el objetivo. Tú ves el resultado y mantienes control sobre permisos, límites y aprobaciones.':'Cloudy assigns specialized work to AgentCloud based on the channel and objective. You see the result and keep control over permissions, limits, and approvals.',
'Entiende tu instrucción':'Understands your instruction','Consulta contexto':'Reviews context','Planifica':'Plans','Usa las conexiones autorizadas':'Uses authorized connections','Ejecuta':'Executes','Reporta resultado':'Reports results',
'Conecta tu CRM. O deja que CloudSales incluya la infraestructura.':'Connect your CRM. Or let CloudSales include the infrastructure.',
'Si ya trabajas con un CRM, puedes conectarlo para que Cloudy opere sobre él. Si no tienes CRM, no necesitas comprar otro por separado para comenzar.':'If you already use a CRM, connect it so Cloudy can operate on it. If you do not have a CRM, you do not need to buy another one separately to get started.',
'¿No tienes CRM?':'No CRM?','Continúa con CloudSales. La infraestructura de gestión que Cloudy necesita puede quedar incluida dentro de tu cuenta.':'Continue with CloudSales. The management infrastructure Cloudy needs can be included in your account.','Continuar':'Continue',
'Mejor calidad empieza antes de que el lead llegue al CRM.':'Better quality starts before the lead reaches the CRM.',
'CloudSales combina protección de entrada, validaciones, señales de comportamiento y feedback comercial. El objetivo es que el proceso publicitario y comercial reciba información más limpia y útil, no simplemente acumular formularios.':'CloudSales combines entry protection, validation, behavioral signals, and sales feedback. The goal is to give advertising and sales cleaner, more useful information instead of simply accumulating forms.',
'Bloquea automatización no deseada':'Blocks unwanted automation','WAF, desafíos anti-bot, honeypots, rate limiting y controles server-side reducen tráfico y registros automatizados antes del CRM.':'WAF, anti-bot challenges, honeypots, rate limiting, and server-side controls reduce automated traffic and registrations before the CRM.',
'Evalúa cada registro':'Evaluates every submission','Lead Quality utiliza señales disponibles para clasificar intención y riesgo y decidir aceptar, desafiar o rechazar según configuración.':'Lead Quality uses available signals to classify intent and risk and decide whether to accept, challenge, or reject according to configuration.',
'Aprende del resultado comercial':'Learns from sales outcomes','Web Events y CRM Events conectan el origen del lead con citas, oportunidades y resultados para producir feedback más útil.':'Web Events and CRM Events connect lead origin with appointments, opportunities, and outcomes to produce more useful feedback.',
'Devuelve mejores señales':'Returns better signals','Cuando las plataformas lo permiten, CloudSales prepara Conversion API, atribución y audiencias usando eventos de mayor valor.':'When platforms allow it, CloudSales prepares Conversion API, attribution, and audiences using higher-value events.',
'Por qué existe CloudSales':'Why CloudSales exists','Mejores leads. Menos trabajo desperdiciado.':'Better leads. Less wasted work.',
'CloudSales fue diseñado para reducir el desperdicio comercial: junk leads, seguimiento perdido, herramientas desconectadas y horas frente a un CRM complejo. Convierte tecnología comercial e inteligencia artificial en':'CloudSales was designed to reduce sales waste: junk leads, lost follow-up, disconnected tools, and hours spent in a complex CRM. It turns sales technology and artificial intelligence into',
'trabajo ejecutado':'executed work','y devuelve al negocio tiempo, visibilidad y capacidad operativa.':'and gives the business back time, visibility, and operating capacity.',
'Tres planes simples. Empieza controlando tu operación desde el celular y aumenta protección, automatización, agentes y capacidad de equipo conforme crece tu negocio. Servicios de terceros —mensajería, llamadas, IA u otros consumos— pueden generar cargos de uso según tu plan.':'Three simple plans. Start by controlling your operation from your phone and add protection, automation, agents, and team capacity as your business grows. Third-party services—messaging, calls, AI, or other usage—may generate usage charges depending on your plan.',
'USD / mes':'USD / month','Leads, pipeline y citas':'Leads, pipeline and appointments','Control desde celular / PWA':'Mobile / PWA control','Elegir Basic':'Choose Basic','Todo Basic':'Everything in Basic','Calificación y seguimiento automatizado':'Automated qualification and follow-up','Automatización avanzada + Data Signals':'Advanced automation + Data Signals','Elegir Pro':'Choose Pro','Todo Pro':'Everything in Pro','2 usuarios incluidos':'2 users included','Más conexiones + control de equipo':'More connections + team control','Prioridad de automatización':'Automation priority','Asientos adicionales: $47 USD / mes':'Additional seats: $47 USD / month','Elegir Premium':'Choose Premium',
'Más que una aplicación.':'More than an app.','CloudSales también incluye formación y servicios opcionales para quienes quieren combinar automatización con acompañamiento humano especializado.':'CloudSales also includes training and optional services for teams that want to combine automation with specialized human support.',
'Marketing digital + IA, CRM, automatización, webmaster, community management, campañas y entrenamiento para equipos.':'Digital marketing + AI, CRM, automation, webmaster, community management, campaigns, and team training.','Ver Academy':'View Academy','Servicios profesionales':'Professional services','Webmaster, Community Management, administración de campañas y Concierge Setup cuando prefieres delegar una parte de la ejecución.':'Webmaster, Community Management, campaign management, and Concierge Setup when you prefer to delegate part of the execution.','Ver Servicios':'View Services','Refiere CloudSales con tu propio link. Recibe 40% de comisión sobre las ventas elegibles atribuidas a tu enlace.':'Refer CloudSales with your own link. Receive a 40% commission on eligible sales attributed to your link.','Conocer programa':'View program',
'Instala CloudSales donde trabajas.':'Install CloudSales wherever you work.','La misma cuenta funciona en navegador y como PWA. Instálala directamente en iPhone/iPad, Android o computadora.':'The same account works in the browser and as a PWA. Install it directly on iPhone/iPad, Android, or desktop.',
'Preguntas frecuentes.':'Frequently asked questions.','Lo esencial antes de conectar tu negocio a CloudSales.':'What you need to know before connecting your business to CloudSales.',
'¿Qué es CloudSales?':'What is CloudSales?','Es una Business Management Platform operada por inteligencia artificial. Reúne la operación comercial y conecta las herramientas que ya usas para que Cloudy pueda ayudarte a ejecutar trabajo, no solo mostrar información.':'It is an AI-operated Business Management Platform. It brings sales operations together and connects the tools you already use so Cloudy can help execute work, not just display information.',
'¿CloudSales es un CRM?':'Is CloudSales a CRM?','No se limita a ser un CRM. Puede controlar un CRM existente o utilizar infraestructura de gestión incluida cuando no tienes uno. CloudSales se coloca por encima del stack como capa de operación, IA y experiencia móvil.':'It is not limited to being a CRM. It can control an existing CRM or use included management infrastructure when you do not have one. CloudSales sits above the stack as an operations, AI, and mobile experience layer.',
'¿Quién es Cloudy?':'Who is Cloudy?','Cloudy es el AI Operator central de CloudSales. Interpreta instrucciones, consulta contexto, coordina herramientas y AgentCloud, ejecuta acciones permitidas y reporta resultados.':'Cloudy is the central AI Operator in CloudSales. It interprets instructions, reviews context, coordinates tools and AgentCloud, executes permitted actions, and reports results.',
'¿Qué es AgentCloud?':'What is AgentCloud?','Es el conjunto de agentes de IA especializados de CloudSales. Pueden asumir funciones concretas —por ejemplo seguimiento, citas, contenido o mensajería— bajo políticas, permisos y supervisión de Cloudy.':'AgentCloud is CloudSales’ set of specialized AI agents. They can take on specific functions—such as follow-up, appointments, content, or messaging—under policies, permissions, and Cloudy supervision.',
'¿Puedo conservar mi CRM actual?':'Can I keep my current CRM?','Sí. La estrategia de CloudSales es conectarse con CRMs líderes y operar sobre ellos. La profundidad de cada integración depende de los permisos y APIs disponibles de cada proveedor.':'Yes. CloudSales is designed to connect with leading CRMs and operate on top of them. Integration depth depends on each provider’s available permissions and APIs.',
'¿Qué pasa si no tengo CRM?':'What if I do not have a CRM?','Puedes comenzar con CloudSales sin contratar un CRM adicional por separado. CloudSales puede incluir la infraestructura de gestión necesaria para contactos, pipeline, conversaciones y automatizaciones.':'You can start with CloudSales without purchasing a separate CRM. CloudSales can include the management infrastructure needed for contacts, pipeline, conversations, and automations.',
'¿Puedo importar mis contactos y oportunidades?':'Can I import my contacts and opportunities?','Sí, cuando el origen y el CRM conectado ofrecen exportación o APIs compatibles. CloudSales está diseñado para mapear contactos, oportunidades y campos para reducir la configuración manual.':'Yes, when the source and connected CRM provide export or compatible APIs. CloudSales is designed to map contacts, opportunities, and fields to reduce manual setup.',
'¿Cloudy puede actuar sin pedirme permiso cada vez?':'Can Cloudy act without asking me every time?','Puede automatizar tareas dentro del nivel de autonomía que autorices. Acciones sensibles, costosas, destructivas o con impacto legal pueden configurarse para pedir aprobación.':'It can automate tasks within the autonomy level you authorize. Sensitive, costly, destructive, or legally significant actions can be configured to require approval.',
'¿Cómo mejora CloudSales la calidad de los leads?':'How does CloudSales improve lead quality?','Actúa en varias capas: protege formularios y landings, detecta automatización no deseada, valida señales del registro, asigna un score de calidad, deduplica y conecta el comportamiento web con lo que después ocurre en el CRM. Ese feedback permite trabajar con señales comerciales más útiles.':'It works across several layers: protecting forms and landing pages, detecting unwanted automation, validating submission signals, assigning a quality score, deduplicating, and connecting web behavior with what later happens in the CRM. That feedback produces more useful sales signals.',
'¿CloudSales filtra después o puede bloquear antes del CRM?':'Does CloudSales filter afterward or can it block before the CRM?','El Junk Lead Firewall está diseñado para intervenir antes de que el registro pase al flujo comercial cuando la campaña utiliza una landing/gateway de CloudSales. Así se puede desafiar o rechazar tráfico sospechoso antes de contaminar el CRM.':'The Junk Lead Firewall is designed to intervene before a submission enters the sales flow when the campaign uses a CloudSales landing/gateway. Suspicious traffic can be challenged or rejected before it contaminates the CRM.',
'¿Qué son Web Events y CRM Events?':'What are Web Events and CRM Events?','Son eventos que conectan lo que una persona hace en la web con lo que ocurre después en ventas: lead aceptado, cita, oportunidad, avance de etapa, compra u otros resultados configurados.':'They are events that connect what a person does on the web with what happens later in sales: accepted lead, appointment, opportunity, stage progression, purchase, or other configured outcomes.',
'¿CloudSales puede trabajar con Meta, Google, TikTok y LinkedIn?':'Can CloudSales work with Meta, Google, TikTok, and LinkedIn?','La plataforma está diseñada para conectar ecosistemas publicitarios y sociales mediante APIs e integraciones disponibles. Cada conexión requiere autorización del propietario de la cuenta y está sujeta a las políticas de cada plataforma.':'The platform is designed to connect advertising and social ecosystems through available APIs and integrations. Each connection requires account-owner authorization and is subject to each platform’s policies.',
'¿Cloudy puede publicar contenido?':'Can Cloudy publish content?','Sí, cuando el usuario conecta los canales y archivos necesarios. Cloudy puede usar materiales autorizados —por ejemplo del Drive del negocio— para preparar contenido y coordinar su publicación.':'Yes, when the user connects the necessary channels and files. Cloudy can use authorized materials—for example from the business Drive—to prepare content and coordinate publishing.',
'¿Puedo trabajar solo desde mi celular?':'Can I work only from my phone?','Ese es uno de los objetivos centrales: reducir drásticamente la dependencia de la computadora. La PWA permite gestionar lo esencial y hablar con Cloudy desde el teléfono. Algunas autorizaciones externas pueden abrir páginas del proveedor.':'That is one of the core goals: dramatically reduce dependence on a computer. The PWA lets you manage the essentials and talk with Cloudy from your phone. Some external authorizations may open provider pages.',
'¿Funciona en iPhone, Android y computadora?':'Does it work on iPhone, Android, and desktop?','Sí. CloudSales es una PWA instalable y también funciona desde navegador. La misma cuenta se utiliza en todos los dispositivos compatibles.':'Yes. CloudSales is an installable PWA and also works in a browser. The same account is used across compatible devices.',
'¿Necesito conocimientos técnicos?':'Do I need technical knowledge?','No para la operación cotidiana. El diseño busca que el usuario describa objetivos y Cloudy se encargue de la mayor parte de la ejecución. Integraciones avanzadas pueden requerir permisos administrativos de las plataformas conectadas.':'Not for everyday operation. The design lets the user describe goals and Cloudy handle most of the execution. Advanced integrations may require administrative permissions on connected platforms.',
'¿Mis credenciales quedan visibles para Cloudy?':'Are my credentials visible to Cloudy?','Las integraciones sensibles se diseñan para trabajar con OAuth, tokens y almacenamiento seguro del lado servidor. La PWA no necesita mostrar secretos para operar las conexiones.':'Sensitive integrations are designed to use OAuth, tokens, and secure server-side storage. The PWA does not need to expose secrets to operate connections.',
'¿CloudSales reemplaza una agencia o un equipo completo?':'Does CloudSales replace an agency or a full team?','Puede eliminar muchas tareas manuales y reducir la necesidad de varias herramientas o servicios separados, pero cada negocio decide qué funciones automatizar y cuáles mantener con personas. También ofrecemos servicios profesionales opcionales.':'It can eliminate many manual tasks and reduce the need for multiple separate tools or services, but each business decides which functions to automate and which to keep human. Optional professional services are also available.',
'¿Hay costos adicionales?':'Are there additional costs?','La suscripción cubre el plan de CloudSales. Algunos servicios externos —mensajes, llamadas, modelos de IA, publicidad u otros consumos— pueden cobrarse por uso. Los servicios profesionales y Academy se venden por separado.':'The subscription covers the CloudSales plan. Some external services—messages, calls, AI models, advertising, or other usage—may be billed by usage. Professional services and Academy are sold separately.',
'¿Puedo cancelar?':'Can I cancel?','Sí. Puedes cancelar de acuerdo con los términos de tu suscripción y conservar acceso según las condiciones vigentes del periodo contratado.':'Yes. You can cancel according to your subscription terms and keep access according to the conditions of the current paid period.',
'CloudSales · Better Leads · Full CRM Control · un producto de CloudCo.':'CloudSales · Better Leads · Full CRM Control · a CloudCo product.','Las integraciones, automatizaciones y funciones disponibles dependen de permisos, APIs y políticas de cada proveedor.':'Available integrations, automations, and features depend on each provider’s permissions, APIs, and policies.',
'Activar CloudSales':'Activate CloudSales','Checkout seguro por Stripe':'Secure checkout by Stripe','Tu correo':'Your email','Escribe un correo válido.':'Enter a valid email.','Preparando checkout…':'Preparing checkout…','No pudimos abrir el checkout: ':'We could not open checkout: '
};

const TRIAL_COPY={
'es':{plan:'14 días gratis',pricing:'<b>14 días de prueba gratis.</b> Agrega tu método de pago hoy y no se cobra la mensualidad hasta que termine la prueba. Cancela antes de que termine si no deseas continuar.',checkout:'<b>Empieza con 14 días gratis.</b> Tu método de pago se guarda de forma segura en Stripe y la primera mensualidad se cobra al terminar la prueba, salvo que canceles antes.'},
'en':{plan:'14 days free',pricing:'<b>14-day free trial.</b> Add your payment method today and your monthly plan is not charged until the trial ends. Cancel before the trial ends if you do not want to continue.',checkout:'<b>Start with 14 days free.</b> Your payment method is stored securely by Stripe and the first monthly charge happens after the trial unless you cancel first.'},
'fr':{plan:'14 jours gratuits',pricing:'<b>Essai gratuit de 14 jours.</b> Ajoutez votre moyen de paiement aujourd’hui; l’abonnement mensuel n’est débité qu’à la fin de l’essai.',checkout:'<b>Commencez avec 14 jours gratuits.</b> Votre moyen de paiement est enregistré de façon sécurisée par Stripe.'},
'it':{plan:'14 giorni gratis',pricing:'<b>Prova gratuita di 14 giorni.</b> Aggiungi oggi il metodo di pagamento; il piano mensile viene addebitato solo al termine della prova.',checkout:'<b>Inizia con 14 giorni gratis.</b> Il metodo di pagamento viene conservato in sicurezza da Stripe.'},
'pt-BR':{plan:'14 dias grátis',pricing:'<b>Teste grátis por 14 dias.</b> Adicione hoje sua forma de pagamento; a mensalidade só é cobrada ao final do teste.',checkout:'<b>Comece com 14 dias grátis.</b> Sua forma de pagamento é armazenada com segurança pela Stripe.'},
'de':{plan:'14 Tage kostenlos',pricing:'<b>14 Tage kostenlos testen.</b> Hinterlegen Sie heute Ihre Zahlungsmethode; die Monatsgebühr wird erst nach dem Testzeitraum berechnet.',checkout:'<b>Starten Sie mit 14 kostenlosen Tagen.</b> Ihre Zahlungsmethode wird sicher bei Stripe gespeichert.'},
'ar-AE':{plan:'14 يوماً مجاناً',pricing:'<b>تجربة مجانية لمدة 14 يوماً.</b> أضف وسيلة الدفع اليوم ولن يتم تحصيل الاشتراك الشهري حتى انتهاء التجربة.',checkout:'<b>ابدأ بـ 14 يوماً مجاناً.</b> تحفظ Stripe وسيلة الدفع بأمان.'},
'ru':{plan:'14 дней бесплатно',pricing:'<b>14-дневный бесплатный период.</b> Добавьте способ оплаты сегодня; ежемесячная плата списывается только после окончания пробного периода.',checkout:'<b>Начните с 14 бесплатных дней.</b> Stripe безопасно сохранит способ оплаты.'},
'he':{plan:'14 ימים חינם',pricing:'<b>ניסיון חינם ל-14 ימים.</b> הוסיפו אמצעי תשלום היום; החיוב החודשי הראשון יתבצע רק לאחר תקופת הניסיון.',checkout:'<b>מתחילים עם 14 ימים חינם.</b> אמצעי התשלום נשמר באופן מאובטח ב-Stripe.'},
'zh-CN':{plan:'免费试用 14 天',pricing:'<b>14 天免费试用。</b> 今天添加付款方式，试用结束前不会收取月费。',checkout:'<b>先免费使用 14 天。</b> Stripe 会安全保存付款方式。'},
'ja':{plan:'14日間無料',pricing:'<b>14日間の無料トライアル。</b> 本日支払い方法を登録しても、月額料金はトライアル終了まで請求されません。',checkout:'<b>14日間無料で開始。</b> 支払い方法はStripeが安全に保存します。'}
};
function applyTrialCopy(locale){const c=TRIAL_COPY[locale]||TRIAL_COPY.en;document.querySelectorAll('[data-trial-copy="plan"]').forEach(x=>x.textContent=c.plan);document.querySelectorAll('[data-trial-copy="pricing"]').forEach(x=>x.innerHTML=c.pricing);document.querySelectorAll('[data-trial-copy="checkout"]').forEach(x=>x.innerHTML=c.checkout)}
function canonicalLocale(x){x=String(x||'').trim();const l=LANGS.find(v=>v[0].toLowerCase()===x.toLowerCase());if(l)return l[0];const short=x.toLowerCase().split('-')[0];return LANGS.find(v=>v[0].toLowerCase().split('-')[0]===short)?.[0]||'es'}
function detect(){const q=new URLSearchParams(location.search).get('lang');if(q)return canonicalLocale(q);try{const s=localStorage.getItem(STORE);if(s)return canonicalLocale(s)}catch{}return canonicalLocale(navigator.language||'es')}
function style(){if(document.getElementById(ID+'-css'))return;const s=document.createElement('style');s.id=ID+'-css';s.textContent=`.csLang{position:relative}.csLangBtn{border:1px solid #343443;background:#111119;color:#f5f4f8;border-radius:999px;padding:8px 10px;font-size:11px;font-weight:850;min-width:48px}.csLangMenu{display:none;position:absolute;right:0;top:calc(100% + 8px);width:210px;max-height:min(430px,70vh);overflow:auto;background:#111119;border:1px solid #343443;border-radius:17px;padding:7px;box-shadow:0 24px 70px #000b;z-index:120}.csLang.open .csLangMenu{display:grid}.csLangOpt{border:0;background:transparent;color:#d5d3dd;border-radius:11px;padding:9px 10px;text-align:left;font-size:11px;display:flex;justify-content:space-between;gap:10px}.csLangOpt:hover,.csLangOpt.active{background:#211725;color:#fff}.csLangOpt span:last-child{color:#77768a;font-size:9px}.csLangMobile{display:none}@media(max-width:940px){.csLangDesktop{display:none}.csLangMobile{display:block;margin-left:auto}.navin{gap:10px}}[dir="rtl"] .csLangMenu{right:auto;left:0}[dir="rtl"] .csLangOpt{text-align:right}`;document.head.appendChild(s)}
function translateText(locale){const dict=T[locale]||{};const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue?.trim())return NodeFilter.FILTER_REJECT;const p=n.parentElement;if(!p||['SCRIPT','STYLE','TEXTAREA','OPTION'].includes(p.tagName))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const nodes=[];while(w.nextNode())nodes.push(w.currentNode);for(const n of nodes){if(!n.__csOriginal)n.__csOriginal=n.nodeValue;const base=n.__csOriginal.trim();if(locale==='es'){n.nodeValue=n.__csOriginal;continue}const tr=dict[base]||EN_FULL[base];if(tr)n.nodeValue=n.__csOriginal.replace(base,tr)}}
function meta(locale){const desc={es:'CloudSales mejora la calidad de tus leads, reduce junk leads y te permite controlar tu CRM, conversaciones, citas y pipeline desde la palma de tu mano.',en:'CloudSales improves lead quality, reduces junk leads, and lets you manage your CRM, conversations, appointments, and pipeline from your phone.',fr:'CloudSales améliore la qualité des prospects, réduit les faux leads et vous permet de gérer CRM, conversations, rendez-vous et pipeline depuis votre téléphone.',it:'CloudSales migliora la qualità dei lead, riduce i lead spazzatura e ti permette di gestire CRM, conversazioni, appuntamenti e pipeline dal telefono.','pt-BR':'CloudSales melhora a qualidade dos leads, reduz leads ruins e permite controlar CRM, conversas, reuniões e pipeline pelo celular.',de:'CloudSales verbessert die Lead-Qualität, reduziert Junk-Leads und ermöglicht CRM, Gespräche, Termine und Pipeline vom Smartphone aus.','ar-AE':'يحسن CloudSales جودة العملاء المحتملين ويقلل العملاء غير الصالحين ويتيح إدارة CRM والمحادثات والمواعيد وخط المبيعات من الهاتف.',ru:'CloudSales повышает качество лидов, сокращает мусорные лиды и позволяет управлять CRM, диалогами, встречами и воронкой с телефона.',he:'CloudSales משפר את איכות הלידים, מפחית לידים לא רלוונטיים ומאפשר לנהל CRM, שיחות, פגישות ופייפליין מהטלפון.','zh-CN':'CloudSales 提升销售线索质量、减少垃圾线索，并可通过手机管理 CRM、对话、预约和销售管道。',ja:'CloudSalesはリード品質を高め、無効なリードを減らし、CRM・会話・商談・パイプラインをスマートフォンから管理できます。'};document.querySelector('meta[name="description"]')?.setAttribute('content',desc[locale]||desc.es);document.title=locale==='es'?'CloudSales — Better Leads. Full CRM Control.':'CloudSales — Better Leads. Full CRM Control.'}
function menu(locale){const html=LANGS.map(([code,short,name])=>`<button class="csLangOpt ${code===locale?'active':''}" data-lang="${code}"><b>${name}</b><span>${short}</span></button>`).join('');return `<div class="csLang"><button class="csLangBtn" aria-label="Language">${LANGS.find(x=>x[0]===locale)?.[1]||'ES'} ▾</button><div class="csLangMenu">${html}</div></div>`}
function mount(locale){document.querySelectorAll('.csLang').forEach(x=>x.remove());const links=document.querySelector('.navlinks');if(links){const d=document.createElement('div');d.className='csLangDesktop';d.innerHTML=menu(locale);links.insertBefore(d,links.firstChild)}const navin=document.querySelector('.navin');if(navin){const m=document.createElement('div');m.className='csLangMobile';m.innerHTML=menu(locale);navin.appendChild(m)}document.querySelectorAll('.csLangBtn').forEach(b=>b.onclick=e=>{e.stopPropagation();b.closest('.csLang')?.classList.toggle('open')});document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLocale(b.dataset.lang));if(!document.documentElement.dataset.csLangCloseBound){document.documentElement.dataset.csLangCloseBound='1';document.addEventListener('click',e=>{if(!e.target.closest('.csLang'))document.querySelectorAll('.csLang.open').forEach(x=>x.classList.remove('open'))},true)}}
function attrs(locale){const d=T[locale]||{},tr=x=>locale==='es'?x:(d[x]||EN_FULL[x]||x);const email=document.getElementById('cemail');if(email){if(!email.dataset.csOrigPlaceholder)email.dataset.csOrigPlaceholder=email.getAttribute('placeholder')||'';email.setAttribute('placeholder',tr(email.dataset.csOrigPlaceholder))}const err=document.getElementById('cerr');if(err&&!err.dataset.csI18nObs){err.dataset.csI18nObs='1';new MutationObserver(()=>{const v=err.textContent||'';if(locale==='es')return;for(const [a,b] of Object.entries({...EN_FULL,...d})){if(v===a){err.textContent=b;return}if(a.endsWith(': ')&&v.startsWith(a)){err.textContent=b+v.slice(a.length);return}}}).observe(err,{childList:true,characterData:true,subtree:true})}}
function setLocale(x){const locale=canonicalLocale(x);try{localStorage.setItem(STORE,locale)}catch{}const u=new URL(location.href);u.searchParams.set('lang',locale);history.replaceState(null,'',u);apply(locale)}
function apply(locale){document.documentElement.lang=locale;document.documentElement.dir=RTL.has(locale)?'rtl':'ltr';translateText(locale);meta(locale);mount(locale);document.documentElement.dataset.csLocale=locale;attrs(locale);applyTrialCopy(locale);window.dispatchEvent(new CustomEvent('cloudsales:locale',{detail:{locale}}))}
function patchHostedCheckout(){
  const start=document.getElementById('cstart'),email=document.getElementById('cemail'),mount=document.getElementById('stripeMount'),err=document.getElementById('cerr');
  if(!start||!email||!mount||!err||start.dataset.csHostedPatched==='1')return;
  let item='';
  document.querySelectorAll('.buy[data-item]').forEach(b=>b.addEventListener('click',()=>{item=b.dataset.item||''}));
  start.dataset.csHostedPatched='1';
  start.onclick=async()=>{
    const mail=email.value.trim();if(!mail||!item){err.textContent='Escribe un correo válido.';return}
    err.textContent='Preparando checkout…';start.disabled=true;
    try{
      const ref=new URL(location.href).searchParams.get('ref')||localStorage.getItem('cloudsales_ref')||'';if(ref)localStorage.setItem('cloudsales_ref',ref);
      const r=await fetch('https://fkahaqprzgcimgyathqx.supabase.co/functions/v1/stripe-checkout-start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({item_key:item,email:mail,affiliate_code:ref})});
      const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||'checkout_error');
      if(d.checkout_url){location.assign(d.checkout_url);return}
      if(!d.client_secret||!d.publishable_key)throw Error('checkout_not_available');
      const stripe=Stripe(d.publishable_key),instance=await stripe.initEmbeddedCheckout({clientSecret:d.client_secret});
      document.getElementById('emailrow').style.display='none';err.textContent='';instance.mount('#stripeMount');
    }catch(e){err.textContent='No pudimos abrir el checkout: '+(e?.message||'error');start.disabled=false}
  };
}
function checkoutReturnBridge(){try{const u=new URL(location.href),sid=u.searchParams.get('session_id')||'';if(u.searchParams.get('checkout')==='return'&&/^cs_(?:test|live)_/.test(sid)){const saved=localStorage.getItem(STORE)||'',lang=u.searchParams.get('lang')||saved,d=new URL('https://app.cloudsales.app/');d.searchParams.set('checkout','return');d.searchParams.set('session_id',sid);if(lang)d.searchParams.set('lang',lang);location.replace(d.toString());return true}}catch{}return false}
style();if(checkoutReturnBridge())return;patchHostedCheckout();const locale=detect();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>apply(locale),{once:true});else apply(locale);window.CloudSalesI18n={setLocale,getLocale:()=>canonicalLocale(document.documentElement.dataset.csLocale||locale),languages:LANGS.map(x=>x[0])};
})();


/* CS_DOMAINS_SEARCH_RUNTIME_V3 */
(()=>{
'use strict';
if(!document.getElementById('domain')||!document.getElementById('search'))return;
const $=id=>document.getElementById(id),input=$('domain'),btn=$('search'),result=$('result'),purchase=$('purchase');
const norm=v=>String(v||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0].replace(/\.$/,'');
const valid=d=>/^(?=.{3,253}$)([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(d);
function set(name,status,cls,price='—',renew='—',note=''){ $('domainName').textContent=name||'Dominio'; $('availability').className=cls; $('availability').textContent=status; $('price').textContent=price; $('renew').textContent=renew; $('note').textContent=note; result.classList.add('show'); }
async function go(e){e&&e.preventDefault();const d=norm(input.value);input.value=d;purchase&&purchase.classList.remove('show');if(!valid(d)){set(d,'ESCRIBE UN DOMINIO VÁLIDO','unavailable','—','—','Ejemplo: minegocio.com');return;}btn.disabled=true;btn.textContent='BUSCANDO…';set(d,'CONSULTANDO…','available','—','—','Buscando disponibilidad del dominio…');try{const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);const r=await fetch('/api/domain-quote?domain='+encodeURIComponent(d),{cache:'no-store',headers:{accept:'application/json'},signal:c.signal});clearTimeout(t);const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.message||j.error||'search_failed');if(j.availability==='registered'||j.registrable===false)set(d,'NO DISPONIBLE','unavailable','—','—',j.message||'Este dominio ya está registrado.');else if(j.provisional||j.availability==='possibly_available'){set(d,'POSIBLEMENTE DISPONIBLE','available','POR CONFIRMAR','POR CONFIRMAR',j.message||'Parece disponible. Confirmaremos disponibilidad y precio antes de cualquier cobro.');purchase&&purchase.classList.add('show');}else if(j.registrable===true){const cur=j.currency||'USD',fmt=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:cur}).format(v);set(d,'✓ DISPONIBLE','available',fmt(j.sale_amount??j.normal?.registration),fmt(j.normal?.renewal)+'/año','Disponibilidad confirmada por el registrador.');purchase&&purchase.classList.add('show');}else set(d,'RESULTADO NO CONCLUYENTE','unavailable','—','—','Intenta nuevamente en unos segundos.');}catch(x){set(d,'NO PUDIMOS CONSULTAR AHORA','unavailable','—','—','No pudimos completar la consulta. Intenta nuevamente.');}finally{btn.disabled=false;btn.textContent='BUSCAR';}}
btn.addEventListener('click',go,true);input.addEventListener('keydown',e=>{if(e.key==='Enter')go(e)},true);
})();
