(() => {
'use strict';
if(window.CloudSalesWebChatLoaded)return;window.CloudSalesWebChatLoaded=true;
const API='https://fkahaqprzgcimgyathqx.supabase.co/functions/v1/public-landing-data';
const script=document.currentScript;
const cfg={hostname:(script?.dataset?.hostname||location.hostname).toLowerCase(),title:script?.dataset?.title||'¿Necesitas ayuda?',welcome:script?.dataset?.welcome||'Hola. ¿En qué podemos ayudarte?',position:script?.dataset?.position||'right',accent:script?.dataset?.accent||'#F955B6'};
const key=`cloudsales_webchat_${cfg.hostname}`;let sessionToken=localStorage.getItem(key)||'',last='',poller=null,startedAt=Date.now(),opened=false,polling=false,history=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`request_${r.status}`);return d}
function style(){if(document.getElementById('cs-webchat-css'))return;const s=document.createElement('style');s.id='cs-webchat-css';s.textContent=`.cswc-launch{position:fixed;${cfg.position==='left'?'left':'right'}:18px;bottom:18px;z-index:2147483000;width:58px;height:58px;border:0;border-radius:50%;background:${cfg.accent};color:#fff;font:900 24px/1 system-ui;box-shadow:0 16px 45px #0005;cursor:pointer}.cswc{position:fixed;${cfg.position==='left'?'left':'right'}:18px;bottom:88px;z-index:2147483000;width:min(380px,calc(100vw - 24px));height:min(610px,calc(100vh - 112px));display:none;grid-template-rows:auto 1fr auto;background:#0d0d14;color:#fff;border:1px solid #30303d;border-radius:24px;overflow:hidden;box-shadow:0 32px 100px #000a;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.cswc.open{display:grid}.cswc-head{padding:15px 16px;background:linear-gradient(135deg,#181824,#101018);border-bottom:1px solid #292936;display:flex;align-items:center;justify-content:space-between;gap:10px}.cswc-head b{display:block;font-size:15px}.cswc-head span{display:block;color:#9291a2;font-size:10px;margin-top:3px}.cswc-close{border:0;background:#ffffff12;color:#fff;border-radius:50%;width:34px;height:34px;font-size:20px}.cswc-msgs{padding:16px;overflow:auto;display:flex;flex-direction:column;gap:9px;background:radial-gradient(circle at 50% -10%,#191927,#0a0a10 45%)}.cswc-b{max-width:82%;padding:10px 12px;border-radius:16px;font-size:12px;line-height:1.5;white-space:pre-wrap;word-break:break-word}.cswc-in{align-self:flex-start;background:#1b1b25;border:1px solid #2d2d3a}.cswc-out{align-self:flex-end;background:linear-gradient(135deg,#8e2cff,${cfg.accent})}.cswc-time{font-size:8px;opacity:.55;margin-top:4px}.cswc-compose{padding:11px;border-top:1px solid #292936;background:#0d0d14}.cswc-row{display:grid;grid-template-columns:1fr auto;gap:7px}.cswc-input{resize:none;min-height:44px;max-height:110px;border:1px solid #343442;background:#15151d;color:#fff;border-radius:13px;padding:11px;font:12px system-ui}.cswc-send{border:0;border-radius:13px;background:${cfg.accent};color:#fff;font-weight:900;padding:0 15px}.cswc-status{font-size:9px;color:#858596;margin:0 0 7px}.cswc-ident{display:none;gap:6px;margin-bottom:7px}.cswc-ident.show{display:grid;grid-template-columns:1fr 1fr}.cswc-ident input{min-width:0;border:1px solid #30303e;background:#15151d;color:#fff;border-radius:10px;padding:8px;font-size:10px}@media(max-width:520px){.cswc{left:8px!important;right:8px!important;bottom:78px;width:auto;height:calc(100vh - 92px);border-radius:20px}.cswc-launch{bottom:12px;${cfg.position==='left'?'left':'right'}:12px}}`;document.head.appendChild(s)}
function build(){style();const launch=document.createElement('button');launch.className='cswc-launch';launch.type='button';launch.setAttribute('aria-label','Abrir chat');launch.textContent='✦';const box=document.createElement('section');box.className='cswc';box.setAttribute('aria-label','CloudSales Web Chat');box.innerHTML=`<header class="cswc-head"><div><b>${esc(cfg.title)}</b><span>Web Chat · AI CHAT</span></div><button class="cswc-close" type="button" aria-label="Cerrar">×</button></header><div class="cswc-msgs" id="cswcMsgs"><div class="cswc-b cswc-in">${esc(cfg.welcome)}</div></div><footer class="cswc-compose"><div class="cswc-status" id="cswcStatus">Escribe un mensaje para comenzar.</div><div class="cswc-ident" id="cswcIdent"><input id="cswcName" placeholder="Nombre"><input id="cswcEmail" type="email" placeholder="Email"></div><div class="cswc-row"><textarea class="cswc-input" id="cswcInput" placeholder="Escribe tu mensaje..."></textarea><button class="cswc-send" id="cswcSend" type="button">Enviar</button></div><input id="cswcWebsite" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px;opacity:0" aria-hidden="true"></footer>`;document.body.append(launch,box);launch.onclick=()=>{opened=!opened;box.classList.toggle('open',opened);if(opened){document.getElementById('cswcInput')?.focus();if(sessionToken)poll()}else stopPolling()};box.querySelector('.cswc-close').onclick=()=>{opened=false;box.classList.remove('open');stopPolling()};box.querySelector('#cswcSend').onclick=send;box.querySelector('#cswcInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};if(!sessionToken)box.querySelector('#cswcIdent').classList.add('show');return box}
const box=build();
function time(v){const d=new Date(v);return isNaN(d.getTime())?'':d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function render(messages){const el=document.getElementById('cswcMsgs');if(!el)return;const welcome=`<div class="cswc-b cswc-in">${esc(cfg.welcome)}</div>`;el.innerHTML=welcome+(messages||[]).map(m=>`<div class="cswc-b ${m.direction==='outbound'?'cswc-in':'cswc-out'}">${esc(m.body||'')}${m.occurred_at?`<div class="cswc-time">${esc(time(m.occurred_at))}</div>`:''}</div>`).join('');el.scrollTop=el.scrollHeight}
function mergeMessages(items){const seen=new Set(history.map(m=>String(m.id||`${m.occurred_at}|${m.direction}|${m.body}`)));for(const m of items||[]){const k=String(m.id||`${m.occurred_at}|${m.direction}|${m.body}`);if(seen.has(k))continue;seen.add(k);history.push(m)}history.sort((a,b)=>new Date(a.occurred_at||0)-new Date(b.occurred_at||0))}
async function start(message){const name=document.getElementById('cswcName')?.value.trim(),email=document.getElementById('cswcEmail')?.value.trim(),website=document.getElementById('cswcWebsite')?.value||'';const d=await api({action:'chat.start',hostname:cfg.hostname,started_at:startedAt,website,identity:{name,email},message});sessionToken=d.session_token;localStorage.setItem(key,sessionToken);document.getElementById('cswcIdent')?.classList.remove('show');history=[];last='';return d}
function stopPolling(){clearTimeout(poller);poller=null}
function schedulePoll(delay=5000){stopPolling();if(!sessionToken||!opened||document.visibilityState==='hidden')return;poller=setTimeout(poll,delay)}
async function send(){const input=document.getElementById('cswcInput'),btn=document.getElementById('cswcSend'),status=document.getElementById('cswcStatus'),message=input?.value.trim();if(!message||btn.disabled)return;btn.disabled=true;status.textContent='Enviando…';try{if(!sessionToken)await start(message);else await api({action:'chat.send',session_token:sessionToken,message});input.value='';status.textContent='Mensaje enviado.';if(opened)await poll()}catch(e){status.textContent=e.message==='too_fast'?'Espera un momento y vuelve a intentar.':'No pude enviar el mensaje.'}finally{btn.disabled=false}}
async function poll(){if(!sessionToken||!opened||document.visibilityState==='hidden'||polling){schedulePoll();return}polling=true;try{const d=await api({action:'chat.poll',session_token:sessionToken,after:last||undefined});const msgs=d.messages||[];if(msgs.length){mergeMessages(msgs);last=msgs[msgs.length-1].occurred_at||last;render(history)}document.getElementById('cswcStatus').textContent='AI CHAT conectado'}catch(e){if(e.message==='invalid_session'){localStorage.removeItem(key);sessionToken='';history=[];last='';document.getElementById('cswcIdent')?.classList.add('show')}}finally{polling=false;schedulePoll()}}
if(sessionToken)document.getElementById('cswcStatus').textContent='AI CHAT listo';
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&opened&&sessionToken)poll();else if(document.visibilityState==='hidden')stopPolling()});
})();